import test from 'node:test';import assert from 'node:assert/strict';
import {SessionHistory} from '../src/experimental/session.js';import {planDawEdit} from '../server/daw-agent.js';import {defaultBounceSettings} from '../src/experimental/bounce-settings.js';import {prepareAudioStretch} from '../src/experimental/audio-stretch-region.js';
const setup=()=>{const h=new SessionHistory();h.execute([{op:'track.add',values:{id:'audio',kind:'audio'}},{op:'region.add',target:'audio',values:{id:'clip',assetId:'source',duration:2}}]);const session=h.session;return {session,instruction:'Make this 25% longer without changing pitch',allowAudioStretch:true,exportContext:{sessionId:session.id,revision:session.revision,regionId:'clip',settings:defaultBounceSettings}};};
const adapter=(name,args,observe=()=>{})=>({key:'test',model:'test',fetchImpl:async(_,options)=>{observe(JSON.parse(options.body));return {ok:true,json:async()=>({output:[{type:'function_call',name,arguments:JSON.stringify(args)}]})};}});
test('agent stretch resolves captured selection and exposes a strict dedicated render tool',async()=>{const input=setup(),before=structuredClone(input.session);let body;const result=await planDawEdit(input,adapter('stretch_audio_region',{regionId:null,ratio:1.25},b=>body=b));assert.equal(result.action,'stretch_audio_region');assert.deepEqual(result.stretch,{regionId:'clip',ratio:1.25});assert.deepEqual(result.commands,[]);assert.equal(result.revision,before.revision);assert.deepEqual(input.session,before);assert.equal(body.tools.find(t=>t.name==='stretch_audio_region').strict,true);});
test('agent stretch rejects disabled capability, continuation, bad ratios, unknown sources and stale context',async()=>{const input=setup(),action={regionId:'clip',ratio:1.5};for(const altered of [{...input,allowAudioStretch:false},{...input,editingContinuation:true},{...input,exportContext:{...input.exportContext,revision:999}}])await assert.rejects(planDawEdit(altered,adapter('stretch_audio_region',action)));for(const altered of [{...action,ratio:3},{...action,ratio:0},{...action,regionId:'missing'},{...action,assetId:'fake'}])await assert.rejects(planDawEdit(input,adapter('stretch_audio_region',altered)));assert.throws(()=>prepareAudioStretch(input.session,action,{...input.exportContext,sessionId:'other'}),/context/);});
test('agent cannot fabricate stretch output through ordinary editing',async()=>{const input=setup();await assert.rejects(planDawEdit(input,adapter('edit_session',{summary:'fake',commands:[{op:'region.commitStretch',target:'clip',values:{ratio:1.5,assetId:'fake',sampleRate:48000,channels:1,frames:144000}}]})),/never fabricate/);});

test('agent musical stretch resolves tempo-map duration through a dedicated strict tool',async()=>{const input=setup();input.session.tempoChanges=[{id:'slow',beat:2,bpm:60}];let body;const result=await planDawEdit(input,adapter('fit_audio_region_beats',{regionId:null,beats:4},b=>body=b));assert.equal(result.action,'stretch_audio_region');assert.deepEqual(result.stretch,{regionId:'clip',ratio:1.5});assert.equal(body.tools.find(t=>t.name==='fit_audio_region_beats').strict,true);await assert.rejects(planDawEdit({...input,allowAudioStretch:false},adapter('fit_audio_region_beats',{regionId:null,beats:4})));await assert.rejects(planDawEdit(input,adapter('fit_audio_region_beats',{regionId:null,beats:20})),/50–200/);});

test('agent pitch transposition resolves selection and rejects invalid ranges and fabricated assets',async()=>{const input=setup(),result=await planDawEdit(input,adapter('transpose_audio_region',{regionId:null,semitones:-3.5}));assert.equal(result.action,'transpose_audio_region');assert.deepEqual(result.pitch,{regionId:'clip',semitones:-3.5});await assert.rejects(planDawEdit(input,adapter('transpose_audio_region',{regionId:null,semitones:13})));await assert.rejects(planDawEdit({...input,allowAudioStretch:false},adapter('transpose_audio_region',{regionId:null,semitones:3})));await assert.rejects(planDawEdit(input,adapter('edit_session',{summary:'fake',commands:[{op:'region.commitPitch',target:'clip',values:{semitones:3,assetId:'fake',sampleRate:48000,channels:1,frames:96000}}]})),/never fabricate/);});
