import test from 'node:test';import assert from 'node:assert/strict';import {SessionHistory,sessionSchema,newSession} from '../src/experimental/session.js';
const setup=()=>{const h=new SessionHistory();h.execute([{op:'track.add',values:{id:'a',kind:'audio'}},{op:'track.add',values:{id:'b',kind:'midi'}},...['a1','a2'].map(id=>({op:'region.add',target:'a',values:{id}})),{op:'region.add',target:'b',values:{id:'b1'}}]);return h;};
test('scenes default empty and persist references without copying or changing source clips',()=>{assert.deepEqual(sessionSchema.parse(newSession()).scenes,[]);const h=setup(),before=structuredClone(h.session.tracks);h.execute([{op:'scene.add',values:{id:'s',name:'Verse',regionIds:'a1,b1'}}]);assert.deepEqual(h.session.scenes[0],{id:'s',name:'Verse',cells:[{regionId:'a1',loop:true},{regionId:'b1',loop:true}]});assert.deepEqual(h.session.tracks,before);assert.deepEqual(new SessionHistory(JSON.parse(JSON.stringify(h.session))).session,h.session);h.undo();assert.equal(h.session.scenes.length,0);h.redo();assert.equal(h.session.scenes.length,1);});
test('scene cells replace per track, support one-shots and ordered scene edits',()=>{const h=setup();h.execute([{op:'scene.add',values:{id:'s',name:'Verse',regionIds:'a1,b1'}},{op:'scene.add',values:{id:'s2',name:'Chorus'}},{op:'scene.cell.set',target:'s',values:{regionId:'a2',loop:false}},{op:'scene.rename',target:'s',values:{name:'Intro'}},{op:'scene.move',target:'s2',values:{index:0}}]);assert.equal(h.session.scenes[0].id,'s2');assert.deepEqual(h.session.scenes[1].cells[0],{regionId:'a2',loop:false});h.execute([{op:'scene.cell.delete',target:'s',values:{regionId:'b1'}},{op:'scene.delete',target:'s2'}]);assert.equal(h.session.scenes.length,1);assert.equal(h.session.scenes[0].cells.length,1);});
test('deleting source clips prunes references in the same undo step',()=>{const h=setup();h.execute([{op:'scene.add',values:{id:'s',name:'Verse',regionIds:'a1,b1'}}]);const before=structuredClone(h.session);h.execute([{op:'track.delete',target:'a'}]);assert.deepEqual(h.session.scenes[0].cells,[{regionId:'b1',loop:true}]);h.undo();assert.deepEqual(h.session.tracks,before.tracks);assert.deepEqual(h.session.scenes,before.scenes);});
test('invalid cells, duplicate scene IDs, source-track collisions and malformed imports reject',()=>{const h=setup();for(const regionIds of ['a1,a2','missing','a1,a1']){const before=structuredClone(h.session);assert.throws(()=>h.execute([{op:'scene.add',values:{id:'s',name:'Bad',regionIds}}]));assert.deepEqual(h.session,before);}h.execute([{op:'scene.add',values:{id:'s',name:'Verse',regionIds:'a1,b1'}}]);const before=structuredClone(h.session);assert.throws(()=>h.execute([{op:'scene.add',values:{id:'s',name:'Duplicate'}}]));assert.throws(()=>h.execute([{op:'scene.cell.set',target:'s',values:{regionId:'missing'}}]));assert.deepEqual(h.session,before);const bad=structuredClone(before);bad.scenes[0].cells[0].regionId='missing';assert.throws(()=>new SessionHistory(bad));});
test('source deletion followed by scene editing stays atomic and invalid track collisions reject',()=>{const h=setup();h.execute([{op:'scene.add',values:{id:'s',name:'Scene',regionIds:'a1,b1'}}]);h.execute([{op:'region.delete',target:'a1'},{op:'scene.rename',target:'s',values:{name:'Renamed'}}]);assert.deepEqual(h.session.scenes[0].cells,[{regionId:'b1',loop:true}]);h.undo();const before=structuredClone(h.session);h.execute([{op:'track.add',values:{id:'c',kind:'audio'}},{op:'region.add',target:'c',values:{id:'c1'}},{op:'scene.cell.set',target:'s',values:{regionId:'c1'}}]);const saved=structuredClone(h.session);assert.throws(()=>h.execute([{op:'region.move',target:'c1',values:{trackId:'a'}}]),/one clip per track/);assert.deepEqual(h.session,saved);assert.equal(before.scenes[0].cells.length,2);});
test('agent can create validated scene definitions without altering source media',async()=>{const {planDawEdit}=await import('../server/daw-agent.js');const h=setup(),before=structuredClone(h.session),commands=[{op:'scene.add',values:{id:'s',name:'Verse',regionIds:'a1,b1'}}];const plan=await planDawEdit({session:h.session,instruction:'Save a Verse scene with a1 and b1'},{key:'test',model:'test',fetchImpl:async()=>({ok:true,json:async()=>({output:[{type:'function_call',name:'edit_session',arguments:JSON.stringify({summary:'Saved scene definition',commands})}]})})});assert.deepEqual(h.session,before);h.execute(plan.commands,plan.revision);assert.deepEqual(h.session.tracks,before.tracks);assert.equal(h.session.scenes[0].cells.length,2);});

test('duplicate scenes preserve loop flags, select adjacent ordering and independent assignments with undo',()=>{
 const h=setup();h.execute([{op:'scene.add',values:{id:'s',name:'Verse',regionIds:'a1,b1'}},{op:'scene.cell.set',target:'s',values:{regionId:'a1',loop:false}},{op:'scene.add',values:{id:'next',name:'Chorus'}}]);
 const before=structuredClone(h.session);h.execute([{op:'scene.duplicate',target:'s',values:{id:'copy'}}]);
 assert.deepEqual(h.session.scenes.map(s=>s.id),['s','copy','next']);assert.equal(h.session.scenes[1].name,'Verse copy');assert.deepEqual(h.session.scenes[0].cells,h.session.scenes[1].cells);assert.deepEqual(h.session.tracks,before.tracks);
 h.undo();assert.deepEqual(h.session.scenes,before.scenes);h.redo();h.execute([{op:'scene.cell.set',target:'copy',values:{regionId:'a2',loop:true}}]);assert.deepEqual(h.session.scenes[0],before.scenes[0]);assert.equal(h.session.scenes[1].cells[0].regionId,'a2');
 const restored=new SessionHistory(JSON.parse(JSON.stringify(h.session)));assert.deepEqual(restored.session.scenes,h.session.scenes);
});
test('duplicate scene names stay unique and within bounds; invalid duplicates roll back the batch',()=>{
 const h=setup();h.execute([{op:'scene.add',values:{id:'s',name:'x'.repeat(100)}},{op:'scene.duplicate',target:'s',values:{id:'copy'}},{op:'scene.duplicate',target:'s',values:{id:'copy2'}}]);
 assert.equal(new Set(h.session.scenes.map(s=>s.name)).size,3);assert.ok(h.session.scenes.every(s=>s.name.length<=100));
 const before=structuredClone(h.session);for(const values of [{id:'s'},{name:''},{unknown:true}]){assert.throws(()=>h.execute([{op:'scene.rename',target:'s',values:{name:'Changed'}},{op:'scene.duplicate',target:'s',values}]));assert.deepEqual(h.session,before);}
 assert.throws(()=>h.execute([{op:'scene.duplicate',target:'missing',values:{}}]));
 h.execute(Array.from({length:61},(_,i)=>({op:'scene.add',values:{id:`extra${i}`,name:`Extra ${i}`}})));assert.throws(()=>h.execute([{op:'scene.duplicate',target:'s',values:{}}]),/64 scenes/);assert.equal(h.session.scenes.length,64);
});
test('agent can duplicate and customize a scene in one undoable batch',async()=>{
 const {planDawEdit}=await import('../server/daw-agent.js');const h=setup();h.execute([{op:'scene.add',values:{id:'s',name:'Verse',regionIds:'a1,b1'}}]);const before=structuredClone(h.session),commands=[{op:'scene.duplicate',target:'s',values:{id:'variation',name:'Verse variation'}},{op:'scene.cell.set',target:'variation',values:{regionId:'a2',loop:false}}];
 const plan=await planDawEdit({session:h.session,instruction:'Duplicate Verse as Verse variation and use a2 once'},{key:'test',model:'test',fetchImpl:async()=>({ok:true,json:async()=>({output:[{type:'function_call',name:'edit_session',arguments:JSON.stringify({summary:'Created variation',commands})}]})})});
 h.execute(plan.commands,plan.revision);assert.deepEqual(h.session.scenes[0],before.scenes[0]);assert.deepEqual(h.session.scenes[1].cells[0],{regionId:'a2',loop:false});h.undo();assert.deepEqual(h.session.scenes,before.scenes);
});
