import test from 'node:test';import assert from 'node:assert/strict';import {audioStatistics} from '../src/experimental/audio-statistics.js';import {validateMixAnalysis,currentMixAnalysis} from '../src/experimental/mix-analysis.js';import {SessionHistory,newSession} from '../src/experimental/session.js';import {planDawEdit} from '../server/daw-agent.js';
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-9,`${a} != ${b}`);
const fixture=()=>{const s=new SessionHistory(newSession()).session;return {s,a:{sessionId:s.id,revision:s.revision,measuredAt:Date.now(),sampleRate:48000,frames:48000,channels:audioStatistics([new Float32Array(48000),new Float32Array(48000)])}};};
test('full sample statistics handle silence, polarity, first peak location, RMS and above-full-scale counts',()=>{const [a,b]=audioStatistics([Float32Array.from([0,.5,-1,1,-1.5]),new Float32Array(5)]);near(a.peakDb,20*Math.log10(1.5));near(a.rmsDb,10*Math.log10(4.5/5));assert.equal(a.peakFrame,4);assert.equal(a.overSamples,1);assert.deepEqual(b,{peakDb:null,rmsDb:null,peakFrame:null,overSamples:0});const [first]=audioStatistics([Float32Array.from([-1,1]),new Float32Array(2)]);assert.equal(first.peakFrame,0);assert.equal(first.overSamples,0);});
test('statistics reject malformed audio and non-finite sample values',()=>{for(const input of [[],[new Float32Array(1)],[new Float32Array(),new Float32Array()],[new Float32Array(1),new Float32Array(2)],[Float32Array.from([NaN]),new Float32Array(1)],[Float32Array.from([Infinity]),new Float32Array(1)]])assert.throws(()=>audioStatistics(input));});
test('analysis is tied to exact document revision and rendered frame count, with consistent channel measurements',()=>{const {s,a}=fixture();assert.deepEqual(validateMixAnalysis(a,s),a);assert.equal(currentMixAnalysis(a,{...s,revision:s.revision+1}),undefined);assert.equal(currentMixAnalysis(a,{...s,id:'other'}),undefined);for(const patch of [{frames:47999},{measuredAt:Date.now()+10000},{channels:[{peakDb:-6,rmsDb:0,peakFrame:1,overSamples:0},a.channels[1]]},{channels:[{peakDb:1,rmsDb:-2,peakFrame:1,overSamples:0},a.channels[1]]},{channels:[{peakDb:null,rmsDb:null,peakFrame:1,overSamples:0},a.channels[1]]},{channels:[{peakDb:0,rmsDb:0,peakFrame:48000,overSamples:0},a.channels[1]]}])assert.throws(()=>validateMixAnalysis({...a,...patch},s));assert.ok(validateMixAnalysis({...a,measuredAt:Date.now()-3600000},s));});
test('agent receives current full-mix measurements and rejects stale results before invoking a provider',async()=>{const {s,a}=fixture();let sent,calls=0;const options={key:'test',model:'test',fetchImpl:async(_,request)=>{calls++;sent=JSON.parse(request.body);return {ok:true,json:async()=>({output:[{type:'message',content:[{type:'output_text',text:'The rendered mix is silent.'}]}]})};}};const result=await planDawEdit({session:s,instruction:'What is the peak?',mixAnalysis:a},options);assert.deepEqual(JSON.parse(sent.input.at(-1).content).mixAnalysis,a);assert.deepEqual(result.commands,[]);assert.equal(sent.store,false);await assert.rejects(planDawEdit({session:s,instruction:'Measure',mixAnalysis:{...a,revision:999}},options),/does not match/);assert.equal(calls,1);});
test('agent can request a bounded browser analysis only when available and current measurements are missing',async()=>{
 const {s,a}=fixture();let sent;const reply=(calls)=>({key:'test',model:'test',fetchImpl:async(_,request)=>{sent=JSON.parse(request.body);return {ok:true,json:async()=>({output:calls})};}}),call={type:'function_call',name:'analyze_mix',arguments:'{}'};
 const result=await planDawEdit({session:s,instruction:'Measure the mix',allowAnalysis:true},reply([call]));assert.equal(result.action,'analyze_mix');assert.equal(result.revision,s.revision);assert.deepEqual(result.commands,[]);assert.ok(sent.tools.some(t=>t.name==='analyze_mix'));assert.equal(sent.parallel_tool_calls,false);
 for(const input of [{allowAnalysis:false},{allowAnalysis:true,mixAnalysis:a}]){await assert.rejects(planDawEdit({session:s,instruction:'Measure',...input},reply([call])),/Unexpected/);assert.ok(!sent.tools.some(t=>t.name==='analyze_mix'));}
 await assert.rejects(planDawEdit({session:s,instruction:'Measure',allowAnalysis:true},reply([{...call,arguments:'{"commands":[]}'}])));
 await assert.rejects(planDawEdit({session:s,instruction:'Measure',allowAnalysis:true},reply([call,{type:'function_call',name:'edit_session',arguments:'{}'}])),/Unexpected/);
});
test('model edit plans can request post-edit verification with a boolean flag',async()=>{
 const {s}=fixture();let sent;const options=value=>({key:'test',model:'test',fetchImpl:async(_,request)=>{sent=JSON.parse(request.body);return {ok:true,json:async()=>({output:[{type:'function_call',name:'edit_session',arguments:JSON.stringify({summary:'Adjusted master gain; verification follows.',commands:[{op:'master.gain.offset',values:{deltaDb:-3}}],verifyMix:value})}]})};}});
 const plan=await planDawEdit({session:s,instruction:'Reduce and verify'},options(true));assert.equal(plan.verifyMix,true);assert.equal(plan.commands[0].values.deltaDb,-3);assert.equal(sent.tools.find(t=>t.name==='edit_session').parameters.properties.verifyMix.type,'boolean');await assert.rejects(planDawEdit({session:s,instruction:'Reduce and verify'},options('true')));
});
test('stereo metrics distinguish mono, opposite polarity, uncorrelated channels and silence',async()=>{
 const {stereoStatistics}=await import('../src/experimental/audio-statistics.js');
 const mono=stereoStatistics([[1,-1],[1,-1]]);assert.deepEqual(mono,{correlation:1,midRmsDb:0,sideRmsDb:null});const opposite=stereoStatistics([[1,-1],[-1,1]]);assert.deepEqual(opposite,{correlation:-1,midRmsDb:null,sideRmsDb:0});const unequal=stereoStatistics([[1,-1],[-.5,.5]]);assert.equal(unequal.correlation,-1);near(unequal.midRmsDb,20*Math.log10(.25));const orthogonal=stereoStatistics([[1,1],[1,-1]]);assert.equal(orthogonal.correlation,0);near(orthogonal.midRmsDb,10*Math.log10(.5));near(orthogonal.sideRmsDb,10*Math.log10(.5));assert.deepEqual(stereoStatistics([[0,0],[0,0]]),{correlation:null,midRmsDb:null,sideRmsDb:null});assert.equal(stereoStatistics([[1,1],[0,0]]).correlation,null);assert.throws(()=>stereoStatistics([[NaN],[0]]));assert.throws(()=>stereoStatistics([[1],[1,2]]));
});
test('stereo analysis validates power relationships and reaches agent context without requiring old clients to supply it',async()=>{
 const {stereoStatistics}=await import('../src/experimental/audio-statistics.js'),{s,a}=fixture(),channels=[new Float32Array(48000).fill(.5),new Float32Array(48000).fill(-.5)];const measured={...a,channels:audioStatistics(channels),stereo:stereoStatistics(channels)};assert.deepEqual(validateMixAnalysis(measured,s),measured);for(const stereo of [{...measured.stereo,correlation:1},{...measured.stereo,correlation:null},{...measured.stereo,sideRmsDb:0},{...measured.stereo,correlation:2}])assert.throws(()=>validateMixAnalysis({...measured,stereo},s));let sent;await planDawEdit({session:s,instruction:'Is this mono compatible?',mixAnalysis:measured},{key:'test',model:'test',fetchImpl:async(_,request)=>{sent=JSON.parse(request.body);return {ok:true,json:async()=>({output:[]})};}});assert.deepEqual(JSON.parse(sent.input.at(-1).content).mixAnalysis.stereo,measured.stereo);
});

test('stereo consistency tolerates roundoff when one nonzero channel is extremely quiet',async()=>{const {stereoStatistics}=await import('../src/experimental/audio-statistics.js'),{s,a}=fixture(),channels=[new Float32Array(48000).fill(.5),new Float32Array(48000).fill(1e-20)];assert.ok(validateMixAnalysis({...a,channels:audioStatistics(channels),stereo:stereoStatistics(channels)},s));});
test('loudness context validates block counts, gates and current revision',async()=>{
 const {s,a}=fixture(),loudness={integratedLufs:null,blocks:7,gatedBlocks:0};
 assert.deepEqual(validateMixAnalysis({...a,loudness},s).loudness,loudness);
 for(const change of [{blocks:8},{gatedBlocks:8},{integratedLufs:-20},{integratedLufs:-71,gatedBlocks:1}])assert.throws(()=>validateMixAnalysis({...a,loudness:{...loudness,...change}},s));
 let sent;await planDawEdit({session:s,instruction:'What is the loudness?',mixAnalysis:{...a,loudness}},{key:'test',model:'test',fetchImpl:async(_,request)=>{sent=JSON.parse(request.body);return {ok:true,json:async()=>({output:[]})};}});
 assert.deepEqual(JSON.parse(sent.input.at(-1).content).mixAnalysis.loudness,loudness);
});
test('true-peak context is optional, consistent with channel samples, and reaches the agent',async()=>{
 const {s,a}=fixture(),truePeak={oversample:4,peaksDbtp:[null,null]};assert.deepEqual(validateMixAnalysis({...a,truePeak},s).truePeak,truePeak);
 for(const t of [{...truePeak,oversample:8},{...truePeak,peaksDbtp:[0,null]},{...truePeak,peaksDbtp:[null]}])assert.throws(()=>validateMixAnalysis({...a,truePeak:t},s));
 const audible={...a,channels:a.channels.map(()=>({peakDb:-1,rmsDb:-6,peakFrame:0,overSamples:0})),truePeak:{oversample:4,peaksDbtp:[-.1,.2]}};assert.ok(validateMixAnalysis(audible,s));assert.throws(()=>validateMixAnalysis({...audible,truePeak:{oversample:4,peaksDbtp:[-2,0]}},s));
 let sent;await planDawEdit({session:s,instruction:'Are there inter-sample peaks?',mixAnalysis:audible},{key:'test',model:'test',fetchImpl:async(_,request)=>{sent=JSON.parse(request.body);return {ok:true,json:async()=>({output:[]})};}});assert.deepEqual(JSON.parse(sent.input.at(-1).content).mixAnalysis.truePeak,audible.truePeak);
});
test('loudness dynamics reject inconsistent duration and reach agent context',async()=>{
 const {s,a}=fixture(),dynamics={momentaryMaxLufs:null,shortTermMaxLufs:null,rangeLu:null},loudness={integratedLufs:null,blocks:7,gatedBlocks:0,dynamics};
 assert.ok(validateMixAnalysis({...a,loudness},s));
 for(const change of [{shortTermMaxLufs:-20},{rangeLu:2},{rangeLu:-1}])assert.throws(()=>validateMixAnalysis({...a,loudness:{...loudness,dynamics:{...dynamics,...change}}},s));
 let sent;await planDawEdit({session:s,instruction:'What is the loudness range?',mixAnalysis:{...a,loudness}},{key:'test',model:'test',fetchImpl:async(_,request)=>{sent=JSON.parse(request.body);return {ok:true,json:async()=>({output:[]})};}});assert.deepEqual(JSON.parse(sent.input.at(-1).content).mixAnalysis.loudness.dynamics,dynamics);
});
