import test from 'node:test';
import assert from 'node:assert/strict';
import JSZip from 'jszip';
import {newSession,applyCommands} from '../src/experimental/session.js';
import {exportArchive,importArchive} from '../src/experimental/archive.js';
const fixture=()=>applyCommands(newSession(),[{op:'track.add',values:{id:'t'}},{op:'region.add',target:'t',values:{assetId:'source',duration:2}},{op:'region.add',target:'t',values:{assetId:'source',start:3,duration:2}},{op:'effect.add',target:'t',values:{kind:'delay'}}]);
test('portable archive preserves media bytes, shared references, edits and effects with isolated IDs',async()=>{const session=fixture(),file=new File([new Uint8Array([0,255,1,127])],'original.wav',{type:'audio/wav',lastModified:123});const blob=await exportArchive(session,new Map([['source',file]])),restored=await importArchive(await blob.arrayBuffer());assert.equal(restored.records.length,1);assert.deepEqual(new Uint8Array(await restored.records[0].file.arrayBuffer()),new Uint8Array(await file.arrayBuffer()));assert.equal(restored.records[0].file.name,file.name);assert.equal(restored.records[0].file.lastModified,123);assert.notEqual(restored.session.id,session.id);assert.notEqual(restored.records[0].id,'source');assert.ok(restored.session.tracks[0].regions.every(r=>r.assetId===restored.records[0].id));assert.deepEqual(restored.session.tracks[0].effects,session.tracks[0].effects);assert.equal(restored.session.tracks[0].regions[1].start,3);});
test('archive refuses missing media and invalid region invariants',async()=>{await assert.rejects(exportArchive(fixture(),new Map()),/missing/);const s=fixture();s.tracks[0].regions[0].fadeIn=10;await assert.rejects(exportArchive(s,new Map()),/Fades/);});
test('archive rejects missing entries and duplicate manifest identities',async()=>{const blob=await exportArchive(fixture(),new Map([['source',new File(['audio'],'a.wav')]]));const zip=await JSZip.loadAsync(await blob.arrayBuffer());zip.remove('media/0');await assert.rejects(importArchive(await zip.generateAsync({type:'uint8array'})),/missing/);const manifest=JSON.parse(await zip.file('project.json').async('string'));manifest.assets.push(manifest.assets[0]);zip.file('project.json',JSON.stringify(manifest));await assert.rejects(importArchive(await zip.generateAsync({type:'uint8array'})),/manifest/);});
test('archives carry takes and selection, rebind source fingerprints and preserve incompatible recordings',async()=>{
 const {sceneSourceSignature}=await import('../src/experimental/scene-source.js'),{availableScenePerformance}=await import('../src/experimental/scene-performance.js');let session=fixture();session=applyCommands(session,[{op:'scene.add',values:{id:'scene',name:'Verse',regionIds:session.tracks[0].regions[0].id}}]);
 const performance={sessionId:session.id,revision:session.revision,events:[{sceneId:'scene',trackId:'t',sourceSignature:sceneSourceSignature(session,'scene','t'),start:0,duration:1}]},take={id:'take',name:'Favorite',createdAt:'2026-09-23T00:00:00.000Z',placements:1,performance},stale=structuredClone(take);stale.id='stale';stale.name='Legacy stale';delete stale.performance.events[0].sourceSignature;stale.performance.revision--;
 const bundle={selectedId:'take',takes:[take,stale]},before=JSON.stringify(bundle),blob=await exportArchive(session,new Map([['source',new File(['audio'],'a.wav')]]),bundle),restored=await importArchive(await blob.arrayBuffer());assert.equal(JSON.stringify(bundle),before);assert.equal(restored.sceneTakes.takes.length,2);const imported=restored.sceneTakes.takes[0];assert.notEqual(imported.id,'take');assert.equal(imported.id,restored.sceneTakes.selectedId);assert.equal(imported.name,'Favorite');assert.equal(imported.createdAt,take.createdAt);assert.equal(imported.performance.sessionId,restored.session.id);assert.notEqual(imported.performance.events[0].sourceSignature,performance.events[0].sourceSignature);assert.ok(availableScenePerformance(restored.session,imported.performance));assert.equal(availableScenePerformance(restored.session,restored.sceneTakes.takes[1].performance),undefined);
 const second=await importArchive(await blob.arrayBuffer());assert.notEqual(second.sceneTakes.takes[0].id,imported.id);assert.notEqual(second.session.id,restored.session.id);
});
test('older archives remain readable and foreign or malformed take bundles are rejected',async()=>{
 const session=fixture(),files=new Map([['source',new File(['audio'],'a.wav')]]),blob=await exportArchive(session,files),zip=await JSZip.loadAsync(await blob.arrayBuffer()),manifest=JSON.parse(await zip.file('project.json').async('string'));delete manifest.sceneTakes;zip.file('project.json',JSON.stringify(manifest));assert.deepEqual((await importArchive(await zip.generateAsync({type:'uint8array'}))).sceneTakes,{selectedId:null,takes:[]});manifest.sceneTakes={selectedId:'missing',takes:[]};zip.file('project.json',JSON.stringify(manifest));await assert.rejects(importArchive(await zip.generateAsync({type:'uint8array'})),/selection/);
 await assert.rejects(exportArchive(session,files,{selectedId:null,takes:[{id:'foreign',name:'Foreign',createdAt:'2026-09-23T00:00:00.000Z',placements:0,performance:{sessionId:'other',revision:0,events:[{sceneId:'s',start:0,duration:1}]}}]}),/project/);
});
