import test from 'node:test';import assert from 'node:assert/strict';
import {SessionHistory} from '../src/experimental/session.js';
const setup=()=>{const h=new SessionHistory();h.execute([{op:'track.add',values:{id:'a',kind:'audio'}},{op:'track.add',values:{id:'m',kind:'midi'}},{op:'region.add',target:'a',values:{id:'ar',start:0,offset:3,duration:2}},{op:'region.set',target:'ar',values:{reverse:true}},{op:'region.add',target:'m',values:{id:'mr',start:4,duration:2}},{op:'note.add',target:'mr',values:{id:'n',pitch:60,start:.5,duration:1.5}},{op:'scene.add',values:{id:'s',name:'Verse',regionIds:'ar,mr'}},{op:'scene.cell.set',target:'s',values:{regionId:'mr',loop:false}}]);return h;};
test('placing scenes repeats audio, keeps one-shots, preserves originals and undoes in one step',()=>{const h=setup(),before=structuredClone(h.session);h.execute([{op:'scene.place',target:'s',values:{position:10,duration:5}}]);const audio=h.session.tracks[0].regions;assert.deepEqual(audio.slice(1).map(r=>[r.start,r.duration,r.offset]),[[10,2,3],[12,2,3],[14,1,4]]);assert.ok(audio.every(r=>r.reverse));assert.equal(h.session.tracks[1].regions.length,2);assert.equal(h.session.tracks[1].regions[1].start,10);assert.deepEqual(audio[0],before.tracks[0].regions[0]);assert.deepEqual(h.session.scenes,before.scenes);const ids=h.session.tracks.flatMap(t=>t.regions.flatMap(r=>[r.id,...r.notes.map(n=>n.id),...r.events.map(e=>e.id)]));assert.equal(new Set(ids).size,ids.length);const placed=structuredClone(h.session);h.undo();assert.deepEqual(h.session.tracks,before.tracks);h.redo();assert.deepEqual(h.session.tracks,placed.tracks);assert.deepEqual(new SessionHistory(JSON.parse(JSON.stringify(h.session))).session,h.session);});
test('partial MIDI copies trim notes, keep source data and exclude out-of-range notes',()=>{const h=setup();h.execute([{op:'scene.place',target:'s',values:{position:20,duration:1}}]);const region=h.session.tracks[1].regions[1];assert.equal(region.duration,1);assert.deepEqual(region.notes.map(n=>[n.start,n.duration]),[[.5,.5]]);assert.equal(h.session.tracks[1].regions[0].notes[0].duration,1.5);});
test('overlap rejects atomically by default and explicit layering preserves both regions',()=>{const h=setup(),before=structuredClone(h.session);assert.throws(()=>h.execute([{op:'scene.place',target:'s',values:{position:0,duration:3}}]),/overlaps/);assert.deepEqual(h.session,before);h.execute([{op:'scene.place',target:'s',values:{position:0,duration:3,overlap:'allow'}}]);assert.equal(h.session.tracks[0].regions.length,3);assert.deepEqual(h.session.tracks[0].regions[0],before.tracks[0].regions[0]);});
test('muted scene cells are copied and protected destinations, missing scenes, empty scenes and timeline overflow reject',()=>{const h=setup();h.execute([{op:'region.set',target:'ar',values:{mute:true}}]);h.execute([{op:'scene.place',target:'s',values:{position:20,duration:2}}]);assert.equal(h.session.tracks[0].regions[1].mute,true);h.execute([{op:'track.set',target:'m',values:{protected:true}}]);const before=structuredClone(h.session);assert.throws(()=>h.execute([{op:'scene.place',target:'s',values:{position:30,duration:2}}]),/Unprotect/);assert.deepEqual(h.session,before);assert.throws(()=>h.execute([{op:'scene.place',target:'s',values:{position:86400,duration:2}}]),/timeline/);assert.throws(()=>h.execute([{op:'scene.place',target:'no',values:{position:30,duration:2}}]),/not found/);h.execute([{op:'scene.add',values:{id:'empty',name:'Empty'}}]);assert.throws(()=>h.execute([{op:'scene.place',target:'empty',values:{position:30,duration:2}}]),/Assign clips/);});
test('scene placement enforces track limits before allocating and all work remains atomic',()=>{const h=setup();h.execute([{op:'region.set',target:'ar',values:{duration:.1}}]);const before=structuredClone(h.session);assert.throws(()=>h.execute([{op:'scene.place',target:'s',values:{position:20,duration:600}}]),/1,000-region/);assert.deepEqual(h.session,before);});
test('agent can place a saved scene through the same editing command',async()=>{const {planDawEdit}=await import('../server/daw-agent.js'),h=setup(),commands=[{op:'scene.place',target:'s',values:{position:20,duration:4}}],before=structuredClone(h.session);const plan=await planDawEdit({session:h.session,instruction:'Put Verse at 20 seconds for four seconds'},{key:'test',model:'test',fetchImpl:async()=>({ok:true,json:async()=>({output:[{type:'function_call',name:'edit_session',arguments:JSON.stringify({commands,summary:'Placed Verse'})}]})})});assert.deepEqual(h.session,before);h.execute(plan.commands,plan.revision);assert.equal(h.session.tracks[0].regions.length,3);assert.equal(h.session.tracks[1].regions.length,2);});
