import test from 'node:test';import assert from 'node:assert/strict';import {SessionHistory} from '../src/experimental/session.js';
const setup=()=>{const h=new SessionHistory();h.execute([{op:'track.add',values:{id:'a',kind:'midi'}},{op:'track.add',values:{id:'b',kind:'audio'}},{op:'region.add',target:'a',values:{id:'r1',start:1,duration:3}},{op:'region.add',target:'b',values:{id:'r2',start:7,duration:5}},{op:'note.add',target:'r1',values:{id:'n',pitch:60,start:1,duration:1}}]);return h;};
const align=(h,values)=>h.execute([{op:'regions.align',values:{regionIds:'r1,r2',position:10,...values}}]);
test('align starts and ends across tracks preserve region contents, undo, and redo',()=>{const h=setup(),before=structuredClone(h.session);align(h,{});for(let i=0;i<2;i++)assert.deepEqual(h.session.tracks[i].regions[0],{...before.tracks[i].regions[0],start:10});h.undo();assert.deepEqual(h.session.tracks,before.tracks);h.redo();align(h,{edge:'end'});assert.deepEqual(h.session.tracks.map(t=>t.regions[0].start),[7,5]);});
test('invalid alignment, unknown/duplicate regions, and protected tracks reject atomically',()=>{const h=setup();for(const values of [{edge:'end',position:2},{position:-1},{edge:'center'},{regionIds:'r1,missing'},{regionIds:'r1,r1'},{extra:1}]){const before=structuredClone(h.session);assert.throws(()=>align(h,values));assert.deepEqual(h.session,before);}h.execute([{op:'track.set',target:'b',values:{protected:true}}]);const before=structuredClone(h.session);assert.throws(()=>align(h,{}),/Unprotect/);assert.deepEqual(h.session,before);});
test('agent validates the shared alignment operation without mutating the supplied session',async()=>{
 const {planDawEdit}=await import('../server/daw-agent.js');const h=setup(),before=structuredClone(h.session);const commands=[{op:'regions.align',values:{regionIds:'r1,r2',position:12,edge:'end'}}];
 const plan=await planDawEdit({session:h.session,instruction:'Align both selected region ends at 12 seconds',selectedRegionIds:['r1','r2']},{provider:'openai',key:'test',model:'test',fetchImpl:async()=>({ok:true,json:async()=>({output:[{type:'function_call',name:'edit_session',arguments:JSON.stringify({summary:'Align ends',commands})}]})})});
 assert.deepEqual(h.session,before);h.execute(plan.commands,plan.revision);assert.deepEqual(h.session.tracks.map(t=>t.regions[0].start),[9,7]);
});
