import test from 'node:test';import assert from 'node:assert/strict';
import {SessionHistory} from '../src/experimental/session.js';
import {zoneZeroPlan} from '../src/experimental/sampler-zone-zero-action.js';
import {planDawEdit} from '../server/daw-agent.js';
const setup=()=>{const h=new SessionHistory();h.execute([{op:'track.add',values:{id:'t',kind:'midi'}},{op:'samplerZone.set',target:'t',values:{id:'z',name:'Zone',assetId:'source',sourceStart:.02,sourceEnd:.08,loopStart:.032,loopEnd:.068}}]);return h;};
const options={trackId:'t',zoneId:'z',mode:'loop',edge:'both'},pcm=Float32Array.from({length:100},(_,i)=>i<30?-.5:i<70?.5:-.5),buffer={sampleRate:1000,length:100,duration:.1,numberOfChannels:1,getChannelData:()=>pcm};
test('agent loop snapping builds one validated undoable edit with original source preserved',()=>{const h=setup(),before=structuredClone(h.session),p=zoneZeroPlan(h.session,options,buffer);assert.deepEqual(h.session,before);h.execute(p.commands);const z=h.session.tracks[0].sampleZones[0];assert.equal(z.loop,true);assert.equal(z.loopStart,.03);assert.equal(z.loopEnd,.07);assert.equal(z.sourceStart,.02);assert.equal(z.sourceEnd,.08);h.undo();assert.deepEqual(h.session.tracks[0].sampleZones,before.tracks[0].sampleZones);});
test('failed searches and sample trims that exclude enabled loops are atomic',()=>{const h=setup(),before=structuredClone(h.session);assert.throws(()=>zoneZeroPlan(h.session,{...options,mode:'sample'},buffer));assert.deepEqual(h.session,before);h.execute([{op:'samplerZone.set',target:'t',values:{...h.session.tracks[0].sampleZones[0],id:'z',sourceStart:.028,loop:true,loopStart:.028,loopEnd:.068}}]);assert.throws(()=>zoneZeroPlan(h.session,{...options,mode:'sample',edge:'start'},buffer));});
test('agent zero-crossing tool checks capabilities, continuation, schema and observed zone IDs',async()=>{const h=setup(),call=(extra={},args=options)=>planDawEdit({session:h.session,instruction:'Snap loop boundaries to zero crossings',allowZoneZero:true,...extra},{key:'test',model:'test',fetchImpl:async(_,r)=>{const body=JSON.parse(r.body);assert.equal(body.tools.some(t=>t.name==='snap_sampler_zone_to_zero_crossings'),extra.allowZoneZero!==false&&!extra.editingContinuation);return {ok:true,json:async()=>({output:[{type:'function_call',name:'snap_sampler_zone_to_zero_crossings',arguments:JSON.stringify(args)}]})};}});const result=await call();assert.equal(result.action,'snap_sampler_zone_to_zero_crossings');assert.deepEqual(result.commands,[]);assert.deepEqual(result.options,options);await assert.rejects(call({allowZoneZero:false}));await assert.rejects(call({editingContinuation:true}));await assert.rejects(call({},{...options,zoneId:'fake'}));await assert.rejects(call({},{...options,edge:'bad'}));});
