import test from 'node:test';import assert from 'node:assert/strict';import {SessionHistory} from '../src/experimental/session.js';import {sampleForNote} from '../src/experimental/sampler-articulations.js';import {referencedAssets,audibleAssets,remapAssets} from '../src/experimental/media-refs.js';import {validateTrackSources} from '../src/experimental/audio-voices.js';import {exportArchive,importArchive} from '../src/experimental/archive.js';import {planDawEdit} from '../server/daw-agent.js';
const setup=()=>{const h=new SessionHistory();h.execute([{op:'track.add',values:{id:'t',kind:'midi',instrument:'sampler',sampleAssetId:'base'}},{op:'region.add',target:'t',values:{id:'r',duration:2}},{op:'note.add',target:'r',values:{id:'a',pitch:60,duration:.5}},{op:'note.add',target:'r',values:{id:'b',pitch:60,start:1,duration:.5}},{op:'midiSwitch.save',target:'t',values:{id:'p',name:'Plucked',type:'keyswitch',channel:0,parameter:24,value:100}},{op:'notes.articulation',target:'r',values:{id:'p',noteIds:'b'}}]);return h;};
test('sampler articulation selects its own source, root and loop while preserving shared envelope and fallback',()=>{
 const h=setup(),before=structuredClone(h.session);h.execute([{op:'samplerArticulation.set',target:'t',values:{id:'p',assetId:'pluck',root:48,loop:true,loopStart:.1,loopEnd:.5}}]);const t=h.session.tracks[0],[a,b]=t.regions[0].notes;assert.equal(sampleForNote(t,a).sampleAssetId,'base');const mapped=sampleForNote(t,b);assert.equal(mapped.sampleAssetId,'pluck');assert.equal(mapped.sampleRoot,48);assert.equal(mapped.sampleLoopEnd,.5);assert.equal(mapped.sampleAttack,t.sampleAttack);assert.deepEqual(t.regions,before.tracks[0].regions);assert.deepEqual(new Set(audibleAssets(h.session)),new Set(['base','pluck']));assert.deepEqual(new Set(referencedAssets(h.session)),new Set(['base','pluck']));h.undo();assert.equal(h.session.tracks[0].sampleArticulations,undefined);h.redo();h.execute([{op:'midiSwitch.delete',target:'t',values:{id:'p'}}]);assert.equal(sampleForNote(h.session.tracks[0],b).sampleAssetId,'pluck');
});
test('source validation checks only required sample mappings and validates their loop bounds',()=>{
 const h=setup();h.execute([{op:'samplerArticulation.set',target:'t',values:{id:'p',assetId:'pluck',loop:true,loopEnd:2}},{op:'note.delete',target:'a'}]);const t=h.session.tracks[0];assert.deepEqual(audibleAssets(h.session),['pluck']);assert.throws(()=>validateTrackSources(t,new Map()),/Missing sampler/);assert.throws(()=>validateTrackSources(t,new Map([['pluck',{duration:1,sampleRate:48000}]])),/loop/);validateTrackSources(t,new Map([['pluck',{duration:3,sampleRate:48000}]]));
 for(const values of [{id:'missing',assetId:'pluck'},{id:'p',assetId:'pluck',root:128},{id:'p',assetId:'pluck',loop:true,loopStart:2,loopEnd:1}])assert.throws(()=>h.execute([{op:'samplerArticulation.set',target:'t',values}]));
});
test('project media remapping and portable archives retain articulation sources',async()=>{
 const h=setup();h.execute([{op:'samplerArticulation.set',target:'t',values:{id:'p',assetId:'pluck'}}]);const files=new Map(['base','pluck'].map(id=>[id,new File([id],id+'.wav',{type:'audio/wav'})]));const result=await importArchive(await (await exportArchive(h.session,files)).arrayBuffer());assert.equal(result.records.length,2);const mapped=result.session.tracks[0].sampleArticulations[0].assetId;assert.notEqual(mapped,'pluck');assert.equal(result.records.find(r=>r.id===mapped).file.name,'pluck.wav');const copy=structuredClone(h.session);remapAssets(copy,new Map([['base','base-new'],['pluck','pluck-new']]));assert.equal(copy.tracks[0].sampleArticulations[0].assetId,'pluck-new');
});
test('agent maps a supplied sample through validated commands and instrument copy clears stale mappings',async()=>{
 const h=setup(),commands=[{op:'samplerArticulation.set',target:'t',values:{id:'p',assetId:'pluck',root:60}}];const result=await planDawEdit({session:h.session,instruction:'Use supplied sample pluck for my Plucked articulation, root 60'},{key:'test',model:'test',fetchImpl:async()=>({ok:true,json:async()=>({output:[{type:'function_call',name:'edit_session',arguments:JSON.stringify({summary:'Mapped sample',commands})}]})})});h.execute(result.commands,result.revision);h.execute([{op:'track.add',values:{id:'other',kind:'midi'}},{op:'track.copySettings',target:'t',values:{sourceId:'other',instrument:true}}]);assert.equal(h.session.tracks[0].sampleArticulations,undefined);
});
