import test from 'node:test';import assert from 'node:assert/strict';
import {SessionHistory} from '../src/experimental/session.js';import {midiOutputPlan} from '../src/experimental/midi-output-plan.js';import {createMidiOutput} from '../src/experimental/midi-output.js';
const setup=()=>{const h=new SessionHistory();h.execute([{op:'track.add',values:{id:'t',kind:'midi'}},{op:'region.add',target:'t',values:{id:'r',duration:2}},{op:'note.add',target:'r',values:{id:'n',pitch:60,start:0,duration:.5,velocity:.8,channel:2}},{op:'event.add',target:'r',values:{type:'controlChange',parameter:64,value:127,start:.1,channel:2}},{op:'event.add',target:'r',values:{type:'controlChange',parameter:64,value:0,start:1,channel:2}}]);return h;};
test('MIDI hardware plan chases controllers and sustained notes, then releases at region end',()=>{const h=setup(),before=JSON.stringify(h.session),plan=midiOutputPlan(h.session,'t',.75),on=plan.messages.find(m=>m.bytes[0]===0x92),off=plan.messages.find(m=>m.bytes[0]===0x82);assert.equal(on.time,.75);assert.equal(off.time,.75);assert.ok(plan.messages.indexOf(on)<plan.messages.indexOf(off));assert.ok(plan.messages.some(m=>m.time===.75&&m.bytes.join()===`${0xb2},64,127`));assert.ok(plan.messages.some(m=>m.time===1&&m.bytes.join()===`${0xb2},64,0`));assert.equal(plan.end,2);assert.equal(JSON.stringify(h.session),before);});
test('hardware plan rejects overlapping channel regions and ignores muted notes',()=>{const h=setup();h.execute([{op:'note.set',target:'n',values:{mute:true}}]);assert.equal(midiOutputPlan(h.session,'t').messages.some(m=>(m.bytes[0]&240)===144),false);h.execute([{op:'region.duplicate',target:'r',values:{start:1}}]);assert.throws(()=>midiOutputPlan(h.session,'t'),/share a MIDI channel/);});
const fixture=()=>{let now=0,tick,changed=0,stateChange;const sent=[],port={id:'out',name:'Synth',state:'connected',open:async()=>{},close:async()=>{},clear(){sent.push(['clear']);},send(data,at){sent.push([data,at]);}},access={outputs:new Map([['out',port]]),addEventListener(type,fn){stateChange=fn;},removeEventListener(){stateChange=null;}},h=setup(),output=createMidiOutput({session:()=>h.session,position:()=>0,beforePlay(){},onChange(){changed++;},clock:()=>now,requestAccess:async()=>access,schedule:fn=>{tick=fn;return 1;},unschedule(){tick=null;}});output.view(x=>x);return {output,port,sent,h,disconnect(){port.state='disconnected';stateChange?.();},setNow:v=>now=v,tick:()=>tick?.(),changed:()=>changed};};
test('timestamped output uses a bounded lookahead and stop clears queued data and releases touched channels',async()=>{const f=fixture();await f.output.connect();await f.output.play();assert.equal(f.output.playing,true);assert.ok(f.sent.some(([bytes,at])=>Array.isArray(bytes)&&bytes[0]===0x92&&at===50));assert.ok(f.sent.every(([bytes,at])=>!Array.isArray(bytes)||at<=100));f.setNow(100);f.tick();f.output.stop();assert.equal(f.output.playing,false);const clear=f.sent.findIndex(e=>e[0]==='clear');assert.ok(clear>=0);assert.deepEqual(f.sent.slice(clear+1).map(e=>e[0]),[[0xb2,64,0],[0xb2,123,0],[0xb2,120,0]]);const count=f.sent.length;f.tick();assert.equal(f.sent.length,count);});
test('late opens and scheduling interruptions never leave hardware playback running',async()=>{const f=fixture();await f.output.connect();let finish;f.port.open=()=>new Promise(resolve=>finish=resolve);const pending=f.output.play();f.output.stop();finish();await pending;assert.equal(f.output.active,false);assert.equal(f.sent.length,0);f.port.open=async()=>{};await f.output.play();f.setNow(1000);f.tick();assert.equal(f.output.active,false);assert.ok(f.sent.some(e=>e[0]==='clear'));});

test('disconnect and failed port opens restore controls without leaving queued notes',async()=>{const f=fixture();await f.output.connect();await f.output.play();f.disconnect();assert.equal(f.output.active,false);assert.ok(f.sent.some(e=>e[0]==='clear'));assert.match(f.output.view(x=>x),/disconnected/);const g=fixture();await g.output.connect();g.port.open=async()=>{throw Error('Port unavailable');};const before=g.changed();await g.output.play();assert.equal(g.output.active,false);assert.ok(g.changed()>before);assert.match(g.output.view(x=>x),/Port unavailable/);});

test('panic releases every pitch and hold pedal on all channels while stopped without editing the session',async()=>{const f=fixture(),before=JSON.stringify(f.h.session);await f.output.connect();await f.output.panic();assert.equal(f.output.active,false);assert.equal(f.sent[0][0],'clear');const notes=f.sent.filter(([b])=>Array.isArray(b)&&(b[0]&240)===128);assert.equal(notes.length,2048);assert.equal(new Set(notes.map(([b])=>b.join())).size,2048);for(let channel=0;channel<16;channel++)for(const cc of [64,66,69,123,120])assert.ok(f.sent.some(([b])=>Array.isArray(b)&&b.join()===[0xb0|channel,cc,0].join()));assert.equal(JSON.stringify(f.h.session),before);assert.match(f.output.view(x=>x),/All notes released/);f.output.dispose();});
test('panic cancels scheduled playback and a canceled pending panic cannot send notes',async()=>{const f=fixture();await f.output.connect();await f.output.play();await f.output.panic();assert.equal(f.output.playing,false);const count=f.sent.length;f.tick();assert.equal(f.sent.length,count);const g=fixture();await g.output.connect();let finish;g.port.open=()=>new Promise(resolve=>finish=resolve);const pending=g.output.panic();g.output.stop();finish();await pending;assert.equal(g.sent.length,0);assert.equal(g.output.active,false);});
test('panic failure restores controls and synchronous close errors cannot strand playback',async()=>{const f=fixture();await f.output.connect();f.port.open=async()=>{throw Error('Disconnected');};await f.output.panic();assert.equal(f.output.active,false);assert.match(f.output.view(x=>x),/Could not silence/);f.port.open=async()=>{};await f.output.play();f.port.close=()=>{throw Error('Closed');};assert.doesNotThrow(()=>f.output.stop());assert.equal(f.output.active,false);});

const arrangementSetup=()=>{const h=setup();h.execute([{op:'track.add',values:{id:'t2',kind:'midi',name:'Bass'}},{op:'region.add',target:'t2',values:{id:'r2',duration:3}},{op:'note.add',target:'r2',values:{id:'n2',pitch:40,start:0,duration:2,velocity:.7,channel:4}},{op:'event.add',target:'r2',values:{type:'programChange',parameter:0,value:32,start:0,channel:4}}]);return h;};
test('hardware arrangement combines tracks on one clock and chases each channel independently',()=>{const h=arrangementSetup(),before=JSON.stringify(h.session),plan=midiOutputPlan(h.session,null,.75,{arrangement:true});assert.equal(plan.trackId,null);assert.deepEqual(plan.trackIds,['t','t2']);assert.equal(plan.end,3);const on=plan.messages.filter(m=>(m.bytes[0]&240)===144);assert.deepEqual(on.map(m=>[m.time,m.bytes[0]&15,m.bytes[1]]),[[.75,2,60],[.75,4,40]]);assert.ok(plan.messages.some(m=>m.time===.75&&m.bytes.join()===[0xc4,32].join()));assert.equal(JSON.stringify(h.session),before);});
test('hardware arrangement honors mute and solo, including solo buses, and rejects shared channels before output',()=>{const h=arrangementSetup();h.execute([{op:'note.set',target:'n2',values:{channel:2}}]);assert.throws(()=>midiOutputPlan(h.session,null,0,{arrangement:true}),/share a MIDI channel \(3\)/);h.execute([{op:'track.set',target:'t2',values:{mute:true}}]);assert.deepEqual(midiOutputPlan(h.session,null,0,{arrangement:true}).trackIds,['t']);h.execute([{op:'track.set',target:'t2',values:{mute:false,solo:true}}]);assert.deepEqual(midiOutputPlan(h.session,null,0,{arrangement:true}).trackIds,['t2']);h.execute([{op:'track.set',target:'t2',values:{solo:false}},{op:'track.add',values:{id:'bus',kind:'bus'}},{op:'track.set',target:'bus',values:{solo:true}},{op:'track.set',target:'t',values:{output:'bus'}}]);assert.deepEqual(midiOutputPlan(h.session,null,0,{arrangement:true}).trackIds,['t']);});
test('sequential tracks may reuse a channel and old note releases precede new note starts',()=>{const h=arrangementSetup();h.execute([{op:'event.delete',target:h.session.tracks[1].regions[0].events[0].id},{op:'note.set',target:'n2',values:{channel:2}},{op:'region.set',target:'r2',values:{start:2}}]);const plan=midiOutputPlan(h.session,null,0,{arrangement:true}),boundary=plan.messages.filter(m=>m.time===2);assert.ok(boundary.findIndex(m=>m.bytes.join()===[0xb2,123,0].join())<boundary.findIndex(m=>m.bytes[0]===0x92));});
