import test from 'node:test';import assert from 'node:assert/strict';
import {musicalNotePlacement} from '../src/experimental/piano-grid.js';
import {pianoView} from '../src/experimental/piano.js';
import {defaultNoteTools} from '../src/experimental/note-transform-controls.js';
const session={tempo:120,tempoChanges:[{beat:8,bpm:60}]},region={id:'r',name:'Piano',start:3,duration:5,notes:[{id:'n',start:.5,duration:1.5,pitch:60,velocity:.8}],events:[]};
test('drawn notes snap and size in local beats across tempo changes',()=>{assert.deepEqual(musicalNotePlacement(1.4,region,session,.25),{start:1.25,duration:.25});assert.deepEqual(musicalNotePlacement(.9,region,session,1),{start:.5,duration:.5});const free=musicalNotePlacement(.9,region,session,0);assert.ok(Math.abs(free.start-.9)<1e-9);assert.ok(Math.abs(free.duration-.15)<1e-9);assert.equal(musicalNotePlacement(6,region,session,.25),null);assert.deepEqual(musicalNotePlacement(4.9,region,session,0),{start:4.9,duration:5-4.9});});
test('piano note fields and velocity labels display beat duration at note onset',()=>{const s={...session,tracks:[{kind:'midi',regions:[region]}]},html=pianoView(region,120,'n',s=>s,{...defaultNoteTools,selectedIds:['n']},s);assert.match(html,/name="start"[^>]*value="1"/);assert.match(html,/name="duration"[^>]*value="2"/);assert.match(html,/Velocity for MIDI note 60 at beat 1.00/);});

import {musicalPianoGrid,applyPianoGrid} from '../src/experimental/piano-grid.js';
test('musical grid lines follow variable beat spacing and remain bounded for long regions',()=>{assert.deepEqual(musicalPianoGrid(region,session,1),[0,.5,1,2,3,4,5]);assert.deepEqual(musicalPianoGrid(region,session,0),[]);const long=musicalPianoGrid({...region,duration:86400},session,.125);assert.ok(long.length<=1000);assert.ok(long.every((time,i)=>!i||time>long[i-1]));const offset=musicalPianoGrid({...region,start:3.25},session,1);assert.deepEqual(offset.slice(0,4),[0,.5,1.25,2.25]);assert.throws(()=>musicalPianoGrid(region,session,-1));});
test('switching grid modes clears mapped styling and snap off hides lines',()=>{const props=new Map(),root={querySelector:()=>({style:{setProperty:(k,v)=>props.set(k,v),removeProperty:k=>props.delete(k)}})};applyPianoGrid(root,.5,1,region,session);assert.match(props.get('--piano-grid-image'),/transparent 108px/);applyPianoGrid(root,.5,0,region,session);assert.equal(props.get('--piano-grid-image'),'none');applyPianoGrid(root,.5,.25,region,{tempo:120});assert.equal(props.has('--piano-grid-image'),false);assert.equal(props.get('--piano-snap-width'),'10px');});
