import test from 'node:test';import assert from 'node:assert/strict';import {draggedZoneTrim} from '../src/experimental/sampler-zone-waveform.js';
const buffer={length:48000,sampleRate:48000,duration:1},range={start:.2,end:.8};
test('zone waveform draws in either direction and snaps to source sample boundaries',()=>{assert.deepEqual(draggedZoneTrim(range,'draw',.8,.2,buffer),range);assert.deepEqual(draggedZoneTrim(range,'draw',-1,2,buffer),{start:0,end:1});const result=draggedZoneTrim(range,'draw',.123456,.765432,buffer);assert.equal(result.start*48000,Math.round(.123456*48000));assert.equal(result.end*48000,Math.round(.765432*48000));});
test('zone waveform edges stay ordered and retain at least one source sample',()=>{assert.deepEqual(draggedZoneTrim(range,'start',.2,.9,buffer),{start:.8-1/48000,end:.8});assert.deepEqual(draggedZoneTrim(range,'end',.8,.1,buffer),{start:.2,end:.2+1/48000});assert.deepEqual(draggedZoneTrim(range,'draw',1,1,buffer),{start:1-1/48000,end:1});assert.deepEqual(draggedZoneTrim(range,'start',.2,-1,buffer),{start:0,end:.8});assert.deepEqual(draggedZoneTrim(range,'end',.8,2,buffer),{start:.2,end:1});});
test('invalid waveform operations do not produce nonfinite form values',()=>{assert.throws(()=>draggedZoneTrim(range,'draw',0,NaN,buffer));assert.throws(()=>draggedZoneTrim(range,'unknown',0,.5,buffer));});

import {zoneLoopBounds,draggedZoneLoop} from '../src/experimental/sampler-zone-waveform.js';
test('graphical loops are constrained to the selected sample, including backwards drawing and extreme handles',()=>{const source={start:.2,end:.8},loop={start:.3,end:.7};assert.deepEqual(draggedZoneLoop(loop,'draw',1,0,buffer,source),source);assert.deepEqual(draggedZoneLoop(loop,'start',.3,-1,buffer,source),{start:.2,end:.7});assert.deepEqual(draggedZoneLoop(loop,'end',.7,2,buffer,source),{start:.3,end:.8});assert.deepEqual(draggedZoneLoop(loop,'draw',0,0,buffer,source),{start:.2,end:.2+1/48000});assert.deepEqual(draggedZoneLoop(loop,'draw',1,1,buffer,source),{start:.8-1/48000,end:.8});});
test('loop bounds align inward and reject absent source selections',()=>{const bounds=zoneLoopBounds({start:.200001,end:.800001},buffer);assert.ok(bounds.start>=.200001);assert.ok(bounds.end<=.800001);assert.ok(Math.abs(bounds.start*48000-Math.round(bounds.start*48000))<1e-8);for(const source of [{start:NaN,end:1},{start:-1,end:.5},{start:0,end:2},{start:.4,end:.3},{start:.2,end:.2}])assert.throws(()=>zoneLoopBounds(source,buffer));});
