import test from 'node:test';
import assert from 'node:assert/strict';
import {SessionHistory} from '../src/experimental/session.js';
import {audioStretchPlan} from '../src/experimental/audio-stretch-region.js';
const setup=()=>{const h=new SessionHistory();h.execute([{op:'track.add',values:{id:'audio',kind:'audio'}},{op:'region.add',target:'audio',values:{id:'clip',assetId:'original',start:3,offset:2,duration:4}},{op:'region.set',target:'clip',values:{fadeIn:.2,fadeOut:.4,reverse:true,gainDb:-3}},{op:'effect.add',target:'audio',values:{kind:'gain',gainDb:2}}]);return h;};
const command=(values={})=>({op:'region.commitStretch',target:'clip',values:{ratio:1.5,assetId:'rendered',sampleRate:48000,channels:1,frames:288000,...values}});
test('stretch commit preserves original, editable effects and scaled fades with undo/redo',()=>{const h=setup(),before=structuredClone(h.session);h.execute([command()]);const [original,copy]=h.session.tracks,r=copy.regions[0];assert.equal(original.regions[0].mute,true);assert.equal(original.regions[0].assetId,'original');assert.equal(r.duration,6);assert.equal(r.start,3);assert.equal(r.offset,0);assert.equal(r.reverse,false);assert.equal(r.assetId,'rendered');assert.equal(r.gainDb,-3);assert.ok(Math.abs(r.fadeIn-.3)<1e-9);assert.ok(Math.abs(r.fadeOut-.6)<1e-9);assert.equal(copy.effects[0].gainDb,2);assert.notEqual(copy.effects[0].id,original.effects[0].id);h.undo();assert.deepEqual(h.session.tracks,before.tracks);h.redo();assert.equal(h.session.tracks.length,2);});
test('invalid stretch assets, lengths and limits reject atomically',()=>{const h=setup(),before=structuredClone(h.session);for(const values of [{frames:1},{assetId:'original'},{ratio:3},{channels:3},{sampleRate:1}])assert.throws(()=>h.execute([command(values)]));assert.deepEqual(h.session,before);assert.throws(()=>audioStretchPlan(h.session,'missing',1));h.execute([{op:'track.set',target:'audio',values:{protected:true}}]);assert.throws(()=>h.execute([command()]),/protect/i);h.undo();h.execute([{op:'region.set',target:'clip',values:{mute:true}}]);assert.throws(()=>h.execute([command()]),/Unmute/);});
test('stretch validates session revision before mutating',()=>{const h=setup(),revision=h.session.revision;h.execute([{op:'session.set',values:{tempo:110}}]);const before=structuredClone(h.session);assert.throws(()=>h.execute([command()],revision));assert.deepEqual(h.session,before);});

test('musical stretch measures from the region start across tempo changes',async()=>{const {audioStretchBeatPlan}=await import('../src/experimental/audio-stretch-region.js');const h=setup();h.execute([{op:'tempo.add',values:{beat:8,bpm:60}}]);const plan=audioStretchBeatPlan(h.session,'clip',6);assert.equal(plan.region.start,3);assert.equal(plan.ratio,1.25);assert.equal(plan.region.duration*plan.ratio,5);assert.throws(()=>audioStretchBeatPlan(h.session,'clip',100),/50–200/);for(const beats of [0,-1,NaN,Infinity])assert.throws(()=>audioStretchBeatPlan(h.session,'clip',beats));});

test('pitch commit keeps duration and fades, preserves original and supports undo',()=>{const h=setup(),before=structuredClone(h.session);const cmd={op:'region.commitPitch',target:'clip',values:{semitones:7,assetId:'pitched',sampleRate:48000,channels:1,frames:192000}};h.execute([cmd]);const r=h.session.tracks[1].regions[0];assert.equal(r.duration,4);assert.equal(r.fadeIn,.2);assert.equal(r.fadeOut,.4);assert.equal(r.assetId,'pitched');assert.match(r.name,/transposed$/);assert.equal(h.session.tracks[0].regions[0].mute,true);h.undo();assert.deepEqual(h.session.tracks,before.tracks);for(const values of [{semitones:13},{frames:100},{assetId:'original'}])assert.throws(()=>h.execute([{...cmd,values:{...cmd.values,...values}}]));assert.deepEqual(h.session.tracks,before.tracks);});
