import test from 'node:test';import assert from 'node:assert/strict';import {SessionHistory} from '../src/experimental/session.js';
function setup(){const h=new SessionHistory();h.execute([{op:'track.add',values:{id:'t'}},{op:'region.add',target:'t',values:{id:'a',assetId:'one',start:.12,offset:2,duration:.3}},{op:'region.add',target:'t',values:{id:'b',assetId:'two',start:.64,duration:.3}}]);return h;}
const cmd=values=>({op:'regions.quantizeAudio',values:{regionIds:'a,b',grid:.5,...values}});
test('audio quantization preserves source and duration with one undo',()=>{const h=setup(),before=structuredClone(h.session);h.execute([cmd({})]);const regions=h.session.tracks[0].regions;assert.equal(regions[0].start,0);assert.equal(regions[1].start,.75);assert.deepEqual(regions.map(({start,...rest})=>rest),before.tracks[0].regions.map(({start,...rest})=>rest));h.undo();assert.deepEqual(h.session.tracks,before.tracks);});
test('strength follows musical beats across tempo changes and swing delays alternate points',()=>{const h=setup();h.execute([{op:'tempo.add',values:{beat:2,bpm:60}},{op:'region.set',target:'a',values:{start:1.2}}]);h.execute([cmd({regionIds:'a',grid:1,strength:.5})]);assert.ok(Math.abs(h.session.tracks[0].regions[0].start-1.1)<1e-9);const g=setup();g.execute([{op:'region.set',target:'a',values:{start:.35}}]);g.execute([cmd({regionIds:'a',swing:.5})]);assert.ok(Math.abs(g.session.tracks[0].regions[0].start-.375)<1e-9);});
test('group mode retains all audio spacing and saved-attack anchors move the entire source',()=>{const h=setup();h.execute([cmd({mode:'group'})]);assert.ok(Math.abs(h.session.tracks[0].regions[1].start-.52)<1e-9);h.undo();h.execute([{op:'region.attackMarkers',target:'a',values:{times:'[0.1]'}}]);h.execute([cmd({regionIds:'a',anchor:'firstAttack'})]);assert.ok(Math.abs(h.session.tracks[0].regions[0].start-.15)<1e-9);assert.deepEqual(h.session.tracks[0].regions[0].attackMarkers,[2.1]);});
test('missing anchors, protection, timeline overflow and invalid parameters reject atomically',()=>{const h=setup(),before=structuredClone(h.session);for(const values of [{anchor:'firstAttack'},{grid:0},{strength:2},{swing:1},{regionIds:'a,a'}]){assert.throws(()=>h.execute([cmd(values)]));assert.deepEqual(h.session,before);}h.execute([{op:'track.set',target:'t',values:{protected:true}}]);assert.throws(()=>h.execute([cmd({})]),/protect/i);const edge=setup();edge.execute([{op:'region.set',target:'a',values:{start:86399.8,duration:.2}}]);assert.throws(()=>edge.execute([cmd({regionIds:'a',grid:1})]),/outside/);});
test('comp references follow moves but conflicting section overlaps reject the whole change',()=>{const h=setup();h.execute([{op:'comp.save',target:'t',values:{name:'Saved',segments:JSON.stringify([{regionId:'a',start:.12,end:.42},{regionId:'b',start:.64,end:.94}])}}]);h.execute([cmd({mode:'group'})]);assert.ok(Math.abs(h.session.tracks[0].compAlternatives[0].segments[1].start-.52)<1e-9);h.undo();h.execute([{op:'region.set',target:'a',values:{start:.2,duration:.4}},{op:'region.set',target:'b',values:{start:.6,duration:.3}},{op:'comp.save',target:'t',values:{name:'Conflict',segments:JSON.stringify([{regionId:'a',start:.2,end:.6},{regionId:'b',start:.6,end:.89}])}}]);const before=structuredClone(h.session);assert.throws(()=>h.execute([cmd({})]),/overlap/);assert.deepEqual(h.session,before);});
test('agent uses the shared audio timing operation',async()=>{const {planDawEdit}=await import('../server/daw-agent.js'),h=setup(),adapter={key:'test',model:'test',fetchImpl:async()=>({ok:true,json:async()=>({output:[{type:'function_call',name:'edit_session',arguments:JSON.stringify({summary:'Tighten audio timing',commands:[cmd({strength:.5})]})}]})})};const result=await planDawEdit({session:h.session,instruction:'Quantize these audio clips halfway to eighth notes',selectedRegionIds:['a','b']},adapter);h.execute(result.commands,result.revision);assert.ok(Math.abs(h.session.tracks[0].regions[0].start-.06)<1e-9);});

test('mixed selections leave MIDI unchanged and reversed regions use their first visible saved attack',()=>{const h=setup();h.execute([{op:'track.add',values:{id:'m',kind:'midi'}},{op:'region.add',target:'m',values:{id:'midi',start:.13,duration:.3}},{op:'region.set',target:'a',values:{reverse:true}},{op:'region.attackMarkers',target:'a',values:{times:'[0.1,0.2]'}}]);const midi=structuredClone(h.session.tracks[1]);h.execute([cmd({regionIds:'a,midi',anchor:'firstAttack'})]);assert.ok(Math.abs(h.session.tracks[0].regions[0].start-.15)<1e-9);assert.deepEqual(h.session.tracks[1],midi);});
