import test from 'node:test';import assert from 'node:assert/strict';
import {SessionHistory} from '../src/experimental/session.js';import {midiOutputPlan} from '../src/experimental/midi-output-plan.js';import {createMidiOutput} from '../src/experimental/midi-output.js';
const setup=()=>{const h=new SessionHistory();h.execute([{op:'track.add',values:{id:'t',kind:'midi'}},{op:'region.add',target:'t',values:{id:'r',duration:2}},{op:'note.add',target:'r',values:{id:'n',pitch:60,start:0,duration:.5,velocity:.8,channel:2}},{op:'event.add',target:'r',values:{type:'controlChange',parameter:64,value:127,start:.1,channel:2}},{op:'event.add',target:'r',values:{type:'controlChange',parameter:64,value:0,start:1,channel:2}}]);return h;};
test('MIDI hardware plan chases controllers and sustained notes, then releases at region end',()=>{const h=setup(),before=JSON.stringify(h.session),plan=midiOutputPlan(h.session,'t',.75),on=plan.messages.find(m=>m.bytes[0]===0x92),off=plan.messages.find(m=>m.bytes[0]===0x82);assert.equal(on.time,.75);assert.equal(off.time,.75);assert.ok(plan.messages.indexOf(on)<plan.messages.indexOf(off));assert.ok(plan.messages.some(m=>m.time===.75&&m.bytes.join()===`${0xb2},64,127`));assert.ok(plan.messages.some(m=>m.time===1&&m.bytes.join()===`${0xb2},64,0`));assert.equal(plan.end,2);assert.equal(JSON.stringify(h.session),before);});
test('hardware plan rejects overlapping channel regions and ignores muted notes',()=>{const h=setup();h.execute([{op:'note.set',target:'n',values:{mute:true}}]);assert.equal(midiOutputPlan(h.session,'t').messages.some(m=>(m.bytes[0]&240)===144),false);h.execute([{op:'region.duplicate',target:'r',values:{start:1}}]);assert.throws(()=>midiOutputPlan(h.session,'t'),/share a MIDI channel/);});
const fixture=()=>{let now=0,tick,changed=0,stateChange;const sent=[],port={id:'out',name:'Synth',state:'connected',open:async()=>{},close:async()=>{},clear(){sent.push(['clear']);},send(data,at){sent.push([data,at]);}},access={outputs:new Map([['out',port]]),addEventListener(type,fn){stateChange=fn;},removeEventListener(){stateChange=null;}},h=setup(),output=createMidiOutput({session:()=>h.session,position:()=>0,beforePlay(){},onChange(){changed++;},clock:()=>now,requestAccess:async()=>access,schedule:fn=>{tick=fn;return 1;},unschedule(){tick=null;}});output.view(x=>x);return {output,port,sent,h,disconnect(){port.state='disconnected';stateChange?.();},setNow:v=>now=v,tick:()=>tick?.(),changed:()=>changed};};
test('timestamped output uses a bounded lookahead and stop clears queued data and releases touched channels',async()=>{const f=fixture();await f.output.connect();await f.output.play();assert.equal(f.output.playing,true);assert.ok(f.sent.some(([bytes,at])=>Array.isArray(bytes)&&bytes[0]===0x92&&at===50));assert.ok(f.sent.every(([bytes,at])=>!Array.isArray(bytes)||at<=100));f.setNow(100);f.tick();f.output.stop();assert.equal(f.output.playing,false);const clear=f.sent.findIndex(e=>e[0]==='clear');assert.ok(clear>=0);assert.deepEqual(f.sent.slice(clear+1).map(e=>e[0]),[[0xb2,64,0],[0xb2,123,0],[0xb2,120,0]]);const count=f.sent.length;f.tick();assert.equal(f.sent.length,count);});
test('late opens and scheduling interruptions never leave hardware playback running',async()=>{const f=fixture();await f.output.connect();let finish;f.port.open=()=>new Promise(resolve=>finish=resolve);const pending=f.output.play();f.output.stop();finish();await pending;assert.equal(f.output.active,false);assert.equal(f.sent.length,0);f.port.open=async()=>{};await f.output.play();f.setNow(1000);f.tick();assert.equal(f.output.active,false);assert.ok(f.sent.some(e=>e[0]==='clear'));});

test('disconnect and failed port opens restore controls without leaving queued notes',async()=>{const f=fixture();await f.output.connect();await f.output.play();f.disconnect();assert.equal(f.output.active,false);assert.ok(f.sent.some(e=>e[0]==='clear'));assert.match(f.output.view(x=>x),/disconnected/);const g=fixture();await g.output.connect();g.port.open=async()=>{throw Error('Port unavailable');};const before=g.changed();await g.output.play();assert.equal(g.output.active,false);assert.ok(g.changed()>before);assert.match(g.output.view(x=>x),/Port unavailable/);});
