import {readMidi,writeMidi} from '../src/experimental/midi.js';
import test from 'node:test';import assert from 'node:assert/strict';
import {SessionHistory} from '../src/experimental/session.js';import {velocityRampEdits} from '../src/experimental/velocity-ramp.js';
const fixture=()=>{const h=new SessionHistory();h.execute([{op:'track.add',values:{id:'t',kind:'midi'}},{op:'region.add',target:'t',values:{id:'r',duration:4}},...[0,1,2,2].map((start,i)=>({op:'note.add',target:'r',values:{id:'n'+i,pitch:60+i,start,duration:.5,velocity:.6,channel:i}}))]);return h;};
const region=h=>h.session.tracks[0].regions[0];
test('velocity ramp uses onset spacing, preserves chords and non-velocity data, and undoes as one edit',()=>{const h=fixture(),before=structuredClone(region(h));h.execute([{op:'notes.velocityRamp',target:'r',values:{from:.2,to:1}}]);region(h).notes.forEach((n,i)=>assert.ok(Math.abs(n.velocity-[.2,.6,1,1][i])<1e-12));assert.deepEqual(region(h),{...before,notes:before.notes.map((n,i)=>({...n,velocity:region(h).notes[i].velocity}))});h.undo();assert.deepEqual(region(h),before);h.redo();assert.equal(region(h).notes[3].velocity,1);});
test('selected ramps, descending curves, region bounds and single onsets are deterministic',()=>{const r=region(fixture());assert.deepEqual(velocityRampEdits(r,{from:1,to:0,curve:'easeIn'}).map(n=>n.velocity),[1,.75,0,0]);assert.deepEqual(velocityRampEdits(r,{from:0,to:1,curve:'easeOut'}).map(n=>n.velocity),[0,.75,1,1]);assert.deepEqual(velocityRampEdits(r,{from:0,to:1,bounds:'region'}).map(n=>n.velocity),[0,.25,.5,.5]);assert.deepEqual(velocityRampEdits(r,{from:.3,to:.9,noteIds:'n2,n3'}).map(n=>n.velocity),[.3,.3]);const h=fixture();h.execute([{op:'notes.velocityRamp',target:'r',values:{from:.1,to:.9,noteIds:'n0,n2'}}]);assert.deepEqual(region(h).notes.map(n=>n.velocity),[.1,.6,.9,.6]);});
test('invalid ramp arguments or selection reject an entire batch without history changes',()=>{const h=fixture(),before=structuredClone(h.session),depth=h.past.length;for(const bad of [{from:-1,to:1},{from:0,to:2},{from:NaN,to:1},{from:0,to:1,noteIds:'missing'},{from:0,to:1,noteIds:''},{from:0,to:1,noteId:'n0',noteIds:'n1'},{from:0,to:1,curve:'wrong'}]){assert.throws(()=>h.execute([{op:'session.set',values:{title:'Must roll back'}},{op:'notes.velocityRamp',target:'r',values:bad}]));assert.deepEqual(h.session,before);assert.equal(h.past.length,depth);}assert.throws(()=>velocityRampEdits({notes:[]},{from:0,to:1}),/Add or select/);});

test('ramped velocities survive MIDI export with channel, pitch and timing preserved',()=>{const h=fixture();h.execute([{op:'notes.velocityRamp',target:'r',values:{from:20/127,to:120/127}}]);const notes=readMidi(writeMidi(h.session).buffer).tracks.flatMap(t=>t.notes).sort((a,b)=>a.pitch-b.pitch);assert.deepEqual(notes.map(n=>Math.round(n.velocity*127)),[20,70,120,120]);assert.deepEqual(notes.map(n=>n.channel),[0,1,2,3]);assert.deepEqual(notes.map(n=>n.start),[0,1,2,2]);assert.ok(notes.every(n=>n.duration===.5));});
