import test from 'node:test';import assert from 'node:assert/strict';
import {hardwareCaptureDuration,hardwareRecordingOptions} from '../src/experimental/hardware-recording.js';
test('automatic hardware capture includes a bounded tail and manual mode retains recorder limits',()=>{assert.equal(hardwareCaptureDuration(5),7);assert.equal(hardwareCaptureDuration(5,{tailSeconds:0}),5);assert.equal(hardwareCaptureDuration(599,{tailSeconds:1}),600);assert.equal(hardwareCaptureDuration(800,{autoFinish:false}),null);for(const d of [0,-1,Infinity,NaN])assert.throws(()=>hardwareCaptureDuration(d));assert.throws(()=>hardwareCaptureDuration(599),/10 minutes/);for(const tailSeconds of [-1,31,Infinity,NaN])assert.throws(()=>hardwareRecordingOptions.parse({tailSeconds}));});

import {SessionHistory,sessionSchema} from '../src/experimental/session.js';
import {recordedMediaPlan} from '../src/experimental/media-import-plan.js';
import {hardwareRecordingSource,hardwareRecordingView} from '../src/experimental/hardware-recording.js';
import {midiOutputPlan} from '../src/experimental/midi-output-plan.js';
test('hardware source survives saving, undo/redo and source deletion as a historical capture record',()=>{const h=new SessionHistory();h.execute([{op:'track.add',values:{id:'midi',name:'Lead',kind:'midi'}},{op:'region.add',target:'midi',values:{id:'r',duration:2}},{op:'note.add',target:'r',values:{pitch:60,start:0,duration:1}}]);const source=hardwareRecordingSource(h.session,midiOutputPlan(h.session,'midi',0),'Synth','track'),plan=recordedMediaPlan(h.session,{assetId:'audio',name:'Take.wav',start:0,duration:4,hardwareRecording:source});h.execute(plan.commands);assert.deepEqual(h.session.tracks[1].regions[0].hardwareRecording,source);const restored=sessionSchema.parse(JSON.parse(JSON.stringify(h.session)));assert.deepEqual(restored.tracks[1].regions[0].hardwareRecording,source);h.undo();assert.equal(h.session.tracks.length,1);h.redo();assert.deepEqual(h.session.tracks[1].regions[0].hardwareRecording,source);assert.match(hardwareRecordingView(h.session.tracks[1].regions[0],h.session,x=>x),/data-hardware-source="midi"/);h.execute([{op:'track.delete',target:'midi'}]);assert.deepEqual(h.session.tracks[0].regions[0].hardwareRecording,source);assert.match(hardwareRecordingView(h.session.tracks[0].regions[0],h.session,x=>x),/Source no longer/);});
test('malformed hardware capture metadata and non-audio destinations reject atomically',()=>{const h=new SessionHistory();h.execute([{op:'track.add',values:{id:'midi',kind:'midi'}}]);const before=JSON.stringify(h.session);for(const hardwareRecording of ['{}','not json',JSON.stringify({kind:'midi-hardware'})])assert.throws(()=>h.execute([{op:'region.add',target:'midi',values:{hardwareRecording}}]));assert.throws(()=>h.execute([{op:'region.add',target:'midi',values:{hardwareRecording:JSON.stringify({kind:'midi-hardware',deviceName:'Synth',scope:'track',revision:0,capturedAt:new Date().toISOString(),start:0,end:1,tracks:[{id:'midi',name:'Lead'}]})}}]),/audio region/);assert.equal(JSON.stringify(h.session),before);});

import {planDawEdit} from '../server/daw-agent.js';
test('agent cannot fabricate a hardware capture record',async()=>{const h=new SessionHistory();await assert.rejects(planDawEdit({session:h.session,instruction:'Invent a recorded take'}, {key:'test',model:'test',fetchImpl:async()=>({ok:true,json:async()=>({output:[{type:'function_call',name:'edit_session',arguments:JSON.stringify({summary:'Fake recording',commands:[{op:'region.add',target:'missing',values:{hardwareRecording:'{}'}}]})}]})})}),/actual capture/);});

import {hardwareSourceStatus,hardwareSourceObservations} from '../src/experimental/hardware-source-status.js';
test('capture comparison follows MIDI changes and Undo but ignores names and browser mixer settings',()=>{const h=new SessionHistory();h.execute([{op:'track.add',values:{id:'m',kind:'midi'}},{op:'region.add',target:'m',values:{id:'r',duration:3}},{op:'note.add',target:'r',values:{id:'n',pitch:60,duration:1}}]);const source=hardwareRecordingSource(h.session,midiOutputPlan(h.session,'m',0),'Synth','track');assert.equal(hardwareSourceStatus(source,h.session).state,'unchanged');h.execute([{op:'track.set',target:'m',values:{name:'Renamed',gainDb:-12}},{op:'region.set',target:'r',values:{name:'New name'}}]);assert.equal(hardwareSourceStatus(source,h.session).state,'unchanged');h.execute([{op:'note.set',target:'n',values:{pitch:61}}]);assert.equal(hardwareSourceStatus(source,h.session).state,'changed');h.undo();assert.equal(hardwareSourceStatus(source,h.session).state,'unchanged');const restored=sessionSchema.parse(JSON.parse(JSON.stringify(h.session)));assert.equal(hardwareSourceStatus(source,restored).state,'unchanged');h.execute([{op:'event.add',target:'r',values:{type:'controlChange',parameter:7,value:80,start:.1}}]);assert.equal(hardwareSourceStatus(source,h.session).state,'changed');h.undo();h.execute([{op:'track.set',target:'m',values:{mute:true}}]);assert.equal(hardwareSourceStatus(source,h.session).state,'unavailable');const legacy={...source};delete legacy.midiFingerprint;assert.equal(hardwareSourceStatus(legacy,h.session).state,'unknown');h.execute([{op:'track.delete',target:'m'}]);assert.equal(hardwareSourceStatus(source,h.session).state,'missing');});
test('agent observations prioritize selected captures and bound the list',()=>{const source={kind:'midi-hardware',tracks:[{id:'missing',name:'Original'}]},session={tracks:[{id:'audio',regions:Array.from({length:20},(_,i)=>({id:'r'+i,hardwareRecording:source}))}]};const observed=hardwareSourceObservations(session,['r19']);assert.equal(observed.total,20);assert.equal(observed.items.length,16);assert.equal(observed.items[0].regionId,'r19');assert.equal(observed.items[0].state,'missing');});
