import test from 'node:test';import assert from 'node:assert/strict';import {createTouchRecording} from '../src/experimental/automation-touch.js';import {newSession,SessionHistory} from '../src/experimental/session.js';import {curveAutomationValue} from '../src/experimental/automation-curves.js';
function setup(mode){const h=new SessionHistory(newSession());h.execute([{op:'track.add',values:{id:'t',kind:'audio'}},{op:'automation.point',target:'t',values:{parameter:'gainDb',time:0,value:-24}},{op:'automation.point',target:'t',values:{parameter:'gainDb',time:10,value:-12}}]);const calls=[],state={position:2,epoch:1,playback:{automation:Object.fromEntries(['trim','resume','cancel','replace'].map(name=>[name,(...args)=>calls.push([name,...args])]))}};const recorder=createTouchRecording({getMode:()=>mode,getState:()=>({...state,session:h.session}),commit:(commands,revision)=>h.execute(commands,revision)});return {h,state,calls,recorder};}
test('Trim Touch commits offset samples and resumes the resulting curve on release',()=>{
 const {h,state,calls,recorder}=setup('trimTouch'),before=structuredClone(h.session);recorder.input('t','gainDb',3);state.position=4;recorder.input('t','gainDb',6);state.position=5;recorder.release('t','gainDb');assert.equal(recorder.active,false);assert.equal(calls.at(-1)[0],'resume');for(const [time,offset]of [[1,0],[3,4.5],[4.5,6],[6,0]])assert.ok(Math.abs(curveAutomationValue(h.session.tracks[0].automation,'gainDb',time,0)-curveAutomationValue(before.tracks[0].automation,'gainDb',time,0)-offset)<1e-9);h.undo();assert.deepEqual(h.session.tracks,before.tracks);
});
test('Trim Latch holds several offsets through repaint and commits one pass on Stop',()=>{
 const {h,state,recorder}=setup('trimLatch'),before=structuredClone(h.session);recorder.input('t','gainDb',3);state.position=3;recorder.release('t','gainDb');recorder.input(h.session.id,'pan',.2);state.position=4;recorder.release(h.session.id,'pan');recorder.beforePaint();assert.equal(recorder.count,2);assert.equal(recorder.value('t','gainDb'),3);assert.equal(h.session.revision,before.revision);state.position=6;recorder.finish();assert.equal(h.session.revision,before.revision+1);assert.ok(Math.abs(curveAutomationValue(h.session.tracks[0].automation,'gainDb',5,0)+15)<1e-9);assert.equal(curveAutomationValue(h.session.masterAutomation,'pan',5,0),.2);h.undo();assert.deepEqual(h.session.tracks,before.tracks);assert.deepEqual(h.session.masterAutomation,before.masterAutomation);
});
test('Trim cancellation and failed playback scheduling restore original state',()=>{
 const {h,state,recorder,calls}=setup('trimTouch'),before=structuredClone(h.session);recorder.input('t','gainDb',3);state.position=3;recorder.cancel();assert.deepEqual(h.session,before);assert.equal(calls.at(-1)[0],'cancel');state.playback.automation.trim=()=>{throw Error('Future limit');};assert.throws(()=>recorder.input('t','gainDb',12),/Future limit/);assert.equal(recorder.active,false);assert.deepEqual(h.session,before);
});
