import test from 'node:test';import assert from 'node:assert/strict';import {newSession,SessionHistory} from '../src/experimental/session.js';import {curveAutomationValue} from '../src/experimental/automation-curves.js';import {sendAutomationTarget} from '../src/experimental/automation-recording-lane.js';
function setup(){const h=new SessionHistory(newSession());h.execute([{op:'track.add',values:{id:'a',kind:'audio'}},{op:'track.add',values:{id:'b',kind:'audio'}},{op:'track.add',values:{id:'fx',kind:'bus'}},...['a','b'].map(target=>({op:'send.set',target,values:{busId:'fx',gainDb:-12}}))]);return h;}
const command=(op='automation.record',target='a',parameter='gainDb',busId='fx')=>({op,target,values:{parameter,busId,samples:JSON.stringify([{time:2,value:3},{time:4,value:6}]),returnSeconds:1}});
test('send recording targets its source and bus pair, preserves routing and other channels, and undoes',()=>{
 const h=setup(),before=structuredClone(h.session);h.execute([command()]);assert.equal(curveAutomationValue(h.session.tracks[0].sends[0].automation,'gainDb',3,-12),4.5);assert.deepEqual(h.session.tracks.slice(1),before.tracks.slice(1));assert.deepEqual(h.session.tracks[0].automation,[]);assert.equal(h.session.tracks[0].sends[0].gainDb,-12);assert.equal(h.session.tracks[0].sends[0].tap,'postPan');h.undo();assert.deepEqual(h.session.tracks,before.tracks);
});
test('send trim follows saved automation with fallback and retains send Read/Off mode',()=>{
 const h=setup();h.execute([{op:'send.automation.point',target:'a',values:{busId:'fx',time:0,value:-24,shape:'smooth'}},{op:'send.automation.point',target:'a',values:{busId:'fx',time:10,value:-12}},{op:'send.set',target:'a',values:{busId:'fx',automationMode:'off'}}]);const before=structuredClone(h.session);h.execute([command('automation.trimRecord')]);const send=h.session.tracks[0].sends[0];assert.equal(send.automationMode,'off');assert.ok(Math.abs(curveAutomationValue(send.automation,'gainDb',3,-12)-curveAutomationValue(before.tracks[0].sends[0].automation,'gainDb',3,-12)-4.5)<1e-9);assert.deepEqual(h.session.tracks[1],before.tracks[1]);
});
test('invalid send identities, unsupported pan and point overflow fail without a partial edit',()=>{
 const h=setup(),before=structuredClone(h.session);for(const op of ['automation.record','automation.trimRecord'])for(const c of [command(op,'missing'),command(op,h.session.id),command(op,'a','pan'),command(op,'a','gainDb','missing'),command(op,'fx')]){assert.throws(()=>h.execute([{op:'session.set',values:{title:'No partial change'}},c]));assert.deepEqual(h.session,before);}
 h.session.tracks[0].sends[0].automation=Array.from({length:2000},(_,i)=>({id:'p'+i,parameter:'gainDb',time:100+i,value:-12}));const full=structuredClone(h.session);assert.throws(()=>h.execute([command()]));assert.deepEqual(h.session,full);
});
test('playback exposes isolated send controls and keeps muted source sends protected',async()=>{
 const {scheduleSession}=await import('../src/experimental/audio-engine.js');const h=setup(),events=[],param=()=>({value:0,cancelScheduledValues(){},setValueAtTime(v,t){events.push([this,v,t]);},linearRampToValueAtTime(){},exponentialRampToValueAtTime(){}}),node=()=>({gain:param(),pan:param(),connect(other){return other;},disconnect(){}}),ctx={currentTime:0,destination:node(),createGain:node,createStereoPanner:node};
 h.execute([{op:'track.set',target:'b',values:{mute:true}}]);const player=scheduleSession(ctx,h.session,new Map(),0,{baseTime:0});player.automation.set(sendAutomationTarget('a','fx'),'gainDb',-6);const sendParam=events.at(-1)[0];player.automation.set('a','gainDb',-6);assert.notEqual(events.at(-1)[0],sendParam);assert.throws(()=>player.automation.set(sendAutomationTarget('b','fx'),'gainDb',0));assert.throws(()=>player.automation.set(sendAutomationTarget('a','fx'),'pan',0));player.stop();
});
test('agent can specify send-scoped recording without changing the input document',async()=>{
 const {planDawEdit}=await import('../server/daw-agent.js');const h=setup(),before=structuredClone(h.session);let request;const result=await planDawEdit({session:h.session,instruction:'Raise the reverb send for this phrase'},{provider:'openai',key:'test',model:'test',fetchImpl:async(_,init)=>{request=JSON.parse(init.body);return {ok:true,json:async()=>({output:[{type:'function_call',name:'edit_session',arguments:JSON.stringify({summary:'Recorded send curve',commands:[command()]})}]})};}});assert.match(request.input[0].content,/busId/);assert.deepEqual(h.session,before);h.execute(result.commands,result.revision);assert.ok(h.session.tracks[0].sends[0].automation.length);assert.equal(h.session.tracks[1].sends[0].automation.length,0);
});
test('send controls record independent source/bus lanes through Touch, Latch and Trim',async()=>{
 const {createTouchRecording}=await import('../src/experimental/automation-touch.js');
 for(const mode of ['touch','latch','trimTouch','trimLatch']){
  const h=setup(),before=structuredClone(h.session),calls=[],state={position:1,epoch:1,playback:{automation:Object.fromEntries(['set','trim','replace','resume','release','cancel'].map(name=>[name,(...args)=>calls.push([name,...args])]))}},recorder=createTouchRecording({getMode:()=>mode,getState:()=>({...state,session:h.session}),commit:(commands,revision)=>h.execute(commands,revision)});
  recorder.input('a','gainDb',3,'fx');state.position=2;recorder.release('a','gainDb','fx');if(mode.endsWith('Latch')||mode==='latch'){recorder.beforePaint();assert.equal(recorder.value('a','gainDb','fx'),3);assert.equal(recorder.value('a','gainDb'),undefined);state.position=3;recorder.finish();}
  assert.equal(calls[0][1],sendAutomationTarget('a','fx'));assert.equal(curveAutomationValue(h.session.tracks[0].sends[0].automation,'gainDb',1.5,-12),mode.startsWith('trim')?-9:3);assert.deepEqual(h.session.tracks[1],before.tracks[1]);h.undo();assert.deepEqual(h.session.tracks,before.tracks);
 }
});
test('send recording respects its parent mode but not the parent fader parameter mute',async()=>{
 const {createTouchRecording}=await import('../src/experimental/automation-touch.js');const h=setup(),state={position:1,epoch:1,playback:{automation:{set(){},cancel(){}}}},recorder=createTouchRecording({getState:()=>({...state,session:h.session}),commit:()=>{}});
 h.session.tracks[0].automationMuted=['gainDb'];recorder.input('a','gainDb',-6,'fx');recorder.cancel();h.session.tracks[0].automationMode='off';assert.throws(()=>recorder.input('a','gainDb',-6,'fx'),/Read/);h.session.tracks[0].automationMode='read';h.session.tracks[0].sends[0].automationMode='off';assert.throws(()=>recorder.input('a','gainDb',-6,'fx'),/Read/);
});
