import test from 'node:test';import assert from 'node:assert/strict';import {detectTransients,adjacentTransient} from '../src/experimental/audio-transients.js';
const rate=48000;
function fixture(){const data=new Float32Array(rate);for(const onset of [.2,.6])for(let i=Math.round(onset*rate);i<Math.round((onset+.15)*rate);i++)data[i]=.5*Math.sin(2*Math.PI*440*(i-onset*rate)/rate);return data;}
test('energy attacks locate separate phrases without repeated sustain detections',()=>{const data=fixture(),before=data.slice(),markers=detectTransients([data],rate);assert.equal(markers.length,2);assert.ok(Math.abs(markers[0]-.2)<.002);assert.ok(Math.abs(markers[1]-.6)<.002);assert.deepEqual(data,before);});
test('opposite-phase stereo retains attacks, silence and subfloor signals do not',()=>{const data=fixture();assert.deepEqual(detectTransients([data,data.map(v=>-v)],rate),detectTransients([data],rate));assert.deepEqual(detectTransients([new Float32Array(rate)],rate),[]);assert.deepEqual(detectTransients([data.map(v=>v*.001)],rate),[]);});
test('minimum gap suppresses nearby attacks and validation rejects corrupt samples',()=>{assert.equal(detectTransients([fixture()],rate,{minimumGap:.5}).length,1);const data=fixture();data[100]=NaN;assert.throws(()=>detectTransients([data],rate));assert.throws(()=>detectTransients([fixture()],rate,{riseDb:0}));assert.throws(()=>detectTransients([fixture()],1));});
test('attack navigation skips current point and handles endpoints',()=>{const markers=[.2,.6];assert.equal(adjacentTransient(markers,.2,'next',rate),.6);assert.equal(adjacentTransient(markers,.6,'previous',rate),.2);assert.equal(adjacentTransient(markers,.6,'next',rate),undefined);assert.equal(adjacentTransient(markers,0,'previous',rate),undefined);});

test('agent detection is capability-gated and validates source and settings',async()=>{const {SessionHistory}=await import('../src/experimental/session.js'),{planDawEdit}=await import('../server/daw-agent.js');const h=new SessionHistory();h.execute([{op:'track.add',values:{id:'t'}},{op:'region.add',target:'t',values:{id:'r',assetId:'a',duration:2}}]);const input={session:h.session,instruction:'Find attacks',selection:'r',allowTransients:true},settings={riseDb:9,floorDb:-45,minimumGap:.05};let tool;const adapter={key:'test',model:'test',fetchImpl:async(_,o)=>{tool=JSON.parse(o.body).tools.find(t=>t.name==='detect_audio_attacks');return {ok:true,json:async()=>({output:[{type:'function_call',name:'detect_audio_attacks',arguments:JSON.stringify({operation:'preview',regionId:null,settings})}]})};}};const result=await planDawEdit(input,adapter);assert.equal(tool.strict,true);assert.equal(result.analysis.regionId,'r');assert.deepEqual(result.commands,[]);await assert.rejects(planDawEdit({...input,allowTransients:false},adapter));await assert.rejects(planDawEdit({...input,editingContinuation:true},adapter));await assert.rejects(planDawEdit({...input,selection:'missing'},adapter));});

test('split analysis rejects protected sources while preview remains allowed',async()=>{const {SessionHistory}=await import('../src/experimental/session.js'),{prepareTransientAnalysis}=await import('../src/experimental/transient-action.js');const h=new SessionHistory();h.execute([{op:'track.add',values:{id:'t'}},{op:'region.add',target:'t',values:{id:'r',assetId:'a',duration:2}},{op:'track.set',target:'t',values:{protected:true}}]);const input={operation:'preview',regionId:null,settings:{riseDb:9,floorDb:-45,minimumGap:.05}};assert.equal(prepareTransientAnalysis(h.session,input,'r').regionId,'r');assert.throws(()=>prepareTransientAnalysis(h.session,{...input,operation:'split'},'r'),/Unprotect/);});
