import test from 'node:test';import assert from 'node:assert/strict';import {eqFrequencyX,eqGainY,eqPointValues,eqKeyboardValues,eqPlot,eqGraphView} from '../src/experimental/eq-graph.js';
const eq={id:'eq',kind:'eq',type:'peaking',frequency:1000,gainDb:3,q:1,enabled:true,automation:[]};
test('EQ graph maps logarithmic frequency and signed gain, with clamped drag bounds',()=>{for(const f of [20,100,1000,10000,20000])assert.ok(Math.abs(eqPointValues(eq,eqFrequencyX(f),eqGainY(6)).frequency-f)<1e-8);for(const db of [-24,-12,0,12,24])assert.ok(Math.abs(eqPointValues(eq,eqFrequencyX(1000),eqGainY(db)).gainDb-db)<1e-8);assert.deepEqual(eqPointValues(eq,-100,500),{frequency:20,gainDb:-24});assert.deepEqual(eqPointValues(eq,999,-100),{frequency:20000,gainDb:24});assert.equal(eqFrequencyX(200),eqPlot.left+eqPlot.width/3);});
test('pass-filter drags and vertical keys do not change ignored gain fields; keyboard fine controls remain bounded',()=>{for(const type of ['lowpass','highpass','notch','bandpass']){const values=eqPointValues({...eq,type},eqFrequencyX(1000),0);assert.ok(Math.abs(values.frequency-1000)<1e-8);assert.equal(values.gainDb,undefined);assert.equal(eqKeyboardValues({...eq,type},'ArrowUp'),null);}assert.deepEqual(eqKeyboardValues(eq,'ArrowUp'),{gainDb:3.5});assert.deepEqual(eqKeyboardValues(eq,'ArrowDown',true),{gainDb:2.9});assert.equal(eqKeyboardValues(eq,'ArrowRight').frequency,1000*2**(1/12));assert.equal(eqKeyboardValues({...eq,frequency:20000},'ArrowRight').frequency,20000);assert.equal(eqKeyboardValues({...eq,gainDb:24},'ArrowUp').gainDb,24);assert.equal(eqKeyboardValues(eq,'Enter'),null);});
test('EQ graph has keyboard instructions and is limited to EQ inserts',()=>{assert.match(eqGraphView(eq),/tabindex="0"/);assert.match(eqGraphView(eq),/Escape cancels/);assert.equal(eqGraphView({kind:'delay'}),'');});

test('notch and bandpass share schema, commands, automation and undo with other EQ modes',async()=>{
 const {SessionHistory}=await import('../src/experimental/session.js');const {effectSchema}=await import('../src/experimental/effects.js');const h=new SessionHistory();
 for(const type of ['notch','bandpass']){const e=effectSchema.parse({id:type,kind:'eq',type});assert.equal(e.type,type);}
 h.execute([{op:'effect.add',target:h.session.id,values:{id:'n',kind:'eq',type:'notch',frequency:60,q:20}},{op:'effect.automation.point',target:'n',values:{parameter:'q',time:1,value:10}}]);
 h.execute([{op:'effect.set',target:'n',values:{type:'bandpass'}}]);assert.equal(h.session.masterEffects[0].type,'bandpass');h.undo();assert.equal(h.session.masterEffects[0].type,'notch');h.redo();assert.equal(h.session.masterEffects[0].automation[0].value,10);
});
