import test from 'node:test';import assert from 'node:assert/strict';
import {newSession,SessionHistory} from '../src/experimental/session.js';
import {adjacentMarker,orderedMarkers} from '../src/experimental/markers.js';
test('markers rename and move atomically with stable identity and undo',()=>{const h=new SessionHistory(newSession());h.execute([{op:'marker.add',values:{id:'chorus',name:'Chorus',time:30}}]);h.execute([{op:'marker.set',target:'chorus',values:{name:'Final chorus',time:45}}]);assert.deepEqual(h.session.markers,[{id:'chorus',name:'Final chorus',time:45}]);h.undo();assert.equal(h.session.markers[0].time,30);h.redo();const before=structuredClone(h.session);for(const command of [{op:'marker.set',target:'chorus',values:{time:-1}},{op:'marker.set',target:'missing',values:{time:1}},{op:'marker.set',target:'chorus',values:{id:'other'}},{op:'marker.add',values:{id:'chorus',time:10}}])assert.throws(()=>h.execute([{op:'marker.set',target:'chorus',values:{name:'Changed'}},command]));assert.deepEqual(h.session,before);h.execute([{op:'marker.delete',target:'chorus'}]);assert.equal(h.session.markers.length,0);h.undo();assert.deepEqual(h.session.markers,before.markers);});
test('marker navigation is chronological, skips coincident markers, and does not reorder document',()=>{const session={markers:[{id:'b',name:'B',time:30},{id:'a',name:'A',time:10},{id:'c',name:'C',time:30}]};assert.deepEqual(orderedMarkers(session).map(m=>m.id),['a','b','c']);assert.equal(adjacentMarker(session,10,1).time,30);assert.equal(adjacentMarker(session,30,-1).time,10);assert.equal(adjacentMarker(session,30,1),undefined);assert.equal(adjacentMarker(session,0,-1),undefined);assert.equal(session.markers[0].id,'b');});

test('marker timecode commands honor the session start and reject ambiguous or skipped labels atomically',()=>{const h=new SessionHistory();h.execute([{op:'session.set',values:{frameRate:29.97,dropFrame:true,timecodeOffset:3599.9964}},{op:'marker.add',values:{id:'cue',name:'Cue',timecode:'01:00:01;00'}}]);assert.ok(Math.abs(h.session.markers[0].time-1.001)<1e-8);h.execute([{op:'marker.set',target:'cue',values:{timecode:'01:01:00;02'}}]);const before=JSON.stringify(h.session);for(const values of [{timecode:'01:01:00;00'},{time:1,timecode:'01:00:01;00'},{timecode:'00:59:59;29'}])assert.throws(()=>h.execute([{op:'marker.set',target:'cue',values}]));assert.equal(JSON.stringify(h.session),before);h.undo();assert.ok(Math.abs(h.session.markers[0].time-1.001)<1e-8);});
import {bindMarkers,markersView} from '../src/experimental/markers.js';
test('renaming a marker through a rounded timecode field preserves its precise position',()=>{const session={frameRate:24,timecodeOffset:3600,markers:[{id:'m',name:'Original',time:1.012345}]},form={dataset:{markerEdit:'m'},elements:{name:{value:'Renamed'},time:{value:'01:00:01:00'}}};let commands;const root={querySelector:()=>({}),querySelectorAll:selector=>selector==='[data-marker-edit]'?[form]:[]};bindMarkers(root,{session,mode:'timecode',position:0,seek(){},execute:c=>commands=c,guard:fn=>fn});form.onsubmit({preventDefault(){}});assert.equal(commands[0].values.time,1.012345);form.elements.time.value='01:00:02:00';form.onsubmit({preventDefault(){}});assert.equal(commands[0].values.time,2);assert.match(markersView(session,0,x=>x,false,'timecode'),/01:00:01:00/);});
