import test from 'node:test';import assert from 'node:assert/strict';
import {quantizeNotes} from '../src/experimental/note-transforms.js';
import {SessionHistory} from '../src/experimental/session.js';
const session={tempo:120,tempoChanges:[{beat:8,bpm:60}]};
const region=()=>({start:3,duration:5,notes:[{id:'a',start:.4,duration:.2},{id:'b',start:1.4,duration:.2},{id:'c',start:2.4,duration:.2}]});
test('musical quantize follows beat spacing after tempo changes and retains note lengths',()=>{const r=region();quantizeNotes(r,{timing:'beats',grid:1},session);assert.deepEqual(r.notes.map(n=>n.start),[.5,1,2]);assert.ok(r.notes.every(n=>n.duration===.2));const seconds=region();quantizeNotes(seconds,{grid:.5});assert.deepEqual(seconds.notes.map(n=>n.start),[.5,1.5,2.5]);});
test('strength interpolates in beats across a tempo change and swing delays alternate beats',()=>{const r={start:3,duration:5,notes:[{id:'a',start:.9,duration:.1}]};quantizeNotes(r,{timing:'beats',grid:3,strength:.5},session);assert.ok(Math.abs(r.notes[0].start-1.4)<1e-10);const s=region();quantizeNotes(s,{timing:'beats',grid:1,swing:.5},session);assert.deepEqual(s.notes.map(n=>n.start),[.75,1,2.5]);});
test('musical quantization respects scope, zero strength, and region boundaries',()=>{const r=region();r.notes.push({id:'last',start:4.7,duration:.3});quantizeNotes(r,{timing:'beats',grid:1,noteId:'last'},session);assert.deepEqual(r.notes.map(n=>n.start),[.4,1.4,2.4,4.7]);const before=structuredClone(r);quantizeNotes(r,{timing:'beats',grid:1,strength:0},session);assert.deepEqual(r,before);assert.throws(()=>quantizeNotes(r,{timing:'beats',grid:1}),/session timing/);});
test('musical quantize commands remain validated, atomic and undoable',()=>{const h=new SessionHistory();h.execute([{op:'track.add',values:{id:'t',kind:'midi'}},{op:'region.add',target:'t',values:{id:'r',duration:4}},{op:'note.add',target:'r',values:{id:'n',pitch:60,start:.4,duration:.25}}]);const before=structuredClone(h.session);h.execute([{op:'notes.quantize',target:'r',values:{timing:'beats',grid:1}}]);assert.equal(h.session.tracks[0].regions[0].notes[0].start,.5);h.undo();assert.deepEqual(h.session.tracks,before.tracks);assert.throws(()=>h.execute([{op:'notes.quantize',target:'r',values:{timing:'beats',grid:1}},{op:'notes.quantize',target:'r',values:{timing:'ticks',grid:1}}]));assert.deepEqual(h.session.tracks,before.tracks);});
