import test from 'node:test';import assert from 'node:assert/strict';
import {detectMelody} from '../src/experimental/audio-melody.js';
import {melodyMidiCommands,prepareMelodyAnalysis} from '../src/experimental/melody-action.js';
import {SessionHistory} from '../src/experimental/session.js';
import {planDawEdit} from '../server/daw-agent.js';
const settings={minPitch:36,maxPitch:84,floorDb:-45,minimumDuration:.08};
const melody=(rate=48000)=>{const c=new Float32Array(rate*2);for(let i=0;i<c.length;i++){const t=i/rate;if(t>=.2&&t<.9)c[i]=.3*Math.sin(2*Math.PI*440*t);if(t>=1.1&&t<1.8)c[i]=.3*Math.sin(2*Math.PI*523.251*t);}return c;};
test('monophonic analysis finds separated tones, timing and tuning without stereo cancellation',()=>{for(const rate of [8000,44100,48000,96000]){const channel=melody(rate),copy=channel.slice(),notes=detectMelody([channel,channel.map(v=>-v)],rate);assert.deepEqual(notes.map(n=>n.pitch),[69,72]);for(let i=0;i<2;i++){assert.ok(Math.abs(notes[i].start-[.2,1.1][i])<.045);assert.ok(Math.abs(notes[i].duration-.7)<.045);assert.ok(Math.abs(notes[i].cents)<8);assert.ok(notes[i].confidence>.9);}assert.deepEqual(channel,copy);}});
test('silence, DC, seeded noise and brief impulses do not become melody notes',()=>{const silence=new Float32Array(16000),noise=silence.slice();let seed=17;for(let i=0;i<noise.length;i++){seed=(1664525*seed+1013904223)>>>0;noise[i]=(seed/2**32-.5)*.3;}for(const c of [silence,silence.map(()=>.3),noise])assert.deepEqual(detectMelody([c],8000),[]);silence[8000]=1;assert.deepEqual(detectMelody([silence],8000),[]);assert.throws(()=>detectMelody([Float32Array.of(NaN)],8000));assert.throws(()=>detectMelody([silence],8000,{minPitch:84,maxPitch:36}));});
const setup=()=>{const h=new SessionHistory();h.execute([{op:'track.add',values:{id:'t',kind:'audio'}},{op:'region.add',target:'t',values:{id:'r',assetId:'source',name:'Voice',start:3,duration:2}}]);return h;};
test('MIDI extraction preserves the recording, aligns notes, supports Undo and rejects stale analysis',()=>{const h=setup(),before=structuredClone(h.session),analysis={sessionId:h.session.id,revision:h.session.revision,regionId:'r',notes:detectMelody([melody()],48000)},plan=melodyMidiCommands(h.session,analysis);assert.deepEqual(h.session,before);h.execute(plan.commands);assert.deepEqual(h.session.tracks[0],before.tracks[0]);assert.equal(h.session.tracks[1].regions[0].start,3);assert.deepEqual(h.session.tracks[1].regions[0].notes.map(n=>n.pitch),[69,72]);assert.throws(()=>melodyMidiCommands(h.session,analysis),/changed/);h.undo();assert.deepEqual(h.session.tracks,before.tracks);assert.throws(()=>melodyMidiCommands(h.session,{...analysis,revision:h.session.revision,notes:[]}),/No detected/);});
test('agent melody analysis is separately gated, validates its source and never invents measured notes',async()=>{const h=setup(),input={session:h.session,instruction:'Extract MIDI from this melody',selection:'r',allowMelodyAnalysis:true};let body;const model={key:'test',model:'test',fetchImpl:async(_,options)=>{body=JSON.parse(options.body);return {ok:true,json:async()=>({output:[{type:'function_call',name:'analyze_audio_melody',arguments:JSON.stringify({operation:'createMidi',regionId:null,settings})}]})};}};const result=await planDawEdit(input,model);assert.equal(result.action,'analyze_audio_melody');assert.equal(result.analysis.regionId,'r');assert.deepEqual(result.commands,[]);assert.equal(result.analysis.notes,undefined);assert.equal(body.tools.find(t=>t.name==='analyze_audio_melody').parameters.properties.settings.required.length,4);for(const override of [{allowMelodyAnalysis:false},{editingContinuation:true},{selection:undefined}])await assert.rejects(planDawEdit({...input,...override},model));assert.throws(()=>prepareMelodyAnalysis(h.session,{operation:'preview',regionId:'missing',settings}));});

test('harmonic-rich notes track the fundamental and retain measured detuning',()=>{const rate=44100,c=new Float32Array(rate),hz=220*2**(.2/12);for(let i=0;i<c.length;i++){const phase=2*Math.PI*hz*i/rate;c[i]=.2*Math.sin(phase)+.25*Math.sin(2*phase)+.1*Math.sin(3*phase);}const notes=detectMelody([c],rate);assert.equal(notes.length,1);assert.equal(notes[0].pitch,57);assert.ok(Math.abs(notes[0].cents-20)<5);});
