import test from 'node:test';import assert from 'node:assert/strict';
import {scheduleMetronome,scheduleRecordingClick} from '../src/experimental/metronome.js';
import {recordingTiming} from '../src/experimental/recording-timing.js';
const fixture=()=>({tempo:120,meter:4,tempoChanges:[{beat:8,bpm:60},{beat:12,bpm:180}],metronomeEnabled:true});
function context(){const buffers=[],sources=[];return {sampleRate:8000,currentTime:0,destination:{},buffers,sources,createBuffer(channels,length,rate){const data=new Float32Array(length),buffer={length,duration:length/rate,getChannelData:()=>data};buffers.push(buffer);return buffer;},createGain(){return {gain:{},connect(){return this;},disconnect(){}};},createBufferSource(){const source={playbackRate:{},connect(){return this;},disconnect(){this.disconnected=true;},start(...args){this.started=args;},stop(time){this.stopped=time;}};sources.push(source);return source;}};}
test('tempo segments share two pulse buffers and retain bar accents',()=>{const c=context(),handle=scheduleMetronome(c,fixture(),{baseTime:0,duration:10});assert.equal(c.buffers.length,2);assert.equal(c.sources.length,6);assert.deepEqual(c.sources.map(s=>s.started[0]),[0,0,4,4,8,8]);assert.deepEqual(c.sources.map(s=>s.loopEnd),[.5,2,1,4,.333375,1.333375]);handle.stop();handle.stop();assert.ok(c.sources.every(s=>s.disconnected));});
test('seek into a click retains its tail without starting a duplicate beat',()=>{const c=context();scheduleMetronome(c,fixture(),{position:4.01,baseTime:2,duration:1});const tails=c.sources.filter(s=>!s.loop);assert.equal(tails.length,2);for(const tail of tails){assert.equal(tail.started[0],2);assert.ok(Math.abs(tail.started[1]-.01)<1e-10);}assert.equal(c.sources.filter(s=>s.loop).length,1);assert.ok(Math.abs(c.sources.at(-1).started[0]-2.99)<1e-10);});
test('long mapped playback schedules by tempo segment rather than by beat',()=>{const c=context(),s={...fixture(),tempoChanges:Array.from({length:256},(_,i)=>({beat:(i+1)*8,bpm:60+i%180}))};scheduleMetronome(c,s,{baseTime:0,duration:86400});assert.equal(c.buffers.length,2);assert.ok(c.sources.length<=514);assert.ok(c.buffers.reduce((n,b)=>n+b.length,0)<=8000*5);});
test('count-in walks backward in beats from recording position across tempo changes',()=>{const s={...fixture(),countInBars:1};assert.equal(recordingTiming(s,0,48000,5).countInSeconds,2.5);assert.equal(recordingTiming(s,0,48000,1).countInSeconds,2);const timing=recordingTiming(s,0,48000,5),c=context();scheduleRecordingClick(c,s,5,timing);assert.ok(c.sources.every(source=>source.stopped<=timing.captureTime));assert.equal(c.sources[0].started[0],timing.clickTime);});
