import test from 'node:test';import assert from 'node:assert/strict';
import {newSession,applyCommands,sessionSchema,SessionHistory} from '../src/experimental/session.js';
const fixture=()=>applyCommands(newSession(),[{op:'track.add',values:{id:'t'}},{op:'region.add',target:'t',values:{id:'a',assetId:'one',duration:4}},{op:'region.add',target:'t',values:{id:'b',assetId:'two',duration:4}}]);
const segments=[{regionId:'a',start:0,end:1},{regionId:'b',start:1,end:3}],save=(values={})=>({op:'comp.save',target:'t',values:{id:'choice',name:'First choice',segments:JSON.stringify(segments),...values}});
test('named alternatives save, update, restore, create and delete through atomic undoable commands',()=>{
 const h=new SessionHistory(fixture()),before=structuredClone(h.session);h.execute([save()]);assert.equal(h.session.tracks.length,1);assert.deepEqual(h.session.tracks[0].regions,before.tracks[0].regions);assert.equal(h.session.tracks[0].mute,false);assert.deepEqual(h.session.tracks[0].compAlternatives[0],{id:'choice',name:'First choice',segments,edgeFade:.005,muteSource:true});
 const restored=sessionSchema.parse(JSON.parse(JSON.stringify(h.session)));assert.deepEqual(restored.tracks[0].compAlternatives,h.session.tracks[0].compAlternatives);
 h.execute([save({name:'Revised',edgeFade:.02,muteSource:false})]);assert.equal(h.session.tracks[0].compAlternatives.length,1);h.undo();assert.equal(h.session.tracks[0].compAlternatives[0].name,'First choice');h.redo();assert.equal(h.session.tracks[0].compAlternatives[0].name,'Revised');
 h.execute([{op:'comp.createTrack',target:'t',values:{compId:'choice'}}]);assert.equal(h.session.tracks.length,2);assert.equal(h.session.tracks[0].mute,false);assert.equal(h.session.tracks[1].name,'Revised');assert.equal(h.session.tracks[1].compAlternatives.length,0);assert.deepEqual(h.session.tracks[1].regions.map(r=>[r.assetId,r.start,r.duration]),[['one',0,1],['two',1,2]]);h.undo();
 h.execute([{op:'comp.delete',target:'t',values:{compId:'choice'}}]);assert.equal(h.session.tracks[0].compAlternatives.length,0);h.undo();assert.equal(h.session.tracks[0].compAlternatives.length,1);
});
test('alternatives enforce names, identities, boundaries, capacity and missing references without destroying saved choices',()=>{
 const s=applyCommands(fixture(),[save()]);for(const cmd of [save({name:' '}),save({id:'a'}),save({segments:'[]'}),save({segments:JSON.stringify([{regionId:'a',start:0,end:3},{regionId:'b',start:2,end:4}])}),{op:'comp.delete',target:'t',values:{compId:'missing'}},{op:'comp.createTrack',target:'t',values:{compId:'missing'}}]){const before=structuredClone(s);assert.throws(()=>applyCommands(s,[cmd]));assert.deepEqual(s,before);}
 const removed=applyCommands(s,[{op:'region.delete',target:'a'}]);assert.equal(removed.tracks[0].compAlternatives.length,1);assert.throws(()=>applyCommands(removed,[{op:'comp.createTrack',target:'t',values:{compId:'choice'}}]),/existing audio/);assert.equal(applyCommands(removed,[{op:'comp.delete',target:'t',values:{compId:'choice'}}]).tracks[0].compAlternatives.length,0);
 const moved=applyCommands(s,[{op:'region.set',target:'a',values:{start:10}}]);assert.throws(()=>applyCommands(moved,[{op:'comp.createTrack',target:'t',values:{compId:'choice'}}]),/fit within/);
 let full=fixture();for(let i=0;i<32;i++)full=applyCommands(full,[save({id:'c'+i})]);assert.throws(()=>applyCommands(full,[save()]),/32/);assert.equal(applyCommands(full,[save({id:'c0',name:'Updated'})]).tracks[0].compAlternatives[0].name,'Updated');
 const crowded=fixture();while(crowded.tracks.length<128)crowded.tracks.push({...structuredClone(crowded.tracks[0]),id:'t'+crowded.tracks.length,regions:[]});const saved=applyCommands(crowded,[save()]);assert.equal(saved.tracks[0].compAlternatives.length,1);assert.throws(()=>applyCommands(saved,[{op:'comp.createTrack',target:'t',values:{compId:'choice'}}]),/space/);
});
test('duplicated tracks remap alternative identities and source-region references; settings-only copies omit alternatives',()=>{
 const s=applyCommands(fixture(),[save()]),copy=applyCommands(s,[{op:'track.duplicate',target:'t',values:{id:'copy'}}]),t=copy.tracks.find(t=>t.id==='copy'),c=t.compAlternatives[0];assert.notEqual(c.id,'choice');assert.deepEqual(c.segments.map(s=>s.regionId),t.regions.map(r=>r.id));assert.deepEqual(s.tracks[0].compAlternatives[0].segments,segments);const created=applyCommands(copy,[{op:'comp.createTrack',target:'copy',values:{compId:c.id}}]);assert.equal(created.tracks.length,3);
 const settings=applyCommands(s,[{op:'track.duplicate',target:'t',values:{includeRegions:false,id:'settings'}}]);assert.equal(settings.tracks.find(t=>t.id==='settings').compAlternatives.length,0);
});
test('portable archives retain named choices while remapping their referenced source media',async()=>{
 const {exportArchive,importArchive}=await import('../src/experimental/archive.js');const s=applyCommands(fixture(),[save()]),files=new Map([['one',new File(['one'],'one.wav')],['two',new File(['two'],'two.wav')]]),archive=await exportArchive(s,files),restored=await importArchive(await archive.arrayBuffer());assert.deepEqual(restored.session.tracks[0].compAlternatives,s.tracks[0].compAlternatives);assert.notEqual(restored.session.tracks[0].regions[0].assetId,'one');const result=applyCommands(restored.session,[{op:'comp.createTrack',target:'t',values:{compId:'choice'}}]);assert.deepEqual(result.tracks[1].regions.map(r=>r.assetId),restored.session.tracks[0].regions.map(r=>r.assetId));
});
test('agent receives named alternatives, validates their commands and records real save deltas',async()=>{
 const {planDawEdit}=await import('../server/daw-agent.js'),{conversationTurn}=await import('../src/experimental/agent-conversation.js');const before=fixture(),saved=applyCommands(before,[save()]);let request;const result=await planDawEdit({session:saved,instruction:'Create a track from First choice'},{key:'test',model:'test',fetchImpl:async(_,options)=>{request=JSON.parse(options.body);return {ok:true,json:async()=>({output:[{type:'function_call',name:'edit_session',arguments:JSON.stringify({summary:'Create saved comp',commands:[{op:'comp.createTrack',target:'t',values:{compId:'choice'}}]})}]})};}});assert.equal(JSON.parse(request.input.at(-1).content).session.tracks[0].compAlternatives[0].id,'choice');assert.equal(applyCommands(saved,result.commands,result.revision).tracks[1].name,'First choice');const turn=conversationTurn({before,after:saved,instruction:'Save first choice',summary:'Saved',outcome:'applied'});assert.equal(turn.changes[0].entity,'comp alternative');assert.equal(turn.changes[0].after.name,'First choice');assert.equal(turn.changes[0].after.segments,JSON.stringify(segments));
});
