import test from 'node:test';import assert from 'node:assert/strict';import {SessionHistory} from '../src/experimental/session.js';
import {midiSeparationGroups} from '../src/experimental/separate-midi.js';
const fixture=()=>{const h=new SessionHistory();h.execute([{op:'track.add',values:{id:'t',name:'Kit',kind:'midi',instrument:'drumKit'}},{op:'region.add',target:'t',values:{id:'r',name:'Beat',start:2,duration:4}},...[36,38,36,42].map((pitch,i)=>({op:'note.add',target:'r',values:{id:'n'+i,pitch,start:i/2,duration:.2,velocity:.7,channel:9}})),{op:'event.add',target:'r',values:{id:'cc',type:'controlChange',parameter:11,value:70,start:0,channel:9}},{op:'event.add',target:'r',values:{id:'pp',type:'polyPressure',parameter:36,value:80,start:0,channel:9}},{op:'event.add',target:'r',values:{id:'other',type:'programChange',value:4,start:0,channel:2}},{op:'region.add',target:'t',values:{id:'untouched',start:8,duration:1}}]);return h;};
const withoutIds=items=>items.map(({id,...rest})=>rest);
test('pitch separation keeps source muted, clones independent regions in order and restores with one undo',()=>{const h=fixture(),before=structuredClone(h.session);h.execute([{op:'region.separateMidi',target:'r',values:{by:'pitch'}}]);assert.equal(h.session.tracks.length,4);assert.deepEqual(h.session.tracks[0],{...before.tracks[0],regions:before.tracks[0].regions.map(r=>r.id==='r'?{...r,mute:true}:r)});
 for(const [i,pitch]of [36,38,42].entries()){const t=h.session.tracks[i+1],r=t.regions[0];assert.equal(t.instrument,'drumKit');assert.equal(r.start,2);assert.equal(r.duration,4);assert.equal(r.mute,false);assert.deepEqual(withoutIds(r.notes),withoutIds(before.tracks[0].regions[0].notes.filter(n=>n.pitch===pitch)));assert.ok(r.events.some(e=>e.type==='controlChange'));assert.equal(r.events.some(e=>e.type==='polyPressure'),pitch===36);assert.ok(!r.events.some(e=>e.channel===2));assert.notEqual(r.id,'r');assert.ok(r.notes.every(n=>!before.tracks[0].regions[0].notes.some(o=>o.id===n.id)));}
 h.undo();assert.deepEqual(h.session.tracks,before.tracks);h.redo();assert.equal(h.session.tracks.length,4);
});
test('channel separation keeps event-only channels and all event types on their original channel',()=>{const h=fixture();h.execute([{op:'region.separateMidi',target:'r',values:{by:'channel'}}]);assert.equal(h.session.tracks.length,3);assert.equal(h.session.tracks[1].regions[0].notes.length,0);assert.equal(h.session.tracks[1].regions[0].events[0].channel,2);assert.equal(h.session.tracks[2].regions[0].notes.length,4);assert.equal(h.session.tracks[2].regions[0].events.length,2);});
test('copies retain routing, sampler references, automation and effects with fresh IDs',()=>{const h=fixture();h.execute([{op:'track.add',values:{id:'bus',kind:'bus'}},{op:'track.set',target:'t',values:{instrument:'sampler',sampleAssetId:'asset',output:'bus',mute:true,solo:true}},{op:'effect.add',target:'t',values:{id:'fx',kind:'gain',gainDb:-3}},{op:'automation.point',target:'t',values:{id:'auto',parameter:'pan',time:0,value:.2}},{op:'send.set',target:'t',values:{busId:'bus',gainDb:-9}}]);h.execute([{op:'region.separateMidi',target:'r'}]);for(const t of h.session.tracks.slice(1,4)){assert.equal(t.sampleAssetId,'asset');assert.equal(t.output,'bus');assert.equal(t.mute,true);assert.equal(t.solo,true);assert.equal(t.effects[0].gainDb,-3);assert.notEqual(t.effects[0].id,'fx');assert.notEqual(t.automation[0].id,'auto');assert.equal(t.sends[0].busId,'bus');}});
test('invalid modes, empty regions and track limits fail atomically',()=>{const h=fixture(),before=structuredClone(h.session);assert.throws(()=>h.execute([{op:'region.separateMidi',target:'r',values:{by:'audio'}}]));assert.throws(()=>h.execute([{op:'region.separateMidi',target:'untouched'}]),/Add notes/);assert.deepEqual(h.session,before);assert.throws(()=>midiSeparationGroups({kind:'audio'},null),/MIDI/);for(let i=0;i<125;i++)h.execute([{op:'track.add',values:{id:'extra'+i}}]);const full=structuredClone(h.session);assert.throws(()=>h.execute([{op:'region.separateMidi',target:'r'}]),/128-track/);assert.deepEqual(h.session,full);});
