import test from 'node:test';import assert from 'node:assert/strict';
import {legatoEdits} from '../src/experimental/legato.js';import {newSession,SessionHistory} from '../src/experimental/session.js';import {writeMidi,readMidi} from '../src/experimental/midi.js';
const region=()=>({duration:8,notes:[{id:'a',pitch:60,start:0,duration:.2,velocity:.5,channel:0},{id:'chord',pitch:64,start:0,duration:.3,velocity:.7,channel:0},{id:'b',pitch:62,start:1,duration:.2,velocity:.6,channel:0},{id:'c',pitch:60,start:3,duration:.5,velocity:1,channel:0},{id:'other',pitch:60,start:.5,duration:.2,velocity:.6,channel:1}]});
const lengths=edits=>Object.fromEntries(edits.map(e=>[e.id,e.duration]));
test('legato connects simultaneous chord notes to the next distinct onset without crossing MIDI channels',()=>{const r=region(),before=structuredClone(r);assert.deepEqual(lengths(legatoEdits(r)),{a:1,chord:1,b:2,c:.5,other:.2});assert.deepEqual(r,before);assert.deepEqual(lengths(legatoEdits(r,{last:'regionEnd'})),{a:1,chord:1,b:2,c:5,other:7.5});});
test('legato selection controls changed notes and following boundaries independently, including same-pitch matching',()=>{const r=region();assert.deepEqual(lengths(legatoEdits(r,{noteIds:'a,c'})),{a:1,c:.5});assert.deepEqual(lengths(legatoEdits(r,{noteIds:'a,c',following:'selected'})),{a:3,c:.5});assert.deepEqual(lengths(legatoEdits(r,{match:'pitch'})),{a:3,chord:.3,b:.2,c:.5,other:.2});assert.deepEqual(lengths(legatoEdits(r,{noteId:'a',following:'selected'})),{a:.2});assert.throws(()=>legatoEdits(r,{noteIds:''}));assert.throws(()=>legatoEdits(r,{noteIds:'a',noteId:'a'}));assert.throws(()=>legatoEdits(r,{noteIds:'absent'}));});
test('gaps, overlaps, last-note policy and shorten-only mode preserve bounds and unrelated note properties',()=>{const r=region();assert.equal(lengths(legatoEdits(r,{gap:.1})).a,.9);assert.equal(lengths(legatoEdits(r,{gap:-.1})).a,1.1);assert.equal(lengths(legatoEdits(r,{gap:-10})).a,8);r.notes[0].duration=2;assert.equal(lengths(legatoEdits(r,{mode:'shorten'})).a,1);assert.equal(lengths(legatoEdits(r,{mode:'shorten'})).b,.2);assert.equal(lengths(legatoEdits(r,{mode:'shorten',last:'regionEnd'})).c,.5);assert.equal(lengths(legatoEdits(r,{gap:.1,last:'regionEnd'})).c,5);assert.throws(()=>legatoEdits(r,{gap:1}));assert.throws(()=>legatoEdits(r,{gap:Infinity}));assert.throws(()=>legatoEdits(r,{mode:'weird'}));assert.throws(()=>legatoEdits({...r,duration:5000},{noteId:'c',last:'regionEnd'}));});
test('shared legato commands are atomic, undoable and survive MIDI export',()=>{const h=new SessionHistory(newSession());h.execute([{op:'track.add',values:{id:'t',kind:'midi'}},{op:'region.add',target:'t',values:{id:'r',duration:8}},...region().notes.map(n=>({op:'note.add',target:'r',values:n}))]);const before=structuredClone(h.session);h.execute([{op:'notes.legato',target:'r',values:{gap:.1}}]);for(const [i,n]of h.session.tracks[0].regions[0].notes.entries())for(const key of ['id','start','pitch','velocity','channel'])assert.equal(n[key],before.tracks[0].regions[0].notes[i][key]);const midi=readMidi(writeMidi(h.session).buffer);assert.ok(midi.tracks.flatMap(t=>t.notes).some(n=>n.pitch===60&&n.channel===0&&Math.abs(n.duration-.9)<.002));h.undo();assert.deepEqual(h.session.tracks,before.tracks);h.redo();assert.equal(h.session.tracks[0].regions[0].notes[0].duration,.9);const saved=structuredClone(h.session);assert.throws(()=>h.execute([{op:'notes.legato',target:'r',values:{}},{op:'notes.legato',target:'r',values:{gap:10}}]));assert.deepEqual(h.session,saved);});
test('large unsorted selections use the next onset and preserve their original order',()=>{const r={duration:20000,notes:Array.from({length:20000},(_,i)=>({id:'n'+i,pitch:60,channel:0,start:19999-i,duration:.25}))};const edits=legatoEdits(r);assert.equal(edits.length,20000);assert.equal(edits[0].id,'n0');assert.equal(edits[0].duration,.25);assert.ok(edits.slice(1).every(e=>e.duration===1));});
test('musical gaps integrate backward from each next onset across tempo boundaries',()=>{
 const r={start:0,duration:8,notes:[{id:'a',start:0,duration:.2},{id:'b',start:3,duration:.2},{id:'c',start:4.25,duration:.2}]},timing={tempo:120,tempoChanges:[{beat:8,bpm:60}]};
 const edits=lengths(legatoEdits(r,{timing:'beats',gap:1},timing));assert.equal(edits.a,2.5);assert.equal(edits.b,.625);assert.equal(edits.c,.2);
 const overlap=lengths(legatoEdits(r,{timing:'beats',gap:-1},timing));assert.equal(overlap.a,3.5);assert.equal(overlap.b,2.25);
 assert.equal(lengths(legatoEdits(r,{timing:'beats',gap:1,last:'regionEnd'},timing)).c,3.75);
 assert.equal(lengths(legatoEdits(r,{timing:'beats',gap:1,mode:'shorten'},timing)).b,.2);
 assert.throws(()=>legatoEdits(r,{timing:'beats',gap:3},timing),/zero-length/);
 assert.throws(()=>legatoEdits(r,{timing:'beats'}),/session timing/);
});
test('musical legato commands preserve controllers and note metadata, protection and undo',()=>{
 const h=new SessionHistory(newSession());h.execute([{op:'track.add',values:{id:'t',kind:'midi'}},{op:'region.add',target:'t',values:{id:'r',duration:8}},...region().notes.map(n=>({op:'note.add',target:'r',values:n})),{op:'tempo.add',values:{beat:4,bpm:60}}]);
 const before=structuredClone(h.session);h.execute([{op:'notes.legato',target:'r',values:{timing:'beats',gap:.25,noteIds:'a,b'}}]);
 const notes=h.session.tracks[0].regions[0].notes;assert.equal(notes[0].duration,.875);assert.equal(notes.find(n=>n.id==='b').duration,2.75);
 assert.deepEqual(notes.find(n=>n.id==='c'),before.tracks[0].regions[0].notes.find(n=>n.id==='c'));h.undo();assert.deepEqual(h.session.tracks,before.tracks);
 assert.throws(()=>h.execute([{op:'track.set',target:'t',values:{protected:true}},{op:'notes.legato',target:'r',values:{timing:'beats',gap:.25}}]),/Unprotect/);
});
