import test from 'node:test';import assert from 'node:assert/strict';import {SessionHistory} from '../src/experimental/session.js';import {batchNormalizationPlan,normalizationSelection} from '../src/experimental/region-normalization-batch.js';
const setup=()=>{const h=new SessionHistory();h.execute([{op:'track.add',values:{id:'a',kind:'audio'}},{op:'track.add',values:{id:'b',kind:'audio'}},{op:'region.add',target:'a',values:{id:'one',assetId:'source1',duration:2}},{op:'region.add',target:'b',values:{id:'two',assetId:'source2',duration:6}},{op:'region.set',target:'one',values:{gainDb:-3}},{op:'region.set',target:'two',values:{gainDb:2}}]);return h;};
const levels=h=>['one','two'].map((regionId,i)=>({regionId,sessionId:h.session.id,revision:h.session.revision,peakDb:-10-i*10,rmsDb:-13-i*10}));
const settings={grouping:'selection',mode:'peak',targetDb:-6,ceilingDb:-1};
test('shared normalization preserves relative gain and commits all changes with one undo',()=>{const h=setup(),before=structuredClone(h.session),plan=batchNormalizationPlan(h.session,levels(h),settings);assert.deepEqual(plan.plans.map(p=>p.gainDb),[4,9]);assert.deepEqual(plan.plans.map(p=>p.deltaDb),[7,7]);h.execute(plan.commands);assert.equal(h.session.tracks[1].regions[0].gainDb-h.session.tracks[0].regions[0].gainDb,5);h.undo();assert.deepEqual(h.session.tracks,before.tracks);});
test('individual and per-track grouping have independent gain targets',()=>{const h=setup(),v={...settings,targetDb:-8};for(const grouping of ['individual','tracks'])assert.deepEqual(batchNormalizationPlan(h.session,levels(h),{...v,grouping}).plans.map(p=>p.gainDb),[2,12]);});
test('shared RMS weights duration, includes existing gain, and honors the group peak ceiling',()=>{const h=setup(),ms=levels(h),rms=10*Math.log10((2*10**(-16/10)+6*10**(-21/10))/8),p=batchNormalizationPlan(h.session,ms,{...settings,mode:'rms',targetDb:-18});assert.ok(Math.abs(p.plans[0].deltaDb-(-18-rms))<1e-9);const limited=batchNormalizationPlan(h.session,ms,{...settings,mode:'rms',targetDb:0,ceilingDb:-8});assert.equal(limited.plans[0].deltaDb,5);assert.ok(limited.plans.every(p=>p.limited));});
test('batch normalization rejects partial invalidity, duplicate/stale measurements, and skips silent individual regions',()=>{const h=setup(),ms=levels(h);assert.throws(()=>batchNormalizationPlan(h.session,[ms[0],ms[0]],settings));assert.throws(()=>batchNormalizationPlan(h.session,[ms[0],{...ms[1],revision:0}],settings));assert.throws(()=>batchNormalizationPlan(h.session,ms,{...settings,targetDb:0}),/outside/);assert.equal(batchNormalizationPlan(h.session,ms.map(m=>({...m,peakDb:null,rmsDb:null})),{...settings,grouping:'individual'}).commands.length,0);h.execute([{op:'track.set',target:'b',values:{protected:true}}]);assert.throws(()=>normalizationSelection(h.session,['one','two']),/protect/i);});

test('agent batch normalization resolves captured selections and gates tools without inventing levels',async()=>{const {planDawEdit}=await import('../server/daw-agent.js'),{defaultBounceSettings}=await import('../src/experimental/bounce-settings.js'),h=setup(),input={session:h.session,instruction:'Normalize selected audio',allowRegionNormalization:true,selectedRegionIds:['one','two'],exportContext:{sessionId:h.session.id,revision:h.session.revision,regionId:'one',settings:defaultBounceSettings}},action={operation:'apply',regionIds:null,settings};let body;const adapter=args=>({key:'test',model:'test',fetchImpl:async(_,options)=>{body=JSON.parse(options.body);return {ok:true,json:async()=>({output:[{type:'function_call',name:'normalize_audio_regions',arguments:JSON.stringify(args)}]})};}});const result=await planDawEdit(input,adapter(action));assert.deepEqual(result.normalization.regionIds,['one','two']);assert.equal(result.action,'normalize_audio_regions');assert.deepEqual(result.commands,[]);assert.equal(body.tools.find(t=>t.name==='normalize_audio_regions').strict,true);await assert.rejects(planDawEdit({...input,allowRegionNormalization:false},adapter(action)));await assert.rejects(planDawEdit({...input,editingContinuation:true},adapter(action)));await assert.rejects(planDawEdit(input,adapter({...action,regionIds:['one','one']})));await assert.rejects(planDawEdit(input,adapter({...action,settings:{...settings,grouping:'mix'}})));});
