import test from 'node:test';import assert from 'node:assert/strict';
import {SessionHistory} from '../src/experimental/session.js';import {writeMidi,readMidi} from '../src/experimental/midi.js';import {midiOutputPlan} from '../src/experimental/midi-output-plan.js';import {planDawEdit} from '../server/daw-agent.js';
const setup=()=>{const h=new SessionHistory();h.execute([{op:'track.add',values:{id:'t',kind:'midi'}},{op:'region.add',target:'t',values:{id:'r',duration:2}},{op:'note.add',target:'r',values:{id:'music',pitch:60,start:.5,duration:1}}]);return h;};
const preset={id:'staccato',name:'Staccato',type:'keyswitch',channel:0,parameter:24,value:100,duration:.05};
test('saved keyswitches insert independent notes, reach MIDI export/device playback before equal-time musical notes, and undo',()=>{
 const h=setup();h.execute([{op:'midiSwitch.save',target:'t',values:preset}]);const before=structuredClone(h.session),music=structuredClone(h.session.tracks[0].regions[0].notes[0]);h.execute([{op:'midiSwitch.insert',target:'r',values:{id:'staccato',start:.5}}]);const r=h.session.tracks[0].regions[0];assert.deepEqual(r.notes.find(n=>n.id==='music'),music);assert.equal(r.notes[0].pitch,24);
 const output=midiOutputPlan(h.session,'t'),ons=output.messages.filter(m=>m.time===.5&&(m.bytes[0]&240)===144);assert.deepEqual(ons.map(m=>m.bytes[1]),[24,60]);const parsed=readMidi(writeMidi(h.session).buffer);assert.ok(parsed.tracks[0].notes.some(n=>n.pitch===24&&Math.abs(n.start-.5)<1e-6));h.undo();assert.deepEqual(h.session,{...before,revision:h.session.revision});h.redo();assert.equal(h.session.tracks[0].regions[0].notes.length,2);
 h.execute([{op:'midiSwitch.delete',target:'t',values:{id:'staccato'}}]);assert.equal(h.session.tracks[0].regions[0].notes.length,2);
});
test('controller and program switches precede note-ons and are chased by hardware playback',()=>{
 const h=setup();for(const p of [{...preset,id:'cc',type:'controlChange',parameter:1,value:64},{...preset,id:'program',type:'programChange',parameter:0,value:3}])h.execute([{op:'midiSwitch.save',target:'t',values:p},{op:'midiSwitch.insert',target:'r',values:{id:p.id,start:.25}}]);const plan=midiOutputPlan(h.session,'t',.5);assert.ok(plan.messages.some(m=>m.time===.5&&m.bytes.join(',')==='176,1,64'));assert.ok(plan.messages.some(m=>m.time===.5&&m.bytes.join(',')==='192,3'));const parsed=readMidi(writeMidi(h.session).buffer);assert.equal(parsed.tracks[0].events.filter(e=>e.start===.25).length,2);
 const before=structuredClone(h.session);assert.throws(()=>h.execute([{op:'midiSwitch.insert',target:'r',values:{id:'cc',start:.25}}]),/already/);assert.deepEqual(h.session,before);
});
test('switch presets validate mappings, region bounds, protected content and note collisions',()=>{
 const h=setup();for(const patch of [{value:0},{channel:16},{parameter:128},{duration:0},{name:''},{extra:1}])assert.throws(()=>h.execute([{op:'midiSwitch.save',target:'t',values:{...preset,...patch}}]));h.execute([{op:'midiSwitch.save',target:'t',values:{...preset,parameter:60}}]);assert.throws(()=>h.execute([{op:'midiSwitch.insert',target:'r',values:{id:'staccato',start:.5}}]),/overlap/);for(const start of [-1,2])assert.throws(()=>h.execute([{op:'midiSwitch.insert',target:'r',values:{id:'staccato',start}}]));h.execute([{op:'track.set',target:'t',values:{protected:true}}]);assert.throws(()=>h.execute([{op:'midiSwitch.insert',target:'r',values:{id:'staccato',start:0}}]));
});
test('agent saves and inserts a user-supplied library mapping in one validated batch',async()=>{
 const h=setup();const commands=[{op:'midiSwitch.save',target:'t',values:preset},{op:'midiSwitch.insert',target:'r',values:{id:'staccato',start:0}}],result=await planDawEdit({session:h.session,instruction:'My staccato is MIDI note 24 channel 1 velocity 100. Save that switch and insert it at region start.'},{key:'test',model:'test',fetchImpl:async()=>({ok:true,json:async()=>({output:[{type:'function_call',name:'edit_session',arguments:JSON.stringify({summary:'Added the supplied switch',commands})}]})})});h.execute(result.commands,result.revision);assert.equal(h.session.tracks[0].midiSwitches[0].name,'Staccato');assert.equal(h.session.tracks[0].regions[0].notes[0].pitch,24);h.undo();assert.equal(h.session.tracks[0].midiSwitches,undefined);
});
test('instrument setting copies preserve independent switches and clear them for an unmapped source',()=>{
 const h=setup();h.execute([{op:'track.add',values:{id:'other',kind:'midi'}},{op:'midiSwitch.save',target:'t',values:preset},{op:'track.copySettings',target:'other',values:{sourceId:'t',instrument:true}}]);assert.deepEqual(h.session.tracks[1].midiSwitches,h.session.tracks[0].midiSwitches);h.execute([{op:'midiSwitch.delete',target:'t',values:{id:'staccato'}}]);assert.equal(h.session.tracks[1].midiSwitches.length,1);h.execute([{op:'track.copySettings',target:'other',values:{sourceId:'t',instrument:true}}]);assert.equal(h.session.tracks[1].midiSwitches.length,0);h.execute([{op:'track.add',values:{id:'clean',kind:'midi'}},{op:'midiSwitch.save',target:'other',values:preset},{op:'track.copySettings',target:'other',values:{sourceId:'clean',instrument:true}}]);assert.equal(h.session.tracks[1].midiSwitches,undefined);
});
