import test from 'node:test';import assert from 'node:assert/strict';import {joinNotesPlan} from '../src/experimental/note-join.js';import {duplicateNotePlan} from '../src/experimental/note-cleanup.js';import {arpeggioPlan} from '../src/experimental/arpeggio.js';import {SessionHistory} from '../src/experimental/session.js';import {articulationIdentity} from '../src/experimental/articulation-identity.js';
const a={id:'a',name:'Sustain',type:'keyswitch',channel:0,parameter:24,value:100,duration:.05},b={...a,id:'b',name:'Pluck',parameter:25},note=(id,start,articulation=a)=>({id,pitch:60,channel:0,start,duration:1,velocity:.8,mute:false,...(articulation?{articulation}:{})});
test('join stops at technique changes even across a permitted gap; equivalent renamed snapshots still join',()=>{
 const region={notes:[note('n0',0),note('n1',1,b),note('n2',2)]};assert.deepEqual(joinNotesPlan(region,{gap:10}).removedIds,[]);region.notes[1].articulation={...a,name:'Renamed'};assert.deepEqual(joinNotesPlan(region).removedIds,['n1','n2']);region.notes[1].articulation={...a,value:80};assert.equal(joinNotesPlan(region,{gap:10}).removedIds.length,0);assert.equal(articulationIdentity(a),articulationIdentity({...a,name:'Renamed'}));assert.notEqual(articulationIdentity(a),articulationIdentity({...a,id:'another'}));
});
test('duplicate cleanup preserves differing articulation sound and assignment identities in both modes',()=>{
 const notes=[note('original',0),note('renamed',0,{...a,name:'Renamed'}),note('other',0,b),note('edited',0,{...a,parameter:26}),note('plain',0,null)];for(const match of ['onset','identical'])assert.deepEqual(duplicateNotePlan({notes},{match}).removedIds,['renamed']);
});
test('arpeggio copies source articulation per generated pitch with independent snapshots',()=>{
 const region={duration:2,notes:[{...note('n0',0),duration:2},{...note('n1',0,b),pitch:64,duration:2}]},plan=arpeggioPlan(region,120,{rate:.5,order:'up'});assert.ok(plan.notes.length>2);for(const n of plan.notes)assert.deepEqual(n.articulation,n.pitch===60?a:b);plan.notes[0].articulation.name='Edited result';assert.equal(region.notes[0].articulation.name,'Sustain');assert.equal(plan.notes[2].articulation.name,'Sustain');
});
test('shared editing commands retain articulations through split, repeat, arpeggio and Undo',()=>{
 const h=new SessionHistory();h.execute([{op:'track.add',values:{id:'t',kind:'midi'}},{op:'region.add',target:'t',values:{id:'r',duration:4}},{op:'note.add',target:'r',values:{id:'n',pitch:60,duration:2}},{op:'midiSwitch.save',target:'t',values:a},{op:'notes.articulation',target:'r',values:{id:'a',noteIds:'n'}}]);const before=structuredClone(h.session);for(const command of [{op:'notes.arpeggiate',target:'r',values:{rate:.5}},{op:'notes.split',target:'r',values:{time:1}},{op:'notes.repeat',target:'r',values:{count:1,seconds:2}}]){h.execute([command]);assert.ok(h.session.tracks[0].regions[0].notes.length>1);assert.ok(h.session.tracks[0].regions[0].notes.every(n=>n.articulation?.id==='a'));h.undo();assert.deepEqual(h.session,{...before,revision:h.session.revision});}
});
