import test from 'node:test';import assert from 'node:assert/strict';import {SessionHistory} from '../src/experimental/session.js';import {validateAudioRangeContext} from '../src/experimental/region-split-range.js';
const setup=reverse=>{const h=new SessionHistory();h.execute([{op:'track.add',values:{id:'audio',kind:'audio'}},{op:'region.add',target:'audio',values:{id:'clip',assetId:'source',start:10,offset:5,duration:4}},{op:'region.set',target:'clip',values:{reverse,fadeIn:.2,fadeOut:.3}}]);return h;};
test('range split isolates middle audio while preserving forward/reversed source coverage and undo',()=>{for(const reverse of [false,true]){const h=setup(reverse),before=structuredClone(h.session);h.execute([{op:'region.splitRange',target:'clip',values:{start:11,end:13}}]);const pieces=[...h.session.tracks[0].regions].sort((a,b)=>a.start-b.start);assert.deepEqual(pieces.map(r=>[r.start,r.duration,r.offset]),reverse?[[10,1,8],[11,2,6],[13,1,5]]:[[10,1,5],[11,2,6],[13,1,8]]);assert.deepEqual(pieces.map(r=>[r.fadeIn,r.fadeOut]),[[.2,0],[0,0],[0,.3]]);assert.ok(pieces.every(r=>r.assetId==='source'&&r.reverse===reverse));h.undo();assert.deepEqual(h.session.tracks,before.tracks);}});
test('range split at one original edge creates only two pieces and rejects invalid ranges atomically',()=>{const h=setup(false),before=structuredClone(h.session);for(const values of [{start:10,end:14},{start:9,end:12},{start:12,end:15},{start:12,end:12}])assert.throws(()=>h.execute([{op:'region.splitRange',target:'clip',values}]));assert.deepEqual(h.session,before);h.execute([{op:'region.splitRange',target:'clip',values:{start:10,end:12}}]);assert.equal(h.session.tracks[0].regions.length,2);h.undo();h.execute([{op:'track.set',target:'audio',values:{protected:true}}]);assert.throws(()=>h.execute([{op:'region.splitRange',target:'clip',values:{start:11,end:13}}]),/protect/i);});
test('agent audio range context validates current source bounds',()=>{const h=setup(false),range={regionId:'clip',start:11,end:13};assert.deepEqual(validateAudioRangeContext(h.session,range),range);for(const changed of [{regionId:'missing'},{start:9},{end:15},{end:11}])assert.throws(()=>validateAudioRangeContext(h.session,{...range,...changed}));});

test('agent receives captured waveform bounds and uses the shared undoable range command',async()=>{const {planDawEdit}=await import('../server/daw-agent.js'),h=setup(false),audioRange={regionId:'clip',start:11,end:13};let body;const adapter={key:'test',model:'test',fetchImpl:async(_,options)=>{body=JSON.parse(options.body);return {ok:true,json:async()=>({output:[{type:'function_call',name:'edit_session',arguments:JSON.stringify({summary:'Isolate selection',commands:[{op:'region.splitRange',target:'clip',values:{start:11,end:13}}]})}]})};}};const result=await planDawEdit({session:h.session,instruction:'Split this selection',audioRange},adapter);assert.deepEqual(JSON.parse(body.input.find(m=>m.role==='user').content).audioRange,audioRange);h.execute(result.commands,result.revision);assert.equal(h.session.tracks[0].regions.length,3);await assert.rejects(planDawEdit({session:h.session,instruction:'Split this selection',audioRange:{...audioRange,end:100}},adapter),/range/i);});

test('range splitting remaps comp passages at both boundaries',()=>{const h=setup(true);h.execute([{op:'comp.save',target:'audio',values:{id:'take',name:'Take',segments:JSON.stringify([{regionId:'clip',start:10,end:14}])}}]);h.execute([{op:'region.splitRange',target:'clip',values:{start:11,end:13}}]);const t=h.session.tracks[0],segments=t.compAlternatives[0].segments;assert.deepEqual(segments.map(s=>[s.start,s.end]),[[10,11],[11,13],[13,14]]);for(const s of segments){const r=t.regions.find(r=>r.id===s.regionId);assert.ok(r&&s.start>=r.start&&s.end<=r.start+r.duration);}assert.doesNotThrow(()=>h.execute([{op:'comp.createTrack',target:'audio',values:{compId:'take'}}]));});
