import test from 'node:test';import assert from 'node:assert/strict';import {SessionHistory} from '../src/experimental/session.js';import {scoreNoteAuditionPlan,createScoreNoteAudition} from '../src/experimental/score-note-audition.js';
const setup=()=>{const h=new SessionHistory();h.execute([{op:'track.add',values:{id:'t',kind:'midi',instrument:'sine'}},{op:'region.add',target:'t',values:{id:'r',start:2,duration:4}},{op:'note.add',target:'r',values:{id:'a',pitch:60,start:1,duration:2}},{op:'note.add',target:'r',values:{id:'b',pitch:64,start:1,duration:2}}]);return h;};
test('note audition isolates the actual note, preserves mixer state and caps length without editing',()=>{const h=setup(),before=structuredClone(h.session),plan=scoreNoteAuditionPlan(h.session,{regionId:'r',noteId:'a'});assert.equal(plan.position,3);assert.equal(plan.document.tracks[0].regions[0].notes.length,1);assert.equal(plan.document.tracks[0].regions[0].notes[0].duration,.5);assert.equal(plan.document.tracks[0].gainDb,h.session.tracks[0].gainDb);assert.ok(plan.end<=7);assert.deepEqual(h.session,before);h.execute([{op:'note.set',target:'a',values:{mute:true}}]);assert.equal(scoreNoteAuditionPlan(h.session,{regionId:'r',noteId:'a'}),null);assert.throws(()=>scoreNoteAuditionPlan(h.session,{regionId:'r',noteId:'missing'}));});
test('new audition cancels older preparation and stop releases the active graph',async()=>{
 const h=setup();let resume,stops=0,scheduled=0;const context={},wait=new Promise(resolve=>resume=resolve),callbacks=[];
 let calls=0;const audition=createScoreNoteAudition({getSession:()=>h.session,getContext:()=>++calls===1?wait:Promise.resolve(context),loadAsset:async()=>{},buffers:new Map(),schedule:()=>{scheduled++;return {stop(){stops++;}};},setTimer:fn=>{callbacks.push(fn);return callbacks.length;},clearTimer:()=>{}});
 const old=audition.play({regionId:'r',noteId:'a'});await audition.play({regionId:'r',noteId:'b'});resume(context);await old;assert.equal(scheduled,1);audition.stop();assert.equal(stops,1);callbacks[0]();assert.equal(stops,1);
});
test('session edits during preparation and blocked transport do not schedule sound',async()=>{
 const h=setup();let resume,scheduled=0,blocked=false;const pending=new Promise(resolve=>resume=resolve),audition=createScoreNoteAudition({getSession:()=>h.session,getContext:()=>pending,loadAsset:async()=>{},buffers:new Map(),blocked:()=>blocked,schedule:()=>{scheduled++;return {stop(){}};}});
 const playing=audition.play({regionId:'r',noteId:'a'});h.execute([{op:'note.set',target:'a',values:{pitch:62}}]);resume({});await playing;assert.equal(scheduled,0);blocked=true;await audition.play({regionId:'r',noteId:'a'});assert.equal(scheduled,0);
});
