import {compLanesView,bindCompLanes,replaceCompInterval} from './comp-lanes.js';
import {z} from 'zod';
import {sessionDuration} from './audio-engine.js';
import {stemSession} from './routing.js';
import {duplicateTrack} from './duplicate-track.js';
import {trimmedRegion} from './region-edit.js';
const piece=z.object({regionId:z.string().min(1).max(100),start:z.number().finite().min(0).max(86400),end:z.number().finite().min(0).max(86400)}).strict();
const options=z.object({segments:z.string().max(100000),name:z.string().min(1).max(200).optional(),muteSource:z.boolean().default(true),edgeFade:z.number().finite().min(0).max(.1).default(.005)}).strict();
export function audioCompPlan(session,trackId,values){
 const v=options.parse(values),source=session.tracks.find(t=>t.id===trackId);if(source?.kind!=='audio')throw Error('Choose an audio track containing takes.');
 if(session.tracks.length>=128)throw Error('A comp needs space for another track.');
 const segments=z.array(piece).min(1).max(64).parse(JSON.parse(v.segments)).sort((a,b)=>a.start-b.start);
 const regions=segments.map((s,i)=>{const r=source.regions.find(r=>r.id===s.regionId);if(!r?.assetId)throw Error('Each comp section must use an existing audio region with media.');if(s.end<=s.start||s.start<r.start||s.end>r.start+r.duration)throw Error('Comp sections must fit within their source regions.');if(i&&s.start<segments[i-1].end)throw Error('Comp sections cannot overlap. Choose one take for each interval.');const trimmed=trimmedRegion(r,s.start,s.end),fade=Math.min(v.edgeFade,trimmed.duration/2);return {...r,...trimmed,mute:false,fadeIn:fade,fadeOut:fade,fadeInShape:'linear',fadeOutShape:'linear',notes:[],events:[]};});
 return {source,regions,name:v.name??(source.name.slice(0,195)+' comp'),muteSource:v.muteSource};
}
export function createAudioComp(session,trackId,values){const plan=audioCompPlan(session,trackId,values),comp=duplicateTrack(plan.source,{name:plan.name,includeRegions:false});comp.mute=false;comp.regions=plan.regions.map(r=>({...r,id:crypto.randomUUID()}));session.tracks.splice(session.tracks.indexOf(plan.source)+1,0,comp);if(plan.muteSource)plan.source.mute=true;return comp;}
export function compAuditionPlan(session,trackId,values){
 const document=structuredClone(session),comp=createAudioComp(document,trackId,values);
 document.loopEnabled=false;
 return {document,position:Math.min(...comp.regions.map(r=>r.start)),end:sessionDuration(stemSession(document,comp)),label:'Auditioning comp in mix…'};
}
const draft=(drafts,track)=>{if(!drafts.has(track.id))drafts.set(track.id,{segments:[],name:track.name.slice(0,195)+' comp',muteSource:true,edgeFade:.005});return drafts.get(track.id);};
export function audioCompView(track,drafts,esc,waveform,auditioning=false){if(track?.kind!=='audio'||!track.regions.length)return '';const d=draft(drafts,track),regions=track.regions.filter(r=>r.assetId);return `<details class="daw-audio-comp"><summary>Build a comp from takes</summary><p class="muted">Choose the best timeline sections from this track's audio regions. Draft choices are temporary until you create the comp.</p>${compLanesView(track,d.segments,esc,waveform)}<form data-comp-add><label>Take<select name="regionId">${regions.map(r=>`<option value="${esc(r.id)}">${esc(r.name)} · ${r.start.toFixed(2)}–${(r.start+r.duration).toFixed(2)} s</option>`).join('')}</select></label><label>Start · seconds<input name="start" type="number" min="0" step="any" required></label><label>End · seconds<input name="end" type="number" min="0" step="any" required></label><button>Add section</button></form><ol>${d.segments.map((s,i)=>`<li>${esc(track.regions.find(r=>r.id===s.regionId)?.name||'Missing take')} · ${s.start.toFixed(2)}–${s.end.toFixed(2)} s <button type="button" data-comp-remove="${i}" aria-label="Remove comp section ${i+1}">Remove</button></li>`).join('')}</ol><form data-comp-create><label>Comp name<input name="name" value="${esc(d.name)}" maxlength="200" required></label><label>Edge fade · ms<input name="fade" type="number" min="0" max="100" step="any" value="${d.edgeFade*1000}" required></label><label><input name="muteSource" type="checkbox" ${d.muteSource?'checked':''}> Mute original track</label><button type="button" data-comp-audition ${d.segments.length?'':'disabled'}>${auditioning?'Stop audition':'Audition in mix'}</button><button ${d.segments.length?'':'disabled'}>Create comp track</button></form><p class="muted">Audition plays your current choices with the mix, including the mute-original option, without saving a track. Changes stop the audition; press Audition again to hear them. Creates editable audio sections on a new track with copied mixer settings. Original takes remain intact. Gaps stay silent; new choices replace earlier choices in the same time range. Each section uses the edge fade above instead of source fades, and plays even if its source region was muted. These are short fades, not overlapping crossfades. You can edit the resulting regions normally.</p></details>`;}
export function bindAudioComp(root,{session,track,drafts,execute,guard,repaint,blocked,audition,onDraftChange=()=>{}}){const add=root.querySelector('[data-comp-add]'),create=root.querySelector('[data-comp-create]');if(!add||!create)return;const d=draft(drafts,track),sync=()=>{d.name=create.elements.name.value;d.edgeFade=create.elements.fade.valueAsNumber/1000;d.muteSource=create.elements.muteSource.checked;};const defaults=()=>{const r=track.regions.find(r=>r.id===add.elements.regionId.value);if(r){add.elements.start.value=r.start;add.elements.end.value=r.start+r.duration;}};defaults();add.elements.regionId.onchange=defaults;create.oninput=()=>{sync();onDraftChange();};create.onchange=()=>{sync();onDraftChange();};
 root.querySelector('[data-comp-audition]').onclick=guard(async()=>{if(blocked?.())return;sync();await audition(compAuditionPlan(session,track.id,{segments:JSON.stringify(d.segments),name:d.name,muteSource:d.muteSource,edgeFade:d.edgeFade}));});
 const choose=section=>{sync();const next=replaceCompInterval(d.segments,section);audioCompPlan(session,track.id,{segments:JSON.stringify(next),name:d.name,muteSource:d.muteSource,edgeFade:d.edgeFade});onDraftChange();d.segments=next;repaint();};
 bindCompLanes(root,{track,choose,guard,blocked});
 add.onsubmit=guard(e=>{e.preventDefault();choose({regionId:add.elements.regionId.value,start:add.elements.start.valueAsNumber,end:add.elements.end.valueAsNumber});});
 root.querySelectorAll('[data-comp-remove]').forEach(button=>button.onclick=()=>{sync();onDraftChange();d.segments.splice(Number(button.dataset.compRemove),1);repaint();});
 create.onsubmit=guard(e=>{e.preventDefault();sync();execute([{op:'track.comp',target:track.id,values:{segments:JSON.stringify(d.segments),name:d.name,muteSource:d.muteSource,edgeFade:d.edgeFade}}],'Created audio comp',session.revision);d.segments=[];repaint();});
}
