import {z} from 'zod';
import {effectParameters} from './effect-automation.js';
const time=z.number().finite().min(0).max(86400),id=z.string().min(1).max(100);
const options=z.object({mode:z.enum(['copy','move','transform','delete']),parameter:z.string().min(1).max(50),start:time,end:time,position:time.optional(),busId:id.optional(),destination:id.optional(),destinationBusId:id.optional(),replace:z.boolean().default(false),timeScale:z.number().finite().min(.01).max(100).default(1),valueScale:z.number().finite().min(-100).max(100).default(1),valueOffset:z.number().finite().min(-1000000).max(1000000).default(0),valueAnchor:z.number().finite().min(-1000000).max(1000000).default(0)}).strict().superRefine((v,ctx)=>{if(v.end<v.start)ctx.addIssue({code:'custom',message:'Range end must be at least its start.'});if(['copy','move'].includes(v.mode)&&v.position===undefined)ctx.addIssue({code:'custom',message:'Choose a destination time.'});if(v.mode==='delete'&&(v.position!==undefined||v.destination!==undefined||v.destinationBusId!==undefined||v.replace||v.timeScale!==1||v.valueScale!==1||v.valueOffset!==0||v.valueAnchor!==0))ctx.addIssue({code:'custom',message:'Delete only takes a source range.'});if(v.mode==='transform'&&(v.position!==undefined||v.destination!==undefined||v.destinationBusId!==undefined))ctx.addIssue({code:'custom',message:'Transform edits the source lane in place; use Copy or Move to choose a destination.'});});
const mixParameters={gainDb:{label:'Volume (dB)',min:-96,max:12},pan:{label:'Pan',min:-1,max:1}};
export function automationLanes(session){
 const result=[],add=(target,name,points,parameters,busId)=>{for(const [parameter,spec]of Object.entries(parameters))result.push({target,name:`${name} · ${spec.label||parameter}`,points,parameter,spec,...(busId?{busId}:{})});};
 add(session.id,'Master',session.masterAutomation,mixParameters);
 for(const t of session.tracks){if(t.kind==='video')continue;add(t.id,t.name,t.automation,mixParameters);for(const send of t.sends)add(t.id,`${t.name} → ${session.tracks.find(b=>b.id===send.busId)?.name||'Send'}`,send.automation,{gainDb:mixParameters.gainDb},send.busId);}
 for(const owner of [{id:session.id,name:'Master',effects:session.masterEffects},...session.tracks])for(const effect of owner.effects)add(effect.id,`${owner.name} · ${effect.kind}`,effect.automation,effectParameters[effect.kind]);
 return result;
}
export function automationRangePlan(session,target,values){
 const v=options.parse(values),lanes=automationLanes(session),source=lanes.find(l=>l.target===target&&l.busId===v.busId&&l.parameter===v.parameter);if(!source)throw Error('Source automation lane not found.');
 const chosen=source.points.filter(p=>p.parameter===v.parameter&&p.time>=v.start&&p.time<=v.end);if(!chosen.length)throw Error('No automation points in this range.');const chosenIds=new Set(chosen.map(p=>p.id)),remainingSource=source.points.filter(p=>!chosenIds.has(p.id));
 if(v.mode==='delete')return {v,source,chosen,remainingSource,replaced:0};
 const destTarget=v.destination??target,destBus=v.destination===undefined&&v.destinationBusId===undefined?v.busId:v.destinationBusId,destination=lanes.find(l=>l.target===destTarget&&l.busId===destBus&&l.parameter===v.parameter);if(!destination)throw Error('Destination automation lane not found.');
 const inserted=chosen.map(p=>({...p,time:(v.mode==='transform'?v.start:v.position)+(p.time-v.start)*v.timeScale,value:p.value*v.valueScale+v.valueAnchor*(1-v.valueScale)+v.valueOffset}));if(inserted.some(p=>p.time>86400||p.value<destination.spec.min||p.value>destination.spec.max))throw Error('Transformed points exceed destination time or value limits.');if(new Set(inserted.map(p=>p.time)).size!==inserted.length)throw Error('Time scaling would put selected points at the same timestamp.');
 const initial=v.mode!=='copy'&&source.points===destination.points?remainingSource:destination.points,times=new Set(inserted.map(p=>p.time)),collisions=initial.filter(p=>p.parameter===v.parameter&&times.has(p.time));if(collisions.length&&!v.replace)throw Error('Destination points already exist at these times. Enable Replace collisions or choose another time.');
 const collisionIds=new Set(collisions.map(p=>p.id)),remainingDestination=initial.filter(p=>!collisionIds.has(p.id));if(remainingDestination.length+inserted.length>2000)throw Error('Automation lanes support at most 2,000 points across all parameters.');
 return {v,source,destination,chosen,remainingSource,remainingDestination,inserted,replaced:collisions.length};
}
export function applyAutomationRange(session,target,values){const plan=automationRangePlan(session,target,values);if(plan.v.mode==='delete'){plan.source.points.splice(0,plan.source.points.length,...plan.remainingSource);return;}const inserted=plan.inserted.map(p=>plan.v.mode==='copy'?{...p,id:crypto.randomUUID()}:p);if(plan.v.mode!=='copy'&&plan.source.points!==plan.destination.points)plan.source.points.splice(0,plan.source.points.length,...plan.remainingSource);plan.destination.points.splice(0,plan.destination.points.length,...plan.remainingDestination,...inserted);}
export function automationRangeView(){return `<details class="daw-automation-range"><summary>Copy, move or transform points</summary><form data-auto-range><label>Action<select name="mode"><option value="copy">Copy points</option><option value="move">Move points</option><option value="transform">Transform in place</option><option value="delete">Delete points</option></select></label><label>From · seconds<input name="start" type="number" min="0" max="86400" step="any" value="0" required></label><label>Through · seconds<input name="end" type="number" min="0" max="86400" step="any" value="0" required></label><label>Destination<select name="destination"></select></label><label>Place range start at · seconds<input name="position" type="number" min="0" max="86400" step="any" value="0" required></label><label><input name="replace" type="checkbox"> Replace points at matching destination times</label><label>Time scale · %<input name="timeScale" type="number" min="1" max="10000" step="any" value="100" required></label><label>Value scale · %<input name="valueScale" type="number" min="-10000" max="10000" step="any" value="100" required></label><label>Value pivot<input name="valueAnchor" type="number" min="-1000000" max="1000000" step="any" value="0" required></label><label>Value offset<input name="valueOffset" type="number" min="-1000000" max="1000000" step="any" value="0" required></label><button type="button" data-auto-reset-transform>Reset scaling and offset</button><output data-auto-range-preview></output><button type="submit">Apply range edit</button><p class="muted">Edits points of the displayed parameter, including both time boundaries. Curve shapes are preserved. 100% keeps timing or values unchanged; 200% doubles them. Time scales from the range start. Value scaling uses the pivot, then adds the offset in this parameter’s units. A negative value scale inverts the curve around the pivot. Out-of-range results are rejected, not clipped. Copy creates new points; Move and Transform keep their identities. No boundary points are added: neighboring curve segments may change. Other parameters stay unchanged.</p></form></details>`;}
export function bindAutomationRange(root,{session,target,busId,parameter,execute,guard,duration}){
 const form=root.querySelector('[data-auto-range]');if(!form||!session)return;const button=form.querySelector('[type=submit]'),lanes=automationLanes(session).filter(l=>l.parameter===parameter);form.elements.end.value=Math.min(86400,duration);form.elements.position.value=Math.min(86400,duration);
 for(const [i,lane]of lanes.entries()){const opt=document.createElement('option');opt.value=i;opt.textContent=lane.name;opt.selected=lane.target===target&&lane.busId===busId;form.elements.destination.append(opt);}
 const values=()=>{const mode=form.elements.mode.value,common={mode,parameter,start:form.elements.start.valueAsNumber,end:form.elements.end.valueAsNumber,...(busId?{busId}:{})};if(mode==='delete')return common;const transforms={timeScale:form.elements.timeScale.valueAsNumber/100,valueScale:form.elements.valueScale.valueAsNumber/100,valueAnchor:form.elements.valueAnchor.valueAsNumber,valueOffset:form.elements.valueOffset.valueAsNumber,replace:form.elements.replace.checked};if(mode==='transform')return {...common,...transforms};const dest=lanes[Number(form.elements.destination.value)];return {...common,...transforms,position:form.elements.position.valueAsNumber,destination:dest?.target,...(dest?.busId?{destinationBusId:dest.busId}:{})};};
 const update=()=>{for(const key of ['destination','position']){const disabled=['delete','transform'].includes(form.elements.mode.value);form.elements[key].disabled=disabled;form.elements[key].parentElement.style.display=disabled?'none':'';}for(const key of ['replace','timeScale','valueScale','valueAnchor','valueOffset']){const disabled=form.elements.mode.value==='delete';form.elements[key].disabled=disabled;form.elements[key].parentElement.style.display=disabled?'none':'';}try{const plan=automationRangePlan(session,target,values());form.querySelector('[data-auto-range-preview]').textContent=`${plan.chosen.length} points to ${plan.v.mode}${plan.replaced?` · ${plan.replaced} destination points replaced`:''}${plan.inserted?` · ${Math.min(...plan.inserted.map(p=>p.time)).toFixed(2)}–${Math.max(...plan.inserted.map(p=>p.time)).toFixed(2)} s · values ${Math.min(...plan.inserted.map(p=>p.value)).toFixed(2)}–${Math.max(...plan.inserted.map(p=>p.value)).toFixed(2)}`:''}`;button.disabled=false;}catch(e){form.querySelector('[data-auto-range-preview]').textContent=e.message;button.disabled=true;}};
 form.querySelector('[data-auto-reset-transform]').onclick=()=>{form.elements.timeScale.value=100;form.elements.valueScale.value=100;form.elements.valueAnchor.value=0;form.elements.valueOffset.value=0;update();};
 form.oninput=update;form.onchange=update;form.onsubmit=guard(e=>{e.preventDefault();update();if(!button.disabled)execute([{op:'automation.range',target,values:values()}],'Edited automation range');});update();
}
