import {prepareTakeTransfer,finishTakeTransfer,takeBundleFingerprint} from './scene-take-transfer.js';
import {validateSceneTakeBundle} from './scene-takes.js';
import {referencedAssets,remapAssets} from './media-refs.js';
import {upload} from '@vercel/blob/client';
export {referencedAssets} from './media-refs.js';
export async function cloudRequest(url,options){const response=await fetch(url,{...options,signal:AbortSignal.timeout(30000)});if(response.status===401)throw Error('Sign in again to save your session. Local edits are kept.');if(response.status===409)throw Error('This project changed elsewhere. Save a copy or reopen its account version.');if(response.status===413)throw Error('This session exceeds the account document size limit. Export a portable project instead.');if(!response.ok){const data=await response.json().catch(()=>({}));throw Error(data.error||'Account project request failed. Local edits are kept.');}return response.json();}
export function createDawCloud({key,request=cloudRequest,uploadFile=upload}){
 const read=id=>{try{const value=JSON.parse(localStorage.getItem(key+':cloud'));return value?.sessionId===id?value:{sessionId:id,assets:{}};}catch{return {sessionId:id,assets:{}};}};
 const write=value=>localStorage.setItem(key+':cloud',JSON.stringify(value));
 async function save(session,files,report,copy=false,takeBundle){const sceneTakes=validateSceneTakeBundle(takeBundle,session.id),meta=read(session.id),target=copy||!meta.project?{id:crypto.randomUUID(),revision:0}:meta.project;if(!session.title.trim())throw Error('Name your session before saving.');const plannedAssets=Object.fromEntries(referencedAssets(session).map(id=>[id,meta.assets[id]??'00000000-0000-0000-0000-000000000000']));if(new TextEncoder().encode(JSON.stringify({...target,data:{type:'daw',status:'draft',session,assets:plannedAssets,sceneTakes}})).length>1024*1024)throw Error('This session exceeds the 1 MB account document limit. Export a portable project instead.');for(const id of referencedAssets(session)){if(meta.assets[id])continue;const file=files.get(id);if(!file)throw Error('A source file is missing. Restore it before saving.');report(`Uploading ${file.name}…`);let asset=meta.pending?.[id];if(!asset){asset=(await request('/api/media?action=reserve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filename:file.name,size:file.size})})).asset;await uploadFile(asset.pathname,file,{access:'private',handleUploadUrl:'/api/media',clientPayload:asset.id,contentType:asset.contentType,multipart:true,onUploadProgress:({percentage})=>report(`Uploading ${file.name} · ${Math.round(percentage)}%`)});meta.pending??={};meta.pending[id]=asset;write(meta);}await request('/api/media?action=complete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:asset.id})});meta.assets[id]=asset.id;delete meta.pending[id];write(meta);}
  const assets=Object.fromEntries(referencedAssets(session).map(id=>[id,meta.assets[id]])),body=JSON.stringify({...target,data:{type:'daw',status:'draft',session,assets,sceneTakes}});if(new TextEncoder().encode(body).length>1024*1024)throw Error('This session exceeds the 1 MB account document limit. Export a portable project instead.');report('Saving session…');const {project}=await request('/api/projects',{method:'POST',headers:{'Content-Type':'application/json'},body});meta.project={id:project.id,revision:project.revision};meta.savedSessionRevision=session.revision;meta.savedTakeFingerprint=takeBundleFingerprint(sceneTakes);write(meta);return project;
 }
 async function restore(project,report){const session=structuredClone(project.data.session),takeTransfer=prepareTakeTransfer(project.data.sceneTakes,session),records=[],assets={},mapping=new Map();for(const id of referencedAssets(session)){const assetId=project.data.assets[id];if(!assetId)throw Error('Project is missing its media mapping.');const media=await request('/api/media?id='+encodeURIComponent(assetId));report(`Loading ${media.filename}…`);const response=await fetch(media.url,{credentials:'omit',referrerPolicy:'no-referrer',signal:AbortSignal.timeout(15*60*1000)});if(!response.ok)throw Error('Source download failed. Your current session is kept.');const blob=await response.blob();if(blob.size!==Number(media.size))throw Error('Source download was incomplete.');const localId=crypto.randomUUID();mapping.set(id,localId);assets[localId]=assetId;records.push({id:localId,file:new File([blob],media.filename,{type:media.contentType})});}remapAssets(session,mapping);const sceneTakes=finishTakeTransfer(takeTransfer,session);return {session,records,sceneTakes,meta:{sessionId:session.id,assets,project:{id:project.id,revision:project.revision},savedSessionRevision:session.revision,savedTakeFingerprint:takeBundleFingerprint(sceneTakes)}};}
 return {save,restore,read,write};
}
