export function replaceCompInterval(segments,section){
 if(!Number.isFinite(section.start)||!Number.isFinite(section.end)||section.end<=section.start)throw Error('Choose a positive take section.');
 const next=segments.flatMap(s=>s.end<=section.start||s.start>=section.end?[{...s}]:[...(s.start<section.start?[{...s,end:section.start}]:[]),...(s.end>section.end?[{...s,start:section.end}]:[])]);
 next.push({...section});next.sort((a,b)=>a.start-b.start);const merged=[];for(const s of next){const last=merged.at(-1);if(last&&last.regionId===s.regionId&&last.end===s.start)last.end=s.end;else merged.push(s);}return merged;
}
export function compLanesView(track,segments,esc,waveform=()=> ''){
 const all=track.regions.filter(r=>r.assetId),regions=all.slice(0,32);if(!regions.length)return '';
 const min=Math.min(...all.map(r=>r.start)),max=Math.max(...all.map(r=>r.start+r.duration)),x=t=>180+(t-min)/(max-min)*800;
 return `<p class="muted">Drag across a take to choose a section. A new choice replaces earlier choices over the same interval. Enter or Space chooses a focused take in full. Numeric fields below offer exact boundaries.${all.length>32?' The first 32 takes are shown; all takes are available in the dropdown.':''}</p><div class="daw-comp-lanes"><svg data-comp-lanes data-min="${min}" data-max="${max}" viewBox="0 0 1000 ${60+regions.length*44}" aria-label="Audio take sections"><text x="180" y="16">${min.toFixed(2)} s</text><text x="980" y="16" text-anchor="end">${max.toFixed(2)} s</text><text x="8" y="36">Comp</text>${segments.map(s=>`<rect class="daw-comp-choice" x="${x(s.start)}" y="24" width="${x(s.end)-x(s.start)}" height="16"/>`).join('')}${regions.map((r,i)=>{const y=60+i*44,left=x(r.start),width=x(r.start+r.duration)-left;return `<g data-comp-lane="${esc(r.id)}" tabindex="0" role="button" aria-label="Choose ${esc(r.name)}, ${r.start.toFixed(2)} to ${(r.start+r.duration).toFixed(2)} seconds"><title>${esc(r.name)}</title><text x="8" y="${y+21}">${esc(r.name.slice(0,22))}</text><rect class="daw-comp-take" x="${left}" y="${y}" width="${width}" height="32"/>${waveform(r).replace('<svg ',`<svg class="daw-comp-wave" x="${left}" y="${y}" width="${width}" height="32" `)}${segments.filter(s=>s.regionId===r.id).map(s=>`<rect class="daw-comp-choice" x="${x(s.start)}" y="${y}" width="${x(s.end)-x(s.start)}" height="32"/>`).join('')}</g>`;}).join('')}<rect data-comp-preview class="daw-comp-drag" x="0" y="0" width="0" height="32" visibility="hidden"/></svg></div>`;
}
export function bindCompLanes(root,{track,choose,guard,blocked=()=>false}){
 const svg=root.querySelector('[data-comp-lanes]');if(!svg)return;const preview=svg.querySelector('[data-comp-preview]'),min=Number(svg.dataset.min),max=Number(svg.dataset.max);let drag,observer;const view=svg.ownerDocument.defaultView;
 const cancel=()=>{if(!drag)return;const id=drag.id;drag=null;observer?.disconnect();observer=null;view.removeEventListener('blur',cancel);preview.setAttribute('visibility','hidden');if(svg.hasPointerCapture(id))svg.releasePointerCapture(id);};
 const time=(event,region)=>{const box=svg.getBoundingClientRect(),value=min+((event.clientX-box.left)/box.width*1000-180)/800*(max-min);return Math.max(region.start,Math.min(region.start+region.duration,value));};
 svg.onpointerdown=event=>{if(event.button!==0||blocked())return;const lane=event.target.closest('[data-comp-lane]');if(!lane)return;const region=track.regions.find(r=>r.id===lane.dataset.compLane);if(!region)return;event.preventDefault();lane.focus();cancel();drag={id:event.pointerId,region,start:time(event,region),end:time(event,region),x:event.clientX,y:60+[...svg.querySelectorAll('[data-comp-lane]')].indexOf(lane)*44};svg.setPointerCapture(event.pointerId);view.addEventListener('blur',cancel);observer=new MutationObserver(()=>{if(!svg.isConnected)cancel();});observer.observe(svg.ownerDocument,{childList:true,subtree:true});};
 svg.onpointermove=event=>{if(!drag||event.pointerId!==drag.id)return;drag.end=time(event,drag.region);const start=Math.min(drag.start,drag.end),end=Math.max(drag.start,drag.end);preview.setAttribute('x',180+(start-min)/(max-min)*800);preview.setAttribute('y',drag.y);preview.setAttribute('width',(end-start)/(max-min)*800);preview.setAttribute('visibility','visible');};
 svg.onpointerup=guard(event=>{if(!drag||event.pointerId!==drag.id)return;const d=drag;d.end=time(event,d.region);cancel();if(!svg.isConnected||blocked()||Math.abs(event.clientX-d.x)<3||d.end===d.start)return;choose({regionId:d.region.id,start:Math.min(d.start,d.end),end:Math.max(d.start,d.end)});});
 svg.onpointercancel=cancel;svg.onlostpointercapture=cancel;svg.onkeydown=guard(event=>{if(event.key==='Escape'){cancel();return;}if(!['Enter',' '].includes(event.key)||blocked())return;const lane=event.target.closest('[data-comp-lane]'),r=track.regions.find(r=>r.id===lane?.dataset.compLane);if(r){event.preventDefault();cancel();choose({regionId:r.id,start:r.start,end:r.start+r.duration});}});
}
