import {selectedRegions} from './region-selection.js';
import {createLevelMeters} from './meters.js';
import {scheduleMetronome} from './metronome.js';
import {scheduleSession} from './audio-engine.js';
export function transportPosition(playback,now){const elapsed=Math.max(0,now-playback.base);if(playback.loop)return playback.loop.start+(playback.position-playback.loop.start+elapsed)%playback.loop.duration;return playback.position+elapsed;}
export async function renderCycle(session,buffers,sampleRate,{metronome=false}={}){const duration=session.loopEnd-session.loopStart;if(!(duration>0)||duration>600)throw Error('Cycle playback supports ranges up to 10 minutes.');const offline=new OfflineAudioContext(2,Math.max(1,Math.round(duration*sampleRate)),sampleRate);scheduleSession(offline,session,buffers,session.loopStart,{baseTime:0});if(metronome)scheduleMetronome(offline,session,{position:session.loopStart,baseTime:0,duration});return offline.startRendering();}
export function startCycle(context,buffer,start,position,{meterId}={}){const source=context.createBufferSource(),base=context.currentTime+.025,duration=buffer.duration;source.buffer=buffer;source.loop=true;source.connect(context.destination);const offset=position>=start&&position<start+duration?position-start:0;source.start(base,offset);const meters=meterId?createLevelMeters(context):null;meters?.add(meterId,source,{startTime:base});return {base,meters,position:start+offset,loop:{start,duration},stop(){meters?.stop();source.stop();source.disconnect();}};}
export function cycleView(session){return `<form class="daw-cycle" data-cycle-form><label><input type="checkbox" name="enabled" title="Repeats the rendered range; effect tails reset at each boundary." ${session.loopEnabled?'checked':''}> Cycle</label><label>Start · seconds<input type="number" name="start" min="0" step="any" value="${session.loopStart}"></label><label>End · seconds<input type="number" name="end" min="0" step="any" value="${session.loopEnd}"></label><button type="submit">Apply cycle</button><button type="button" data-cycle-selection>Loop selected clips</button><button type="button" data-action="range-bounce">Bounce range WAV</button><small>Export uses the saved start/end even when Cycle is off. Ends exactly at the range boundary. Earlier reverb/delay history is not included.</small></form>`;}
export function bindCycle(root,{session,ids,execute,guard}){const form=root.querySelector('[data-cycle-form]');form.onsubmit=guard(e=>{e.preventDefault();execute([{op:'session.set',values:{loopEnabled:form.elements.enabled.checked,loopStart:Number(form.elements.start.value),loopEnd:Number(form.elements.end.value)}}],'Updated cycle range');});root.querySelector('[data-cycle-selection]').onclick=guard(()=>{execute([{op:'session.set',values:cycleFromSelection(session,ids)}],'Cycle follows the selected clips');});}

export function cycleFromSelection(session,ids){
 const regions=selectedRegions(session,ids),loopStart=Math.min(...regions.map(r=>r.start)),loopEnd=Math.max(...regions.map(r=>r.start+r.duration));
 if(loopEnd>86400)throw Error('The selected passage extends beyond the 24-hour timeline.');
 if(loopEnd-loopStart>600)throw Error('Select a passage of 10 minutes or less for cycle playback.');
 return {loopEnabled:true,loopStart,loopEnd};
}
