export const drumRows=[{pitch:36,name:'Kick'},{pitch:38,name:'Snare'},{pitch:42,name:'Closed hat'},{pitch:46,name:'Open hat'},{pitch:49,name:'Crash'},{pitch:51,name:'Ride'}];
export const drumDuration=pitch=>pitch===36?.5:pitch===38?.4:pitch===42?.12:pitch===46?.9:1.4;
const cache=new WeakMap();
export function drumBuffer(context,pitch){let buffers=cache.get(context);if(!buffers){buffers=new Map();cache.set(context,buffers);}if(buffers.has(pitch))return buffers.get(pitch);const length=Math.ceil(drumDuration(pitch)*context.sampleRate),buffer=context.createBuffer(1,length,context.sampleRate),data=buffer.getChannelData(0);let seed=1987+pitch,previous=0;for(let i=0;i<length;i++){const t=i/context.sampleRate;seed=(Math.imul(seed,1664525)+1013904223)>>>0;const noise=seed/2147483648-1,high=(noise-previous)*.5;previous=noise;let sample;
 if(pitch===36)sample=Math.sin(2*Math.PI*(45*t+100/30*(1-Math.exp(-30*t))))*Math.exp(-12*t)+noise*.08*Math.exp(-100*t);
 else if(pitch===38)sample=(high*.85+Math.sin(2*Math.PI*180*t)*.15)*Math.exp(-16*t);
 else{const decay=pitch===42?45:pitch===46?7:4,metal=Math.sin(2*Math.PI*4100*t)*Math.sin(2*Math.PI*5671*t);sample=(high*.7+metal*.3)*Math.exp(-decay*t);}
 data[i]=sample*.6*Math.min(1,t/.001)*Math.min(1,(length-i)/(context.sampleRate*.015));}buffers.set(pitch,buffer);return buffer;}
export function scheduleDrum(context,destination,note,relative,when,regionDuration,nodes){const buffer=drumBuffer(context,note.pitch),elapsed=Math.max(0,relative-note.start),duration=Math.min(buffer.duration,regionDuration-note.start)-elapsed;if(duration<=0||note.velocity===0)return;const source=context.createBufferSource(),gain=context.createGain();source.buffer=buffer;gain.gain.value=note.velocity;source.connect(gain).connect(destination);source.start(when+Math.max(0,note.start-relative),elapsed,duration);nodes.push(source,gain);}
export function stepSequencerView(region,session,bar,velocity){const step=60/session.tempo/4,steps=session.meter*4,barLength=steps*step,bars=Math.max(1,Math.ceil(region.duration/barLength)),index=Math.min(bar,bars-1);return `<section class="daw-sequencer"><div class="section-title"><h3>Step sequencer</h3><label>Bar<select data-pattern-bar>${Array.from({length:bars},(_,i)=>`<option value="${i}" ${i===index?'selected':''}>${i+1}</option>`).join('')}</select></label><label>Velocity<input data-pattern-velocity type="number" min="1" max="127" step="1" value="${velocity}"></label></div><p class="muted">Each step is a sixteenth note. Click to add or remove a hit; edit velocities and mute notes in the piano roll. Muted steps have dashed outlines.</p><div class="daw-step-scroll">${drumRows.map(row=>`<div class="daw-step-row" style="grid-template-columns:90px repeat(${steps},28px)"><strong>${row.name}</strong>${Array.from({length:steps},(_,i)=>{const time=index*barLength+i*step,hits=region.notes.filter(n=>n.pitch===row.pitch&&(n.channel||0)===9&&Math.abs(n.start-time)<.0001);return `<button data-step-pitch="${row.pitch}" data-step-time="${time}" class="${i%4===0?'beat':''}" aria-label="${row.name}, step ${i+1}" data-step-muted="${hits.length>0&&hits.every(n=>n.mute)}" aria-pressed="${hits.length>0}" ${time>=region.duration?'disabled':''}></button>`;}).join('')}</div>`).join('')}</div></section>`;}
export function bindSequencer(root,{region,tempo,velocity,onBar,onVelocity,execute,guard}){if(!region)return;root.querySelector('[data-pattern-bar]')?.addEventListener('change',e=>onBar(Number(e.target.value)));root.querySelector('[data-pattern-velocity]')?.addEventListener('change',guard(e=>{const value=Number(e.target.value);if(!Number.isInteger(value)||value<1||value>127)throw Error('Velocity must be from 1 to 127.');onVelocity(value);}));root.querySelectorAll('[data-step-pitch]').forEach(button=>button.onclick=guard(()=>{const pitch=Number(button.dataset.stepPitch),start=Number(button.dataset.stepTime),notes=region.notes.filter(n=>n.pitch===pitch&&(n.channel||0)===9&&Math.abs(n.start-start)<.0001);execute(notes.length?notes.map(n=>({op:'note.delete',target:n.id})):[{op:'note.add',target:region.id,values:{pitch,start,channel:9,duration:Math.min(60/tempo/4,region.duration-start),velocity:velocity()/127}}],notes.length?'Removed drum hit':'Added drum hit');}));}
