import {markerCyclePlan} from './marker-cycle.js';
import {timelinePosition,parseTimelinePosition} from './timeline-ruler.js';
const positionValue=(time,session,mode)=>mode==='seconds'?String(time):timelinePosition(time,session,mode);
export const orderedMarkers=session=>[...session.markers].sort((a,b)=>a.time-b.time||a.name.localeCompare(b.name));
export function adjacentMarker(session,position,direction){const markers=orderedMarkers(session);return direction<0?markers.filter(m=>m.time<position-.000001).at(-1):markers.find(m=>m.time>position+.000001);}
export function markersView(session,position,esc,playing=false,mode='seconds',regionIds=[]){const cycle=m=>{try{markerCyclePlan(session,m.id);return `<button type="button" data-marker-cycle="${esc(m.id)}">Loop to next marker</button>`;}catch(error){return `<button type="button" disabled title="${esc(error.message)}">Loop to next marker</button>`;}};const field=time=>`<label>${mode==='timecode'?'Timecode':mode==='musical'?'Bar:beat:tick':'Time · seconds'}<input name="time" ${mode==='seconds'?'type="number" min="0" max="86400" step="any"':'type="text"'} value="${esc(positionValue(time,session,mode))}" required></label>`;return `<details class="daw-markers" open><summary>Markers · ${session.markers.length}</summary><div class="button-row"><button data-markers-from-regions ${regionIds.length?'':'disabled'}>Create markers from selected regions</button><button data-marker-capture>Add marker at playhead</button><button data-marker-prev ${(playing&&session.markers.length)||adjacentMarker(session,position,-1)?'':'disabled'}>Previous marker</button><button data-marker-next ${(playing&&session.markers.length)||adjacentMarker(session,position,1)?'':'disabled'}>Next marker</button></div><form data-marker-new><label>Marker name<input name="name" maxlength="200" required placeholder="Chorus, scene change…"></label>${field(position)}<button>Add named marker</button></form><div class="daw-marker-list">${orderedMarkers(session).map(m=>`<form data-marker-edit="${esc(m.id)}"><button type="button" data-marker-jump="${esc(m.id)}" aria-label="Go to ${esc(m.name)}">${esc(timelinePosition(m.time,session,mode))}</button><label>Name<input name="name" maxlength="200" value="${esc(m.name)}" required></label>${field(m.time)}<button>Save marker</button>${cycle(m)}<button type="button" data-marker-delete="${esc(m.id)}">Delete marker</button></form>`).join('')||'<p class="muted">Mark scene changes, sections, or places to revisit.</p>'}</div></details>`;}
export function bindMarkers(root,{session,position,getPosition=()=>position,seek,execute,guard,mode='seconds',regionIds=[]}){
 root.querySelector('[data-markers-from-regions]').onclick=guard(()=>execute([{op:'markers.fromRegions',values:{regionIds:regionIds.join(',')}}],'Created markers from selected regions'));
 root.querySelector('[data-marker-capture]').onclick=guard(()=>{const names=new Set(session.markers.map(m=>m.name));let number=1;while(names.has('Cue '+number))number++;execute([{op:'marker.add',values:{name:'Cue '+number,time:getPosition()}}],'Added marker at playhead');});
 const values=(form,original)=>{const name=form.elements.name.value.trim();if(!name)throw Error('Enter a marker name.');return {name,time:original!==undefined&&form.elements.time.value===positionValue(original,session,mode)?original:parseTimelinePosition(form.elements.time.value,session,mode)};};
 root.querySelector('[data-marker-new]').onsubmit=guard(e=>{e.preventDefault();execute([{op:'marker.add',values:values(e.currentTarget)}],'Added marker');});
 root.querySelectorAll('[data-marker-edit]').forEach(form=>form.onsubmit=guard(e=>{e.preventDefault();execute([{op:'marker.set',target:form.dataset.markerEdit,values:values(form,session.markers.find(m=>m.id===form.dataset.markerEdit)?.time)}],'Updated marker');}));
 root.querySelectorAll('[data-marker-cycle]').forEach(button=>button.onclick=guard(()=>execute([{op:'marker.cycle',target:button.dataset.markerCycle}],'Loop between cue markers')));
 root.querySelectorAll('[data-marker-delete]').forEach(button=>button.onclick=guard(()=>execute([{op:'marker.delete',target:button.dataset.markerDelete}],'Deleted marker')));
 root.querySelectorAll('[data-marker-jump]').forEach(button=>button.onclick=()=>{const marker=session.markers.find(m=>m.id===button.dataset.markerJump);if(marker)seek(marker.time);});
 for(const [selector,direction] of [['[data-marker-prev]',-1],['[data-marker-next]',1]])root.querySelector(selector).onclick=()=>{const marker=adjacentMarker(session,getPosition(),direction);if(marker)seek(marker.time);};
}
