import {z} from 'zod';
import {melodySettingsSchema} from './audio-melody.js';
export const melodyActionSchema=z.object({operation:z.enum(['preview','createMidi']),regionId:z.string().min(1).max(100).nullable(),settings:z.object(Object.fromEntries(Object.entries(melodySettingsSchema.shape).map(([key,value])=>[key,value.unwrap()]))).strict()}).strict();
export function prepareMelodyAnalysis(session,value,selected){const v=melodyActionSchema.parse(value);v.settings=melodySettingsSchema.parse(v.settings);const regionId=v.regionId??selected,track=session.tracks.find(t=>t.regions.some(r=>r.id===regionId)),region=track?.regions.find(r=>r.id===regionId);if(track?.kind!=='audio'||!region?.assetId)throw Error('Select an audio region with a source recording.');if(region.duration>120)throw Error('Split this recording into regions of at most two minutes before melody analysis.');return {...v,regionId};}
export function melodyMidiCommands(session,analysis){
 if(!analysis||analysis.sessionId!==session.id||analysis.revision!==session.revision)throw Error('The project changed. Analyze the melody again.');
 const region=session.tracks.filter(t=>t.kind==='audio').flatMap(t=>t.regions).find(r=>r.id===analysis.regionId);
 if(!region||!analysis.notes?.length)throw Error('No detected melody notes to create.');
 const notes=z.array(z.object({pitch:z.number().int().min(0).max(127),start:z.number().finite().min(0),duration:z.number().finite().min(.001).max(3600),velocity:z.number().finite().min(0).max(1),cents:z.number().finite(),confidence:z.number().finite().min(0).max(1)}).strict()).min(1).max(20000).parse(analysis.notes);
 if(notes.some(n=>n.start+n.duration>region.duration+1e-8))throw Error('Detected notes exceed the source region.');
 const trackId=crypto.randomUUID(),regionId=crypto.randomUUID(),name=`${region.name||'Audio'} melody`.slice(0,100);
 return {trackId,regionId,commands:[{op:'track.add',values:{id:trackId,kind:'midi',name,instrument:'sine'}},{op:'region.add',target:trackId,values:{id:regionId,name,start:region.start,duration:region.duration}},{op:'notes.addMany',target:regionId,values:{notes:JSON.stringify(notes.map(({pitch,start,duration,velocity})=>({id:crypto.randomUUID(),pitch,start,duration,velocity})))}}]};
}
export function melodyView(track,region,analysis,disabled=false){if(track?.kind!=='audio'||!region?.assetId)return '';return `<details data-melody-analysis><summary>Audio to MIDI · melody</summary><p class="muted">For one voice or instrument playing one note at a time. Analyze the source recording, review the detected notes, then create an editable MIDI track. Chords, drums, slides and noisy recordings can produce incorrect notes. The audio stays unchanged.</p><form data-melody-form><div class="button-row"><label>Lowest MIDI pitch<input name="minPitch" type="number" min="24" max="95" value="${analysis?.settings.minPitch??36}" required></label><label>Highest MIDI pitch<input name="maxPitch" type="number" min="25" max="96" value="${analysis?.settings.maxPitch??84}" required></label><label>Noise floor · dB<input name="floorDb" type="number" min="-80" max="-12" value="${analysis?.settings.floorDb??-45}" required></label><label>Shortest note · seconds<input name="minimumDuration" type="number" min=".04" max="1" step=".01" value="${analysis?.settings.minimumDuration??.08}" required></label></div><button ${disabled?'disabled':''}>Analyze melody</button></form>${analysis?`<p>${analysis.notes.length} notes detected. Timing is approximate; MIDI uses nearest semitones.</p>${analysis.notes.length?`<button data-melody-create ${disabled?'disabled':''}>Create MIDI track</button><div style="max-height:260px;overflow:auto"><table><thead><tr><th>Note</th><th>Start · s</th><th>Length · s</th><th>Tuning · cents</th><th>Confidence</th></tr></thead><tbody>${analysis.notes.slice(0,128).map(n=>`<tr><td>${['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'][n.pitch%12]}${Math.floor(n.pitch/12)-1}</td><td>${n.start.toFixed(2)}</td><td>${n.duration.toFixed(2)}</td><td>${n.cents.toFixed(0)}</td><td>${Math.round(n.confidence*100)}%</td></tr>`).join('')}</tbody></table></div>${analysis.notes.length>128?'<small>First 128 notes shown; all detected notes will be created.</small>':''}`:'<p>Try adjusting the range or noise floor, or use a clearer solo recording.</p>'}`:''}</details>`;}
