const noteName=p=>`${['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'][p%12]}${Math.floor(p/12)-1}`;
export function melodyGraphLayout(notes,measured,startIndex=0){
 if(!notes.length)return null;
 const pitches=notes.flatMap((n,i)=>[Math.floor(n.pitch+(n.fineCents??0)/100),Math.ceil(n.pitch+(n.fineCents??0)/100),measured[i].pitch]),low=Math.max(0,Math.min(...pitches)-2),high=Math.min(127,Math.max(...pitches)+2),rowHeight=22,top=30,left=55,width=700,height=top+(high-low+1)*rowHeight+12;
 const start=Math.max(0,Math.floor(Math.min(...[...notes,...measured].map(n=>n.start))*10)/10),end=Math.max(start+.1,Math.ceil(Math.max(...[...notes,...measured].map(n=>n.start+n.duration))*10)/10),span=end-start;
 return {width,height,rowHeight,low,high,start,end,rows:Array.from({length:high-low+1},(_,i)=>({pitch:high-i,y:top+i*rowHeight,name:noteName(high-i)})),notes:notes.map((n,i)=>({index:startIndex+i,pitch:n.pitch,fineCents:n.fineCents??0,name:noteName(n.pitch),excluded:Boolean(n.excluded),x:left+(n.start-start)/span*(width-left-10),y:top+(high-n.pitch-(n.fineCents??0)/100)*rowHeight+2,width:Math.max(3,n.duration/span*(width-left-10)),height:rowHeight-4,measuredX:left+(measured[i].start-start)/span*(width-left-10),measuredWidth:Math.max(3,measured[i].duration/span*(width-left-10)),measuredY:top+(high-measured[i].pitch-measured[i].cents/100)*rowHeight+2})),ticks:Array.from({length:6},(_,i)=>({x:left+i/5*(width-left-10),label:(start+span*i/5).toFixed(2)}))};
}
export function melodyGraphView(analysis,notes,disabled){const start=analysis.page??0,layout=melodyGraphLayout(notes.slice(start,start+128),analysis.notes.slice(start,start+128),start);if(!layout)return '';return `<p class="muted">Drag notes vertically to change pitch, or use ↑/↓ (Shift for an octave). Click or press Enter to edit their fields. Solid blocks show draft pitches; outlines show original detections. Times are seconds within the region.</p><div class="daw-melody-scroll" style="overflow:auto;max-height:380px;border:1px solid var(--line);border-radius:6px"><svg data-melody-graph data-row-height="${layout.rowHeight}" viewBox="0 0 ${layout.width} ${layout.height}" style="display:block;width:100%;min-width:700px;height:auto;background:var(--surface)" role="group" aria-label="Detected melody pitch editor">${layout.rows.map(r=>`<rect x="0" y="${r.y}" width="${layout.width}" height="${layout.rowHeight}" fill="${[1,3,6,8,10].includes(r.pitch%12)?'var(--raised)':'var(--surface)'}"/><line x1="0" x2="${layout.width}" y1="${r.y+layout.rowHeight}" y2="${r.y+layout.rowHeight}" stroke="var(--line)"/><text x="8" y="${r.y+15}" fill="var(--muted)" font-size="11">${r.name}</text>`).join('')}${layout.ticks.map(t=>`<line x1="${t.x}" x2="${t.x}" y1="25" y2="${layout.height}" stroke="var(--line)"/><text x="${t.x}" y="18" text-anchor="${t.x>layout.width-50?'end':'start'}" fill="var(--muted)" font-size="11">${t.label}s</text>`).join('')}${layout.notes.map(n=>`<rect x="${n.measuredX}" y="${n.measuredY}" width="${n.measuredWidth}" height="${n.height}" fill="none" stroke="var(--muted)" stroke-dasharray="3 3" pointer-events="none"/><g data-melody-graph-note="${n.index}" data-pitch="${n.pitch}" data-fine-cents="${n.fineCents}" role="button" tabindex="${disabled?-1:0}" aria-disabled="${disabled}" aria-label="Edit detected note ${n.index+1}, ${n.name}${n.fineCents?`, ${n.fineCents>0?'+':''}${n.fineCents} cents`: ""}${n.excluded?', excluded':''}" style="cursor:${disabled?'default':'ns-resize'};touch-action:none"><title>Note ${n.index+1}: ${n.name}${n.fineCents?`, ${n.fineCents>0?'+':''}${n.fineCents} cents`: ""}${n.excluded?' (excluded)':''}</title><rect x="${n.x}" y="${n.y}" width="${n.width}" height="${n.height}" rx="3" fill="${n.excluded?'var(--hover)':'var(--action)'}" stroke="${n.excluded?'var(--muted)':'var(--action)'}"/>${n.width>35?`<text x="${n.x+5}" y="${n.y+13}" fill="${n.excluded?'var(--muted)':'var(--action-text)'}" font-size="11" pointer-events="none">${n.name}</text>`:''}</g>`).join('')}</svg></div>`;}
export function movedMelodyPitch(pitch,steps){const next=pitch+steps;if(!Number.isInteger(pitch)||pitch<0||pitch>127||!Number.isInteger(steps)||next<0||next>127)throw Error('Keep the note within MIDI pitch 0–127.');return next;}
export function bindMelodyGraph(root,{select,update,guard}){
 const svg=root.querySelector('[data-melody-graph]');if(!svg)return;
 for(const element of svg.querySelectorAll('[data-melody-graph-note]')){
  if(element.getAttribute('aria-disabled')==='true')continue;
  const index=Number(element.dataset.melodyGraphNote),pitch=Number(element.dataset.pitch),label=element.getAttribute('aria-label');let gesture=null,suppressClick=false;
  const restore=()=>{element.removeAttribute('transform');delete element.dataset.dragPitch;element.setAttribute('aria-label',label);};
  const cancel=()=>{if(!gesture)return;const id=gesture.id;gesture=null;suppressClick=true;restore();if(element.hasPointerCapture(id))element.releasePointerCapture(id);};
  const commit=next=>{update({operation:'edit',edits:[{index,pitch:next,start:null,duration:null,velocity:null,excluded:null}]});root.querySelector(`[data-melody-graph-note="${index}"]`)?.focus({preventScroll:true});};
  element.onpointerdown=e=>{if(e.button!==0||!e.isPrimary)return;e.preventDefault();e.stopPropagation();element.focus({preventScroll:true});suppressClick=false;gesture={id:e.pointerId,y:e.clientY,pitch,rowPixels:Number(svg.dataset.rowHeight)*svg.getBoundingClientRect().height/svg.viewBox.baseVal.height};element.setPointerCapture(e.pointerId);};
  element.onpointermove=e=>{if(!gesture||gesture.id!==e.pointerId)return;e.preventDefault();e.stopPropagation();const steps=Math.round((gesture.y-e.clientY)/gesture.rowPixels);try{gesture.pitch=movedMelodyPitch(pitch,steps);element.dataset.dragPitch=String(gesture.pitch);element.setAttribute('transform',`translate(0 ${-steps*Number(svg.dataset.rowHeight)})`);element.setAttribute('aria-label',`Move to ${noteName(gesture.pitch)}`);}catch{gesture.pitch=null;element.setAttribute('aria-label','Outside MIDI pitch range');}};
  element.onpointerup=guard(e=>{if(!gesture||gesture.id!==e.pointerId)return;e.preventDefault();e.stopPropagation();const next=gesture.pitch;gesture=null;suppressClick=true;restore();if(element.hasPointerCapture(e.pointerId))element.releasePointerCapture(e.pointerId);if(next===null)throw Error('Keep the note within MIDI pitch 0–127.');if(next!==pitch)commit(next);else select(index);});
  element.onpointercancel=cancel;element.onlostpointercapture=cancel;
  element.onclick=e=>{e.stopPropagation();if(suppressClick){suppressClick=false;return;}select(index);};
  element.onkeydown=guard(e=>{if(e.key==='Escape'&&gesture){e.preventDefault();e.stopPropagation();cancel();return;}if(gesture)return;if(['Enter',' '].includes(e.key)){e.preventDefault();e.stopPropagation();select(index);}else if(['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();e.stopPropagation();if(e.repeat)return;commit(movedMelodyPitch(pitch,(e.key==='ArrowUp'?1:-1)*(e.shiftKey?12:1)));}});
 }
}
