import {melodyGraphView,bindMelodyGraph} from './melody-graph.js';
import {z} from 'zod';
const values={pitch:z.number().int().min(0).max(127),start:z.number().finite().min(0),duration:z.number().finite().min(.001).max(120),velocity:z.number().finite().min(0).max(1),excluded:z.boolean()};
const editSchema=z.object({index:z.number().int().min(0).max(19999),...Object.fromEntries(Object.entries(values).map(([key,value])=>[key,value.nullable()]))}).strict();
export const melodyDraftActionSchema=z.object({operation:z.enum(['edit','reset','createMidi','retuneAudio']),edits:z.array(editSchema).max(128)}).strict();
export const melodyDraftContextSchema=z.object({sessionId:z.string().min(1),revision:z.number().int().nonnegative(),regionId:z.string().min(1).max(100),token:z.string().uuid(),notes:z.array(z.object({index:z.number().int().min(0),...values}).strict()).max(128)}).strict();
export function melodyDraftNotes(analysis){return analysis.notes.map((note,index)=>({...note,...analysis.edits?.[index]}));}
export function melodyDraftContext(session,analysis){if(!analysis?.token||analysis.sessionId!==session.id||analysis.revision!==session.revision)return undefined;const start=analysis.page??0;return {sessionId:session.id,revision:session.revision,regionId:analysis.regionId,token:analysis.token,notes:melodyDraftNotes(analysis).slice(start,start+128).map((n,i)=>({index:start+i,pitch:n.pitch,start:n.start,duration:n.duration,velocity:n.velocity,excluded:n.excluded??false}))};}
export function validateMelodyDraftAction(session,context,value){
 const c=melodyDraftContextSchema.parse(context),action=melodyDraftActionSchema.parse(value),region=session.tracks.filter(t=>t.kind==='audio').flatMap(t=>t.regions).find(r=>r.id===c.regionId);
 if(c.sessionId!==session.id||c.revision!==session.revision||!region)throw Error('The melody draft changed. Analyze it again.');
 if(new Set(c.notes.map(n=>n.index)).size!==c.notes.length)throw Error('Invalid melody draft note indices.');
 if(action.operation!=='edit'&&action.edits.length)throw Error('Choose corrections or reset/create, not both.');
 if(action.operation==='edit'&&!action.edits.length)throw Error('Choose notes to correct.');
 const seen=new Set();for(const edit of action.edits){const note=c.notes.find(n=>n.index===edit.index);if(!note||seen.has(edit.index))throw Error('Choose distinct notes shown in the captured melody draft.');seen.add(edit.index);const updated={...note,...Object.fromEntries(Object.entries(edit).filter(([,value])=>value!==null))};if(updated.start+updated.duration>region.duration+1e-8)throw Error('Corrected note must stay inside the source region.');}
 return action;
}
export function updateMelodyDraft(session,analysis,value,context=melodyDraftContext(session,analysis)){
 if(!analysis||context?.token!==analysis.token)throw Error('The melody draft changed. Try again.');
 const action=validateMelodyDraftAction(session,context,value);if(['createMidi','retuneAudio'].includes(action.operation))return analysis;
 const edits=action.operation==='reset'?{}:structuredClone(analysis.edits??{});
 for(const edit of action.edits){const patch=Object.fromEntries(Object.entries(edit).filter(([key,value])=>key!=='index'&&value!==null));edits[edit.index]={...edits[edit.index],...patch};}
 return {...analysis,edits,token:crypto.randomUUID()};
}
export function melodyDraftTable(analysis,disabled){
 const start=analysis.page??0,notes=melodyDraftNotes(analysis),locked=disabled?'disabled':'';
 return `<p>${notes.filter(n=>!n.excluded).length} of ${notes.length} notes included. Corrections stay in this draft until you create MIDI or render tuned audio.</p><div class="button-row"><button data-melody-reset ${locked}>Reset corrections</button><button data-melody-page="${Math.max(0,start-128)}" ${disabled||start===0?'disabled':''}>Previous notes</button><button data-melody-page="${start+128}" ${disabled||start+128>=notes.length?'disabled':''}>Next notes</button><span>Notes ${start+1}–${Math.min(start+128,notes.length)}</span></div>${melodyGraphView(analysis,notes,disabled)}<div style="max-height:320px;overflow:auto"><table><thead><tr><th>Note</th><th>Start · s</th><th>Length · s</th><th>Measured cents</th><th>Measured confidence</th><th></th></tr></thead><tbody>${notes.slice(start,start+128).map((n,i)=>{const original=analysis.notes[start+i];return `<tr><td>${['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'][n.pitch%12]}${Math.floor(n.pitch/12)-1}${n.excluded?' · excluded':''}${analysis.edits?.[start+i]?' · corrected':''}</td><td>${n.start.toFixed(3)}</td><td>${n.duration.toFixed(3)}</td><td>${original.cents.toFixed(0)}</td><td>${Math.round(original.confidence*100)}%</td><td><button data-melody-edit="${start+i}" ${locked}>Edit note ${start+i+1}</button></td></tr>`;}).join('')}</tbody></table></div><form data-melody-note-form hidden><h4 data-melody-edit-title></h4><div class="button-row"><label>MIDI pitch<input name="pitch" type="number" min="0" max="127" step="1" required></label><label>Start · seconds<input name="start" type="number" min="0" step="any" required></label><label>Length · seconds<input name="duration" type="number" min=".001" max="120" step="any" required></label><label>Velocity<input name="velocity" type="number" min="0" max="1" step="any" required></label><label><input name="excluded" type="checkbox">Exclude note</label></div><button ${locked}>Apply correction</button><button type="button" data-melody-edit-cancel>Cancel</button></form>`;
}
export function bindMelodyDraft(root,{analysis,update,page,guard}){if(!analysis)return;const form=root.querySelector('[data-melody-note-form]');if(!form)return;const select=index=>{const note=melodyDraftNotes(analysis)[index];form.dataset.index=index;form.hidden=false;form.querySelector('[data-melody-edit-title]').textContent=`Correct note ${index+1}`;for(const key of ['pitch','start','duration','velocity'])form.elements.namedItem(key).value=note[key];form.elements.namedItem('excluded').checked=Boolean(note.excluded);form.elements.namedItem('pitch').focus();};for(const button of root.querySelectorAll('[data-melody-edit]'))button.onclick=()=>select(Number(button.dataset.melodyEdit));bindMelodyGraph(root,{select,update,guard});form.onsubmit=guard(event=>{event.preventDefault();update({operation:'edit',edits:[{index:Number(form.dataset.index),...Object.fromEntries(['pitch','start','duration','velocity'].map(key=>[key,form.elements.namedItem(key).valueAsNumber])),excluded:form.elements.namedItem('excluded').checked}]});});form.querySelector('[data-melody-edit-cancel]').onclick=()=>{form.hidden=true;};root.querySelector('[data-melody-reset]').onclick=guard(()=>update({operation:'reset',edits:[]}));for(const button of root.querySelectorAll('[data-melody-page]'))button.onclick=guard(()=>page(Number(button.dataset.melodyPage)));}
