import {createLiveLoudness,updateLiveLoudness} from './live-loudness.js';
export function samplePeak(samples){let peak=0;for(const value of samples)peak=Math.max(peak,Math.abs(value));return peak;}
export const peakDb=value=>value>0?20*Math.log10(value):-Infinity;
export function createLevelMeters(context){
 const entries=new Map();let closed=false;
 function add(id,source,loudnessOptions){const split=context.createChannelSplitter(2),sink=context.createGain();sink.gain.value=0;sink.connect(context.destination);source.connect(split);const analysers=[0,1].map(channel=>{const a=context.createAnalyser();a.fftSize=2048;split.connect(a,channel);a.connect(sink);return a;});entries.set(id,{loudness:loudnessOptions?createLiveLoudness(context,source,loudnessOptions):null,isMaster:Boolean(loudnessOptions),source,split,sink,analysers,data:new Float32Array(2048),held:0});}
 return {add,read(){const values=new Map();if(closed)return values;for(const [id,m]of entries){const peaks=m.analysers.map(a=>{a.getFloatTimeDomainData(m.data);return samplePeak(m.data);});m.held=Math.max(m.held,...peaks);values.set(id,{left:peaks[0],right:peaks[1],peak:m.held,...(m.isMaster?{loudness:m.loudness?.read()||{unavailable:true}}:{})});}return values;},reset(id){const entry=entries.get(id);if(entry)entry.held=0;},stop(){if(closed)return;closed=true;for(const m of entries.values()){m.loudness?.stop();m.source.disconnect(m.split);m.split.disconnect();m.sink.disconnect();m.analysers.forEach(a=>a.disconnect());}entries.clear();}};
}
export function meterView(id,name,esc){return `<div class="daw-level-meter" data-level-meter="${id}"><div><meter min="-60" max="0" value="-60" aria-label="${esc(name)} left level"></meter><meter min="-60" max="0" value="-60" aria-label="${esc(name)} right level"></meter></div><output>—</output><button type="button" data-peak-reset="${id}" title="Reset held sample peak">Reset peak</button></div>`;}
export function updateMeters(root,values){updateLiveLoudness(root,values);for(const el of root?.querySelectorAll('[data-level-meter]')||[]){const value=values?.get(el.dataset.levelMeter),meters=el.querySelectorAll('meter');meters[0].value=Math.max(-60,Math.min(0,peakDb(value?.left||0)));meters[1].value=Math.max(-60,Math.min(0,peakDb(value?.right||0)));const db=peakDb(value?.peak||0);el.querySelector('output').textContent=value?`${Number.isFinite(db)?db.toFixed(1):'−∞'} dBFS peak`:'—';el.classList.toggle('clipped',Boolean(value&&value.peak>=1));}}
