import {midiOutputPlan} from './midi-output-plan.js';
export function createMidiOutput({session,position,beforePlay,onChange,onPosition=()=>{},requestAccess=()=>navigator.requestMIDIAccess({sysex:false}),clock=()=>performance.now(),schedule=setInterval,unschedule=clearInterval}){
 let access=null,outputId='',trackId='',port=null,timer=null,plan=null,index=0,base=0,lastTick=0,epoch=0,opening=false,disposed=false,notice='';const channels=new Set();
 const outputs=()=>access?[...access.outputs.values()].filter(p=>p.state==='connected'):[];
 const changed=()=>{if(!disposed)onChange();};
 function stop(reason='MIDI output stopped.'){
  if(!port&&!plan&&!opening)return;epoch++;opening=false;if(timer!==null)unschedule(timer);timer=null;
  if(port){try{port.clear();}catch{}for(const channel of channels)for(const cc of [64,123,120])try{port.send([0xb0|channel,cc,0]);}catch{}Promise.resolve(port.close()).catch(()=>{});}
  port=null;plan=null;channels.clear();notice=reason;
 }
 function stateChange(){if(port&&port.state!=='connected')stop('MIDI output disconnected.');if(!outputs().some(p=>p.id===outputId))outputId=outputs()[0]?.id||'';changed();}
 async function connect(){if(opening||plan)return;opening=true;const token=++epoch;notice='Requesting MIDI output access…';changed();try{const next=await requestAccess();if(disposed||epoch!==token)return;access?.removeEventListener('statechange',stateChange);access=next;access.addEventListener('statechange',stateChange);outputId=outputs()[0]?.id||'';notice=outputId?'MIDI output ready.':'Connect a MIDI output device.';}catch{if(epoch===token)notice='MIDI output access is unavailable or was denied.';}finally{if(epoch===token){opening=false;changed();}}}
 function tick(){if(!plan||!port)return;const now=clock();if(now-lastTick>500){stop('MIDI output stopped after a timing interruption. Restart from the playhead.');changed();return;}lastTick=now;try{while(index<plan.messages.length&&base+(plan.messages[index].time-plan.start)*1000<=now+100){const m=plan.messages[index++];channels.add(m.bytes[0]&15);port.send(m.bytes,base+(m.time-plan.start)*1000);}onPosition(Math.min(plan.end,plan.start+Math.max(0,now-base)/1000));if(now>=base+(plan.end-plan.start)*1000+20){stop('MIDI output finished.');changed();}}catch{stop('MIDI output failed or disconnected.');changed();}}
 async function play(){if(opening||plan)return;const prepared=midiOutputPlan(session(),trackId,position()),output=outputs().find(p=>p.id===outputId);if(!output)throw Error('Choose a connected MIDI output.');beforePlay();const token=++epoch;opening=true;notice='Opening MIDI output…';changed();try{await output.open();if(disposed||epoch!==token){if(port!==output)await output.close();return;}if(output.state!=='connected')throw Error('MIDI output disconnected.');port=output;plan=prepared;index=0;base=clock()+50;lastTick=clock();notice='Playing on '+(output.name||'MIDI output');opening=false;tick();if(plan)timer=schedule(tick,25);}catch(error){if(epoch===token){stop(error.message);changed();}}finally{if(epoch===token){opening=false;changed();}}}
 return {get active(){return Boolean(plan||opening);},get playing(){return Boolean(plan);},connect,play,stop,
  activate(){disposed=false;},dispose(){disposed=true;stop();access?.removeEventListener('statechange',stateChange);access=null;},
  view(esc,disabled=false){const tracks=session().tracks.filter(t=>t.kind==='midi');if(!tracks.some(t=>t.id===trackId))trackId=tracks[0]?.id||'';const off=disabled||opening||plan?'disabled':'';return `<section class="daw-midi-input"><div class="button-row"><strong>MIDI output</strong><button data-midi-output-connect ${off}>Connect output</button><label>Device<select data-midi-output-device ${off}>${outputs().length?outputs().map(p=>`<option value="${esc(p.id)}" ${p.id===outputId?'selected':''}>${esc(p.name||'MIDI output')}</option>`).join(''):'<option value="">No connected outputs</option>'}</select></label><label>Track<select data-midi-output-track ${off}>${tracks.length?tracks.map(t=>`<option value="${esc(t.id)}" ${t.id===trackId?'selected':''}>${esc(t.name)}</option>`).join(''):'<option value="">No instrument tracks</option>'}</select></label><button data-midi-output-play ${off||!outputId||!trackId?'disabled':''}>Play on device</button><button data-midi-output-stop ${!plan&&!opening?'disabled':''}>Stop device</button></div><p role="status">${esc(notice)}</p><p class="muted">Plays this track from the playhead using its MIDI channels, notes, and controller events. Browser instruments and mixer effects are not sent to the device. Stop or seek clears queued messages and releases notes.</p></section>`;},
  bind(root,guard){root.querySelector('[data-midi-output-connect]')?.addEventListener('click',guard(connect));root.querySelector('[data-midi-output-play]')?.addEventListener('click',guard(play));root.querySelector('[data-midi-output-stop]')?.addEventListener('click',()=>{stop();changed();});const d=root.querySelector('[data-midi-output-device]'),t=root.querySelector('[data-midi-output-track]');if(d)d.onchange=()=>{stop();outputId=d.value;changed();};if(t)t.onchange=()=>{stop();trackId=t.value;changed();};}
 };
}
