import {compileMidiControllers,upperMidiTime} from './midi-controller-timeline.js';
import {pitchBendTimeline,rpnControllers} from './pitch-bend-state.js';
import {regionBeatTiming} from './tempo-map.js';
import {z} from 'zod';
export const midiEventSchema=z.object({id:z.string().min(1).max(100).regex(/^[a-zA-Z0-9_-]+$/),start:z.number().finite().min(0).max(86400),channel:z.number().int().min(0).max(15).default(0),type:z.enum(['controlChange','pitchBend','programChange','channelPressure','polyPressure']),parameter:z.number().int().min(0).max(127).default(0),value:z.number().int().min(0).max(16383)}).superRefine((e,ctx)=>{if(e.type!=='pitchBend'&&e.value>127)ctx.addIssue({code:'custom',message:'This MIDI event value must be between 0 and 127.'});});
export function eventBytes(event){const c=event.channel||0;switch(event.type){case 'controlChange':return [0xb0|c,event.parameter,event.value];case 'pitchBend':return [0xe0|c,event.value&127,event.value>>7];case 'programChange':return [0xc0|c,event.value];case 'channelPressure':return [0xd0|c,event.value];case 'polyPressure':return [0xa0|c,event.parameter,event.value];default:throw Error('Unknown MIDI event.');}}
export function eventFromBytes(type,channel,a,b,start){const names={10:'polyPressure',11:'controlChange',12:'programChange',13:'channelPressure',14:'pitchBend'};if(!names[type])return null;return {id:crypto.randomUUID(),type:names[type],channel,start,parameter:type===10||type===11?a:0,value:type===14?a+(b<<7):type===12||type===13?a:b};}
export function chasedEvents(events,at){
 const ordered=[...events].sort((a,b)=>a.start-b.start),past=ordered.filter(e=>e.start<at),key=e=>`${e.channel}:${e.type}:${e.parameter}`;
 const boundary=new Set(events.filter(e=>e.start===at).map(key));
 const statefulChannels=new Set(past.filter(e=>e.type==='controlChange'&&(rpnControllers.has(e.parameter)||e.parameter===121)).map(e=>e.channel));
 const stateful=e=>statefulChannels.has(e.channel)&&(e.type==='pitchBend'||(e.type==='controlChange'&&(rpnControllers.has(e.parameter)||[11,64,121].includes(e.parameter))));
 const previous=new Map();for(const e of past)if(!stateful(e))previous.set(key(e),e);
 const history=past.filter(e=>stateful(e)&&!(e.type==='pitchBend'&&boundary.has(key(e))));
 return [...history,...[...previous.values()].filter(e=>!boundary.has(key(e)))].map(e=>({...e,id:crypto.randomUUID(),start:0}));
}
export function controllerValue(events,type,parameter,time,fallback){let value=fallback;for(const e of [...events].sort((a,b)=>a.start-b.start)){if(e.start>time)break;if(type==='controlChange'&&e.type==='controlChange'&&e.parameter===121&&[11,64].includes(parameter))value=parameter===11?127:0;if(e.type===type&&(parameter===null||e.parameter===parameter))value=e.value;}return value;}
export function scheduleMidiChannel(context,input,events,relative,when,nodes,compiled){
 const gain=context.createGain(),pan=context.createStereoPanner(),levels=(compiled??compileMidiControllers(events)).levels,index=upperMidiTime(levels,relative),initial=levels[index-1]??{gain:1,pan:0};gain.connect(pan).connect(input);nodes.push(gain,pan);
 gain.gain.setValueAtTime(initial.gain,when);pan.pan.setValueAtTime(initial.pan,when);let previous=initial;
 for(let i=index;i<levels.length;i++){const p=levels[i],at=when+p.time-relative;if(p.gain!==previous.gain)gain.gain.setValueAtTime(p.gain,at);if(p.pan!==previous.pan)pan.pan.setValueAtTime(p.pan,at);previous=p;}
 return gain;
}
export function schedulePitchBend(osc,events,localStart,when,end,range=2,compiledPoints){
 const points=compiledPoints??pitchBendTimeline(events,range),index=upperMidiTime(points,localStart);osc.detune.setValueAtTime(points[index-1]?.cents??0,when);
 for(let i=index;i<points.length&&points[i].time<end;i++){const p=points[i];osc.detune.setValueAtTime(p.cents,when+p.time-localStart);}
}
export function sustainedEnd(note,events,regionDuration){const end=note.start+note.duration;if(controllerValue(events,'controlChange',64,end,0)<64)return end;return Math.min(regionDuration,[...events].sort((a,b)=>a.start-b.start).find(e=>e.type==='controlChange'&&e.start>end&&(e.parameter===121||(e.parameter===64&&e.value<64)))?.start??regionDuration);}
export function midiEventsView(region,tempo,esc){const timing=regionBeatTiming(region,tempo);return `<details class="daw-midi-events"><summary>MIDI events · ${(region.events||[]).length}</summary><p class="muted">Volume (CC7), expression (CC11), pan (CC10), sustain (CC64) pitch bend, and RPN channel tuning affect playback. Program and pressure events are preserved for MIDI export.</p><label>Event<select data-event-select><option value="">New event</option>${(region.events||[]).map(e=>`<option value="${esc(e.id)}">Beat ${(timing.beatAtTime(e.start)).toFixed(2)} · Ch ${e.channel+1} · ${esc(e.type)} ${e.parameter}: ${e.value}</option>`).join('')}</select></label><form data-event-editor><label>Type<select name="type">${['controlChange','pitchBend','programChange','channelPressure','polyPressure'].map(type=>`<option>${type}</option>`).join('')}</select></label><label>Beat<input type="number" name="start" min="0" max="${timing.beatAtTime(region.duration)}" step="any" value="0" required></label><label>Channel<input type="number" name="channel" min="1" max="16" step="1" value="1" required></label><label>Controller / note<input type="number" name="parameter" min="0" max="127" step="1" value="7" required></label><label>Value<input type="number" name="value" min="0" max="127" step="1" value="127" required></label><button type="submit" data-event-save>Add event</button><button type="button" data-event-delete disabled>Delete event</button></form></details>`;}
export function bindMidiEvents(root,{region,tempo,session,execute,guard}){const select=root.querySelector('[data-event-select]'),form=root.querySelector('[data-event-editor]');if(!select||!form)return;const timing=regionBeatTiming(region,session??tempo),updateBounds=()=>{form.elements.value.max=form.elements.type.value==='pitchBend'?16383:127;form.elements.parameter.disabled=!['controlChange','polyPressure'].includes(form.elements.type.value);};select.onchange=()=>{const event=region.events.find(e=>e.id===select.value);if(event){for(const key of ['type','parameter','value'])form.elements[key].value=event[key];form.elements.channel.value=event.channel+1;form.elements.start.value=timing.beatAtTime(event.start);}else form.reset();root.querySelector('[data-event-save]').textContent=event?'Update event':'Add event';root.querySelector('[data-event-delete]').disabled=!event;updateBounds();};form.elements.type.onchange=()=>{form.elements.value.value=form.elements.type.value==='pitchBend'?8192:127;updateBounds();};form.onsubmit=guard(e=>{e.preventDefault();const values={type:form.elements.type.value,start:timing.timeAtBeat(Number(form.elements.start.value)),channel:Number(form.elements.channel.value)-1,parameter:form.elements.parameter.disabled?0:Number(form.elements.parameter.value),value:Number(form.elements.value.value)};execute([{op:select.value?'event.set':'event.add',target:select.value||region.id,values}],'Saved MIDI event');});root.querySelector('[data-event-delete]').onclick=guard(()=>execute([{op:'event.delete',target:select.value}],'Deleted MIDI event'));}
