import {z} from 'zod';
import {selectedMidiNotes} from './note-selection.js';
const selection={noteId:z.string().optional(),noteIds:z.string().max(2020000).optional()};
const splitOptions=z.object({...selection,time:z.number().finite().min(0).max(86400)}).strict();
const divideOptions=z.object({...selection,parts:z.number().int().min(2).max(128),gate:z.number().finite().min(.01).max(1).default(1)}).strict();
export function splitNotesPlan(region,values,mode='split'){
 if(!['split','divide'].includes(mode))throw Error('Choose split or divide.');const v=(mode==='split'?splitOptions:divideOptions).parse(values),chosen=selectedMidiNotes(region,v);if(!chosen.length)throw Error('Add or select notes to split.');
 if(mode==='split'&&v.time>region.duration)throw Error('Choose a split point inside the region.');
 const affected=mode==='split'?chosen.filter(n=>n.start<v.time&&n.start+n.duration>v.time):chosen,parts=mode==='split'?2:v.parts,added=affected.length*(parts-1);
 if(region.notes.length+added>20000)throw Error('Splitting would exceed the 20,000-note region limit.');
 const changes=affected.map(n=>({id:n.id,pieces:mode==='split'?[{start:n.start,duration:v.time-n.start},{start:v.time,duration:n.start+n.duration-v.time}]:Array.from({length:parts},(_,i)=>{const start=n.start+n.duration*i/parts,end=i===parts-1?n.start+n.duration:n.start+n.duration*(i+1)/parts;return {start,duration:(end-start)*v.gate};})}));
 if(changes.some(c=>c.pieces.some(p=>!Number.isFinite(p.duration)||p.duration<=0)))throw Error('These note sections are too short to represent.');
 return {changes,added,total:region.notes.length+added};
}
const state=settings=>settings.splitTools??={mode:'split',scope:'selected',time:1,parts:2,gate:100};
export function splitNotesView(settings){const s=state(settings);return `<details class="daw-note-split"><summary>Split &amp; divide notes</summary><form data-note-split class="button-row"><label>Action<select name="mode"><option value="split" ${s.mode==='split'?'selected':''}>Split at a beat</option><option value="divide" ${s.mode==='divide'?'selected':''}>Divide into equal parts</option></select></label><label>Apply to<select name="scope"><option value="selected" ${s.scope==='selected'?'selected':''}>Selected notes</option><option value="region" ${s.scope==='region'?'selected':''}>All notes in region</option></select></label><label>Split · beat<input name="time" type="number" min="0" step="any" value="${Number.isFinite(s.time)?s.time:''}" required></label><button type="button" data-split-playhead>Use playhead</button><label>Parts<input name="parts" type="number" min="2" max="128" step="1" value="${Number.isFinite(s.parts)?s.parts:''}" required></label><label>Note length · % of each part<input name="gate" type="number" min="1" max="100" step="any" value="${Number.isFinite(s.gate)?s.gate:''}" required></label><button type="submit">Split notes</button></form><output data-note-split-preview></output><p class="muted">Split cuts only notes crossing the chosen beat. Divide retriggers each chosen note in equal time slots; a shorter length leaves gaps. Pitch, velocity, channel and mute are retained. Controller events stay in place, so sustain may bridge the gaps. Undo restores the originals. You can also choose Split notes in the piano-roll Tool menu and click a note; selected notes crossing that time split together. Hold Shift to bypass snap.</p></details>`;}
export function bindSplitNotes(root,{region,tempo,settings,execute,guard,getPosition}){
 const form=root.querySelector('[data-note-split]');if(!form)return;const s=state(settings),button=form.querySelector('[type=submit]'),f=form.elements;
 const values=()=>({...(s.scope==='selected'?{noteIds:(settings.selectedIds||[]).join(',')}:{}),...(s.mode==='split'?{time:s.time*60/tempo}:{parts:s.parts,gate:s.gate/100})});
 const update=()=>{for(const key of ['scope','mode'])s[key]=f[key].value;for(const key of ['time','parts','gate'])s[key]=f[key].value===''?NaN:Number(f[key].value);f.time.disabled=s.mode!=='split';f.parts.disabled=f.gate.disabled=s.mode!=='divide';root.querySelector('[data-split-playhead]').disabled=s.mode!=='split';button.textContent=s.mode==='split'?'Split notes':'Divide notes';try{const p=splitNotesPlan(region,values(),s.mode);root.querySelector('[data-note-split-preview]').textContent=`${p.changes.length} notes will change; ${p.added} notes will be added (${p.total} total).`;button.disabled=!p.changes.length;}catch(e){root.querySelector('[data-note-split-preview]').textContent=e.message;button.disabled=true;}};
 form.oninput=update;form.onchange=update;root.querySelector('[data-split-playhead]').onclick=guard(()=>{if(!getPosition)return;f.time.value=(getPosition()-region.start)*tempo/60;update();});form.onsubmit=guard(e=>{e.preventDefault();update();if(!button.disabled)execute([{op:s.mode==='split'?'notes.split':'notes.divide',target:region.id,values:values()}],s.mode==='split'?'Split MIDI notes':'Divided MIDI notes');});update();
}
