import {z} from 'zod';
import {samplerGroupsSchema,validateSamplerGroups} from './sampler-groups.js';
import {samplerZonesSchema} from './sampler-zones.js';
import {samplerArticulationsSchema} from './sampler-articulations.js';
import {midiSwitchSchema,midiSwitchesSchema} from './midi-switches.js';
import {samplerTuningSchema} from './sampler-tuning.js';
import {samplerFilterSchema} from './sampler-filter.js';
import {pitchBendRangeSchema} from './pitch-bend.js';
const id=z.string().min(1).max(100).regex(/^[a-zA-Z0-9_-]+$/),name=z.string().trim().min(1).max(100),time=z.number().finite().min(0).max(86400);
export const samplerSettingsSchema=z.object({instrument:z.literal('sampler'),pitchBendRange:pitchBendRangeSchema,sampleAssetId:id.nullable().default(null),sampleRoot:z.number().int().min(0).max(127).default(60),sampleAttack:z.number().finite().min(0).max(10).default(.005),sampleDecay:z.number().finite().min(0).max(10).default(0),sampleSustain:z.number().finite().min(0).max(1).default(1),sampleRelease:z.number().finite().min(0).max(30).default(.02),...samplerTuningSchema.shape,...samplerFilterSchema.shape,sampleLoop:z.boolean().default(false),sampleLoopStart:time.default(0),sampleLoopEnd:time.nullable().default(null),sampleGroups:samplerGroupsSchema.optional(),sampleZones:samplerZonesSchema.optional(),sampleArticulations:samplerArticulationsSchema.optional(),midiSwitches:midiSwitchesSchema.optional(),inputArticulation:midiSwitchSchema.nullable().optional()}).strict().superRefine((s,ctx)=>{validateSamplerGroups(s,ctx);if(s.sampleLoopEnd!==null&&s.sampleLoopEnd<=s.sampleLoopStart)ctx.addIssue({code:'custom',message:'Sampler loop end must follow its start.'});if(!s.sampleAssetId&&!s.sampleZones?.length&&!s.sampleArticulations?.length)ctx.addIssue({code:'custom',message:'Assign a sample before saving an instrument preset.'});});
export const samplerPresetSchema=z.object({id,name,settings:samplerSettingsSchema}).strict();
export const samplerPresetsSchema=z.array(samplerPresetSchema).max(32).default([]).refine(p=>new Set(p.map(x=>x.id)).size===p.length,'Sampler preset IDs must be unique.');
export function samplerSnapshot(track){if(track?.kind!=='midi'||track.instrument!=='sampler')throw Error('Choose a sampler instrument track.');return samplerSettingsSchema.parse(Object.fromEntries(Object.keys(samplerSettingsSchema.shape).filter(k=>track[k]!==undefined).map(k=>[k,structuredClone(track[k])])));}
export const samplerPresetImportLimit=1024*1024;
export function parseSamplerPresetImport(json){if(typeof json!=='string'||new TextEncoder().encode(json).length>samplerPresetImportLimit)throw Error('Sampler preset settings exceed 1 MB.');let data;try{data=JSON.parse(json);}catch{throw Error('Invalid sampler preset JSON.');}return samplerPresetSchema.parse(data);}
export function editSamplerPreset(session,op,target,values){const presets=session.samplerPresets;
 if(op==='samplerPreset.import'){if(target!==undefined&&target!==session.id)throw Error('Import sampler presets into the current project.');const {json}=z.object({json:z.string().max(samplerPresetImportLimit)}).strict().parse(values);if(presets.length>=32)throw Error('A project can save up to 32 sampler presets.');const preset=parseSamplerPresetImport(json),names=new Set(presets.map(p=>p.name.toLowerCase()));let candidate=preset.name;for(let i=2;names.has(candidate.toLowerCase());i++){const suffix=` (${i})`;candidate=preset.name.slice(0,100-suffix.length)+suffix;}preset.name=candidate;presets.push(preset);return;}

 if(op==='samplerPreset.save'||op==='samplerPreset.update'){const v=(op==='samplerPreset.save'?z.object({id:id.optional(),name}):z.object({presetId:id})).strict().parse(values),settings=samplerSnapshot(session.tracks.find(t=>t.id===target));if(op==='samplerPreset.update'){const preset=presets.find(p=>p.id===v.presetId);if(!preset)throw Error('Choose a saved sampler preset.');preset.settings=settings;return;}if(presets.length>=32)throw Error('A project can save up to 32 sampler presets.');if(presets.some(p=>p.name.toLowerCase()===v.name.toLowerCase()))throw Error('Choose a different preset name.');presets.push(samplerPresetSchema.parse({id:v.id??crypto.randomUUID(),name:v.name,settings}));return;}
 if(op==='samplerPreset.apply'){const {presetId}=z.object({presetId:id}).strict().parse(values),preset=presets.find(p=>p.id===presetId),track=session.tracks.find(t=>t.id===target);if(!preset)throw Error('Choose a saved sampler preset.');if(track?.kind!=='midi')throw Error('Apply sampler presets to an instrument track.');for(const key of Object.keys(samplerSettingsSchema.shape))delete track[key];Object.assign(track,structuredClone(preset.settings));return;}
 const preset=presets.find(p=>p.id===target);if(!preset)throw Error('Choose a saved sampler preset.');if(op==='samplerPreset.rename'){const v=z.object({name}).strict().parse(values);if(presets.some(p=>p.id!==target&&p.name.toLowerCase()===v.name.toLowerCase()))throw Error('Choose a different preset name.');preset.name=v.name;}else if(op==='samplerPreset.delete'){z.object({}).strict().parse(values);session.samplerPresets=presets.filter(p=>p.id!==target);}else throw Error('Unknown sampler preset operation.');
}
export function samplerPresetsView(session,track,esc){if(track?.kind!=='midi')return '';return `<details data-sampler-presets><summary>Sampler instrument presets</summary><p class="muted">Save this instrument’s samples, zones, groups and articulations with the project. Apply a saved instrument to this track; notes, effects, volume and routing stay unchanged.</p><label>Saved instrument<select data-sampler-preset><option value="">Choose a preset</option>${session.samplerPresets.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('')}</select></label><div class="button-row"><button type="button" data-sampler-preset-apply>Apply preset</button><button type="button" data-sampler-preset-update>Update from this track</button><button type="button" data-sampler-preset-delete>Delete preset</button><button type="button" data-sampler-preset-export>Export instrument</button><button type="button" data-sampler-preset-import>Import instrument</button><input type="file" data-sampler-preset-file accept=".zip,application/zip" hidden></div><form data-sampler-preset-save><label>Preset name<input name="name" maxlength="100" required></label><div class="button-row"><button>Save new preset</button><button type="button" data-sampler-preset-rename>Rename selected preset</button></div></form><small>Presets retain source files in project storage and portable archives. Updating a preset does not change tracks that already use a copy.</small></details>`;}
export function bindSamplerPresets(root,{session,track,state={},execute,guard,blocked,exportFile,importFile}){const scope=root.querySelector('[data-sampler-presets]');if(!scope)return;const select=scope.querySelector('[data-sampler-preset]'),form=scope.querySelector('form'),button=action=>scope.querySelector(`[data-sampler-preset-${action}]`);select.value=state.id??'';const chosen=()=>{const preset=session.samplerPresets.find(p=>p.id===select.value);if(!preset)throw Error('Choose a sampler preset first.');return preset;},ready=()=>{if(blocked())throw Error('Finish the current operation before editing presets.');},refresh=()=>{state.id=select.value;for(const action of ['apply','update','delete','rename','export'])button(action).disabled=!select.value;if(select.value)form.elements.namedItem('name').value=chosen().name;};select.onchange=refresh;refresh();button('export').onclick=guard(async()=>{ready();await exportFile(chosen());});const fileInput=scope.querySelector('[data-sampler-preset-file]');button('import').onclick=guard(()=>{ready();fileInput.click();});fileInput.onchange=guard(async()=>{const file=fileInput.files?.[0];fileInput.value='';if(!file)return;ready();await importFile(file);});form.onsubmit=guard(e=>{e.preventDefault();ready();const id=crypto.randomUUID();state.id=id;execute([{op:'samplerPreset.save',target:track.id,values:{id,name:form.elements.namedItem('name').value}}],'Saved sampler preset',session.revision);});for(const action of ['apply','update'])button(action).onclick=guard(()=>{ready();execute([{op:`samplerPreset.${action}`,target:track.id,values:{presetId:chosen().id}}],action==='apply'?'Applied sampler preset':'Updated sampler preset',session.revision);});button('delete').onclick=guard(()=>{ready();execute([{op:'samplerPreset.delete',target:chosen().id}],'Deleted sampler preset',session.revision);});button('rename').onclick=guard(()=>{ready();execute([{op:'samplerPreset.rename',target:chosen().id,values:{name:form.elements.namedItem('name').value}}],'Renamed sampler preset',session.revision);});}
