import {groupPlaybackSchema,groupPlaybackPatch,validateGroupRanges,groupShapingView,loadGroupShaping,readGroupShaping} from './sampler-group-shaping.js';
import {z} from 'zod';
import {zoneVoiceSchema,zoneVoicePatchSchema} from './sampler-zone-voice.js';
const id=z.string().min(1).max(100),name=z.string().trim().min(1).max(100);
export const samplerGroupSchema=zoneVoiceSchema.extend({...groupPlaybackSchema.shape,id,name,mute:z.boolean().default(false),solo:z.boolean().default(false)}).strict().superRefine(validateGroupRanges);
export const samplerGroupsSchema=z.array(samplerGroupSchema).max(64).refine(groups=>new Set(groups.map(g=>g.id)).size===groups.length,'Sample group IDs must be unique.');
export function editSamplerGroup(track,op,values){if(track?.kind!=='midi')throw Error('Choose an instrument track.');const groups=track.sampleGroups??[];if(op==='samplerGroup.set'){const v=zoneVoicePatchSchema.extend({...groupPlaybackPatch.shape,id,name:name.optional(),mute:z.boolean().optional(),solo:z.boolean().optional()}).strict().parse(values),group=samplerGroupSchema.parse({...groups.find(g=>g.id===v.id),...v});track.sampleGroups=samplerGroupsSchema.parse([...groups.filter(g=>g.id!==v.id),group]);return;}const v=z.object({id,...(op==='samplerGroup.members'?{zoneIds:z.string().max(20000)}:{})}).strict().parse(values);if(!groups.some(g=>g.id===v.id))throw Error('Choose an existing sample group.');if(op==='samplerGroup.delete'){track.sampleGroups=groups.filter(g=>g.id!==v.id);for(const zone of track.sampleZones??[])if(zone.groupId===v.id)zone.groupId=null;return;}let ids;try{ids=z.array(id).max(128).refine(a=>new Set(a).size===a.length,'Choose each zone once.').parse(JSON.parse(v.zoneIds));}catch{throw Error('Choose a valid list of sample-zone IDs.');}if(ids.some(id=>!track.sampleZones?.some(z=>z.id===id)))throw Error('A selected sample zone no longer exists.');for(const zone of track.sampleZones??[]){if(ids.includes(zone.id))zone.groupId=v.id;else if(zone.groupId===v.id)zone.groupId=null;}}
export const groupForZone=(track,zone)=>track.sampleGroups?.find(g=>g.id===zone.groupId);
export const groupsSoloed=track=>(track.sampleGroups??[]).some(g=>g.solo);
export function samplerGroupAudible(track,zone,note){const group=groupForZone(track,zone);if(group?.mute||(groupsSoloed(track)&&!group?.solo))return false;if(!group)return true;const low=Math.max(zone.keyLow,group.keyLow??0),high=Math.min(zone.keyHigh,group.keyHigh??127),soft=Math.max(zone.velocityLow,group.velocityLow??1),hard=Math.min(zone.velocityHigh,group.velocityHigh??127);if(low>high||soft>hard)return false;if(!note)return true;const velocity=Math.max(1,Math.min(127,Math.round(note.velocity*127)));return note.pitch>=low&&note.pitch<=high&&velocity>=soft&&velocity<=hard;}
export function validateSamplerGroups(track,ctx){const ids=new Set((track.sampleGroups??[]).map(g=>g.id));if((track.sampleZones??[]).some(z=>z.groupId&&!ids.has(z.groupId)))ctx.addIssue({code:'custom',message:'Sample zones must reference an existing group on their track.'});}
export function samplerGroupsView(track,esc){if(track?.kind!=='midi')return '';return `<details data-sampler-groups><summary>Sample groups</summary><p class="muted">Balance, tune, mute or solo related zones together. Group settings preserve each zone’s own settings. Deleting a group keeps its zones.</p><form data-sampler-group><label>Group<select name="group"><option value="">New group</option>${(track.sampleGroups??[]).map(g=>`<option value="${esc(g.id)}">${esc(g.name)}</option>`).join('')}</select></label><label>Name<input name="name" maxlength="100" required value="Sample group"></label>${[['gainDb','Group level · dB',-60,24,'any'],['pan','Group pan · −1 left / 1 right',-1,1,'.01'],['tune','Group tune · semitones',-48,48,'1'],['fineTune','Group fine tune · cents',-100,100,'any']].map(([key,label,min,max,step])=>`<label>${label}<input name="${key}" type="number" value="0" min="${min}" max="${max}" step="${step}" required></label>`).join('')}<label>Mute group<input name="mute" type="checkbox"></label><label>Solo group<input name="solo" type="checkbox"></label>${groupShapingView()}<fieldset class="daw-sampler-group-members"><legend>Member zones</legend>${(track.sampleZones??[]).map(z=>`<label><input type="checkbox" data-group-zone="${esc(z.id)}">${esc(z.name)}</label>`).join('')||'<p class="muted">Create sample zones first, then assign them here.</p>'}</fieldset><div class="button-row"><button>Save sample group</button><button type="button" data-delete-sampler-group>Delete group</button></div></form></details>`;}
export function bindSamplerGroups(root,{track,state={},execute,guard}){const form=root.querySelector('[data-sampler-group]');if(!form)return;const f=form.elements,del=form.querySelector('[data-delete-sampler-group]');if(state.trackId!==track.id){state.trackId=track.id;state.id='';}const load=()=>{const g=track.sampleGroups?.find(g=>g.id===f.group.value);for(const [key,value]of Object.entries({name:'Sample group',gainDb:0,pan:0,tune:0,fineTune:0}))f.namedItem(key).value=g?.[key]??value;f.mute.checked=g?.mute??false;f.solo.checked=g?.solo??false;loadGroupShaping(form,g);for(const checkbox of form.querySelectorAll('[data-group-zone]'))checkbox.checked=Boolean(g&&track.sampleZones?.find(z=>z.id===checkbox.dataset.groupZone)?.groupId===g.id);state.id=f.group.value;del.disabled=!g;};f.group.value=state.id??'';f.group.onchange=load;load();form.onsubmit=guard(e=>{e.preventDefault();const values={...readGroupShaping(form),id:f.group.value||crypto.randomUUID(),name:f.namedItem('name').value,mute:f.mute.checked,solo:f.solo.checked};for(const key of ['gainDb','pan','tune','fineTune'])values[key]=Number(f.namedItem(key).value);const zoneIds=[...form.querySelectorAll('[data-group-zone]:checked')].map(c=>c.dataset.groupZone);state.id=values.id;execute([{op:'samplerGroup.set',target:track.id,values},{op:'samplerGroup.members',target:track.id,values:{id:values.id,zoneIds:JSON.stringify(zoneIds)}}],'Saved sample group');});del.onclick=guard(()=>execute([{op:'samplerGroup.delete',target:track.id,values:{id:f.group.value}}],'Deleted group; sample zones kept'));}
