export function sceneGridSelection(session,selection={}) {
 const tracks=session.tracks.filter(t=>['audio','midi'].includes(t.kind));
 return {sceneId:session.scenes.find(s=>s.id===selection.sceneId)?.id??session.scenes[0]?.id,trackId:tracks.find(t=>t.id===selection.trackId)?.id??tracks[0]?.id};
}
export function scenesView(session,selection,esc,disabled=false) {
 const tracks=session.tracks.filter(t=>['audio','midi'].includes(t.kind)),active=sceneGridSelection(session,selection),scene=session.scenes.find(s=>s.id===active.sceneId),track=tracks.find(t=>t.id===active.trackId),cell=scene?.cells.find(c=>track?.regions.some(r=>r.id===c.regionId)),off=disabled?'disabled':'';
 return `<details id="daw-scenes" class="daw-scenes"><summary>Scenes</summary><p class="muted">Organize clips into scenes. Each scene holds one clip per track. Scene playback is not available yet.</p><form data-scene-create><label>Scene name<input name="name" placeholder="Verse" maxlength="100" required></label><button ${off} name="empty">Create scene</button><button ${off} name="selection">Save selected clips</button></form>${session.scenes.length?`<div class="daw-scene-scroll"><table><caption class="muted">Select a cell to assign a clip</caption><thead><tr><th scope="col">Track</th>${session.scenes.map(s=>`<th scope="col"><button type="button" data-scene-select="${s.id}" aria-pressed="${s.id===active.sceneId}">${esc(s.name)}</button></th>`).join('')}</tr></thead><tbody>${tracks.map(t=>`<tr><th scope="row">${esc(t.name)}</th>${session.scenes.map(s=>{const c=s.cells.find(c=>t.regions.some(r=>r.id===c.regionId)),r=t.regions.find(r=>r.id===c?.regionId);return `<td><button type="button" data-scene-cell="${s.id}" data-scene-track="${t.id}" aria-label="${esc(s.name)} / ${esc(t.name)}" aria-pressed="${s.id===active.sceneId&&t.id===active.trackId}"><span>${r?esc(r.name):'Choose clip'}</span>${r?`<small>${c.loop?'Loop':'One-shot'}</small>`:''}</button></td>`;}).join('')}</tr>`).join('')}</tbody></table></div>`:'<p class="muted">Create a scene, then assign clips from your tracks.</p>'}${scene?`<form data-scene-rename><label>Selected scene<input name="name" value="${esc(scene.name)}" maxlength="100" required></label><button ${off}>Rename scene</button><button type="button" data-scene-move="-1" ${off||session.scenes[0]===scene?'disabled':''}>Move left</button><button type="button" data-scene-move="1" ${off||session.scenes.at(-1)===scene?'disabled':''}>Move right</button><button type="button" data-scene-delete ${off}>Delete scene</button></form>`:''}${scene&&track?`<form data-scene-assign><strong>${esc(scene.name)} / ${esc(track.name)}</strong><label>Source clip<select name="regionId" required><option value="">Choose a clip</option>${track.regions.map(r=>`<option value="${r.id}" ${cell?.regionId===r.id?'selected':''}>${esc(r.name)}</option>`).join('')}</select></label><label><input type="checkbox" name="loop" ${cell?.loop!==false?'checked':''}> Loop clip</label><button ${off||!track.regions.length?'disabled':''}>Assign clip</button><button type="button" data-scene-clear ${off||!cell?'disabled':''}>Remove clip</button></form>`:''}</details>`;
}
export function bindScenes(root,{session,selection,select,ids,execute,guard,blocked=()=>false}) {
 const active=sceneGridSelection(session,selection),scene=session.scenes.find(s=>s.id===active.sceneId),track=session.tracks.find(t=>t.id===active.trackId);
 const run=commands=>{if(blocked())throw Error('Finish the current operation before editing scenes.');execute(commands,'Updated scenes');};
 root.querySelectorAll('[data-scene-cell]').forEach(b=>b.onclick=()=>select({sceneId:b.dataset.sceneCell,trackId:b.dataset.sceneTrack}));
 root.querySelectorAll('[data-scene-select]').forEach(b=>b.onclick=()=>select({...active,sceneId:b.dataset.sceneSelect}));
 const create=root.querySelector('[data-scene-create]');if(create)create.onsubmit=guard(e=>{e.preventDefault();const selected=e.submitter?.name==='selection';if(selected&&!ids.length)throw Error('Select clips in the arrangement first.');run([{op:'scene.add',values:{name:new FormData(create).get('name'),...(selected?{regionIds:ids.join(',')}:{})}}]);});
 const rename=root.querySelector('[data-scene-rename]');if(rename)rename.onsubmit=guard(e=>{e.preventDefault();run([{op:'scene.rename',target:scene.id,values:{name:new FormData(rename).get('name')}}]);});
 root.querySelector('[data-scene-delete]')?.addEventListener('click',guard(()=>run([{op:'scene.delete',target:scene.id,values:{}}])));
 root.querySelectorAll('[data-scene-move]').forEach(b=>b.onclick=guard(()=>run([{op:'scene.move',target:scene.id,values:{index:session.scenes.indexOf(scene)+Number(b.dataset.sceneMove)}}])));
 const assign=root.querySelector('[data-scene-assign]');if(assign)assign.onsubmit=guard(e=>{e.preventDefault();const data=new FormData(assign);run([{op:'scene.cell.set',target:scene.id,values:{regionId:data.get('regionId'),loop:data.has('loop')}}]);});
 root.querySelector('[data-scene-clear]')?.addEventListener('click',guard(()=>{const cell=scene.cells.find(c=>track.regions.some(r=>r.id===c.regionId));run([{op:'scene.cell.delete',target:scene.id,values:{regionId:cell.regionId}}]);}));
}
