import {compileTempoMap} from './tempo-map.js';
import {compileMeterMap} from './meter-map.js';
import {compileKeyMap} from './key-map.js';
import {exportRegionMusicxml} from './musicxml.js';
export function validateScorePreviewKeys(session,region){
 const tempo=compileTempoMap(session),meter=compileMeterMap(session),start=tempo.beatAtTime(region.start),end=tempo.beatAtTime(region.start+region.duration);
 for(const key of compileKeyMap(session).points){if(key.beat<=start||key.beat>=end)continue;const bar=meter.positionAtBeat(key.beat).bar;if(Math.abs(meter.barStart(bar)-key.beat)>1e-9)throw Error('This region has a mid-bar key change that the score preview cannot display accurately. Export MusicXML to view it in notation software.');}
}
export function scorePreviewView(track,region){if(track?.kind!=='midi'||!region)return '';return `<details data-score-preview><summary>Score preview</summary><div class="button-row"><label>Clef<select data-score-clef>${["treble","bass","alto","tenor"].map(c=>`<option value="${c}" ${c===(track.scoreClef??"treble")?"selected":""}>${c[0].toUpperCase()+c.slice(1)}</option>`).join('')}</select></label><label>Score zoom<select data-score-zoom><option value="0.75">75%</option><option value="1" selected>100%</option><option value="1.25">125%</option><option value="1.5">150%</option></select></label></div><p class="muted">Notation preview of this MIDI region. Edit notes in the piano roll; export MusicXML to continue in notation software.</p><output data-score-status aria-live="polite"></output><div class="daw-score-scroll"><div data-score-sheet role="img" aria-label="MIDI region score"></div></div></details>`;}
export function bindScorePreview(root,{session,track,region,execute,guard}){const panel=root.querySelector('[data-score-preview]');if(!panel)return;const sheet=panel.querySelector('[data-score-sheet]'),status=panel.querySelector('output'),zoom=panel.querySelector('[data-score-zoom]');let renderer=null,pending=false,loaded=false;
 const draw=async()=>{if(pending||!panel.open||!panel.isConnected)return;pending=true;status.textContent='Preparing score…';try{if(!loaded){validateScorePreviewKeys(session,region);const xml=exportRegionMusicxml(session,track,region),module=await import('opensheetmusicdisplay');if(!panel.isConnected)return;const Display=module.OpenSheetMusicDisplay??module.default?.OpenSheetMusicDisplay;renderer=new Display(sheet,{autoResize:false,backend:'svg',drawingParameters:'compacttight',drawTitle:true});await renderer.load(xml);if(!panel.isConnected){renderer.clear();return;}loaded=true;}renderer.Zoom=Number(zoom.value);renderer.render();sheet.setAttribute('aria-label',`Score for ${region.name}`);status.textContent='Score preview ready.';}catch(error){sheet.replaceChildren();loaded=false;renderer=null;if(panel.isConnected)status.textContent=error.message||'Unable to render this score.';}finally{pending=false;}};
 panel.querySelector('[data-score-clef]').onchange=guard(e=>execute([{op:'track.set',target:track.id,values:{scoreClef:e.target.value}}],'Changed score clef'));
 panel.addEventListener('toggle',()=>{if(panel.open)void draw();});zoom.onchange=()=>void draw();if(panel.open)void draw();
}
