import {z} from 'zod';
import {validateRouting} from './routing.js';
const options=z.object({trackIds:z.string().min(1).max(13000),name:z.string().trim().min(1).max(200),id:z.string().min(1).max(100).regex(/^[a-zA-Z0-9_-]+$/).optional(),output:z.string().min(1).max(100).nullable().optional()}).strict();
export function summingGroupPlan(session,values){
 if(values.trackIds==='')throw Error('Select at least one track.');
 const v=options.parse(values),ids=v.trackIds.split(',');if(ids.length>127||new Set(ids).size!==ids.length||ids.some(id=>!id))throw Error('Choose distinct tracks for the group.');if(session.tracks.length>=128)throw Error('The session already has 128 tracks.');
 const chosen=new Set(ids),tracks=session.tracks.filter(t=>chosen.has(t.id));if(tracks.length!==ids.length||tracks.some(t=>t.kind==='video'))throw Error('Choose existing audio, instrument or bus tracks.');
 const byId=new Map(session.tracks.map(t=>[t.id,t]));for(const t of tracks){let next=t.output;const visited=new Set();while(next){if(visited.has(next))throw Error('Existing routing contains a feedback loop.');visited.add(next);if(chosen.has(next))throw Error('Choose a parent bus or its subtracks, not both.');next=byId.get(next)?.output;}}
 const outputs=new Set(tracks.map(t=>t.output??null));if(v.output===undefined&&outputs.size>1)throw Error('Selected tracks have different outputs. Choose the group output explicitly.');const output=v.output===undefined?[...outputs][0]:v.output;
 if(output!==null&&byId.get(output)?.kind!=='bus')throw Error('Choose an existing bus output or Master.');if(chosen.has(output))throw Error('The group output cannot be one of its own tracks.');
 return {tracks,output,name:v.name,id:v.id,index:session.tracks.indexOf(tracks[0])};
}
export function createSummingGroup(session,values,makeTrack){
 const plan=summingGroupPlan(session,values),group=makeTrack({id:plan.id??crypto.randomUUID(),name:plan.name,kind:'bus',gainDb:0,pan:0,mute:false,solo:false,instrument:'triangle',regions:[],output:plan.output});
 const selected=new Set(plan.tracks.map(t=>t.id));for(const t of plan.tracks)t.output=group.id;session.tracks=session.tracks.filter(t=>!selected.has(t.id));session.tracks.splice(plan.index,0,group,...plan.tracks);validateRouting(session);return group;
}
export function summingGroupView(session,esc){const tracks=session.tracks.filter(t=>t.kind!=='video');if(!tracks.length)return '';return `<details class="daw-summing-group"><summary>Create summing group</summary><form data-summing-group><label>Group name<input name="name" maxlength="200" value="New group" required></label><fieldset><legend>Tracks to group</legend>${tracks.map(t=>`<label><input type="checkbox" name="trackIds" value="${esc(t.id)}"> ${esc(t.name)} <small>${t.kind==='midi'?'Instrument':t.kind==='bus'?'Bus':'Audio'}</small></label>`).join('')}</fieldset><label>Group output<select name="output"><option value="preserve">Keep shared output</option><option value="master">Master</option>${tracks.filter(t=>t.kind==='bus').map(t=>`<option value="bus:${esc(t.id)}">${esc(t.name)}</option>`).join('')}</select></label><p class="muted">Creates a bus before the selected tracks and routes their main outputs through it. The group starts at unity volume with no effects. Existing sends remain independent, so they can still sound when the group is muted. Use the group’s volume, pan, effects and automation to mix the section.</p><output data-group-preview></output><button type="submit">Create group</button></form></details>`;}
export function bindSummingGroup(root,{session,execute,guard,blocked,select}){
 const form=root.querySelector('[data-summing-group]');if(!form)return;const button=form.querySelector('[type=submit]');const values=()=>({name:form.elements.name.value,trackIds:[...form.querySelectorAll('[name=trackIds]:checked')].map(el=>el.value).join(','),...(form.elements.output.value==='preserve'?{}:{output:form.elements.output.value==='master'?null:form.elements.output.value.slice(4)})});
 const update=()=>{try{const plan=summingGroupPlan(session,values());form.querySelector('[data-group-preview]').textContent=`${plan.tracks.length} tracks → ${plan.name} → ${session.tracks.find(t=>t.id===plan.output)?.name||'Master'}`;button.disabled=false;}catch(e){form.querySelector('[data-group-preview]').textContent=e.message;button.disabled=true;}};
 form.oninput=update;form.onchange=update;form.onsubmit=guard(e=>{e.preventDefault();if(blocked())throw Error('Stop recording or wait for the current operation before grouping tracks.');update();if(button.disabled)return;const id=crypto.randomUUID();execute([{op:'track.createGroup',values:{...values(),id}}],'Created summing group',session.revision);select(id);});update();
}
export function groupMembersView(session,track,esc){if(track.kind!=='bus')return '';const members=session.tracks.filter(t=>t.output===track.id);return `<section class="daw-group-members"><h4>Group inputs · ${members.length}</h4><div class="button-row">${members.map(t=>`<button type="button" data-mix-select="${t.id}">${esc(t.name)}</button>`).join('')||'<span class="muted">No tracks route their main output here.</span>'}</div><p class="muted">Change a track’s Output in Routing to add or remove it. Sends into this bus are additional inputs.</p></section>`;}
