import {z} from 'zod';
import {compileTempoMap} from './tempo-map.js';
const bpm=z.number().finite().min(20).max(300);
const options=z.object({startBeat:z.number().finite().min(0).max(432000),endBeat:z.number().finite().positive().max(432000),fromBpm:bpm,toBpm:bpm,step:z.number().finite().positive().default(.25),curve:z.enum(['linear','easeIn','easeOut','easeInOut']).default('linear'),continueAfter:z.boolean().default(true)}).strict();
export function tempoRampPlan(session,values){
 const v=options.parse(values);if(v.endBeat<=v.startBeat)throw Error('End beat must follow start beat.');
 const intervals=Math.ceil((v.endBeat-v.startBeat)/v.step);if(intervals>256)throw Error('The tempo curve needs more than 256 points. Increase beat spacing.');
 const old=compileTempoMap(session),inside=new Map(old.points.map(p=>[p.beat,p])),shape=t=>v.curve==='easeIn'?t*t:v.curve==='easeOut'?1-(1-t)**2:v.curve==='easeInOut'?t*t*(3-2*t):t;
 const generated=Array.from({length:intervals+1},(_,i)=>{const fraction=i/intervals,beat=i===intervals?v.endBeat:v.startBeat+(v.endBeat-v.startBeat)*fraction;return {beat,bpm:i===intervals&&!v.continueAfter?old.tempoAtBeat(v.endBeat):v.fromBpm+(v.toBpm-v.fromBpm)*shape(fraction),id:inside.get(beat)?.id??crypto.randomUUID()};});
 if(generated.some((p,i)=>i&&p.beat<=generated[i-1].beat))throw Error('Tempo curve spacing is below timeline precision.');
 const points=[...old.points.filter(p=>p.beat<v.startBeat),...generated,...old.points.filter(p=>p.beat>v.endBeat)];
 const timing={tempo:points[0].bpm,tempoChanges:points.slice(1).map(({beat,bpm,id})=>({beat,bpm,id:id??crypto.randomUUID()}))};
 const map=compileTempoMap(timing);
 return {...timing,points:generated,generated:generated.length,duration:map.timeAtBeat(v.endBeat)-map.timeAtBeat(v.startBeat)};
}
export function tempoRampView(session){return `<details data-tempo-ramp-panel><summary>Create tempo curve</summary><form data-tempo-ramp class="daw-cycle"><label>Start beat<input name="startBeat" type="number" min="1" step="any" value="1" required></label><label>End beat<input name="endBeat" type="number" min="1" step="any" value="17" required></label><label>From BPM<input name="fromBpm" type="number" min="20" max="300" step="any" value="${session.tempo}" required></label><label>To BPM<input name="toBpm" type="number" min="20" max="300" step="any" value="${Math.min(300,session.tempo+20)}" required></label><label>Maximum spacing · quarter-note beats<input name="step" type="number" min=".001" step="any" value=".25" required></label><label>Curve<select name="curve"><option value="linear">Linear</option><option value="easeIn">Ease in</option><option value="easeOut">Ease out</option><option value="easeInOut">Ease in and out</option></select></label><label><input name="continueAfter" type="checkbox" checked>Continue at the ending tempo</label><svg data-tempo-ramp-graph viewBox="0 0 600 100" role="img" aria-label="Generated tempo curve" style="width:100%;height:100px"><path fill="none" stroke="currentColor" stroke-width="2"/></svg><output data-tempo-ramp-preview></output><button>Create tempo curve</button></form><p class="muted">Replaces tempo points in the selected beat range. BPM holds between generated points; smaller spacing makes a finer curve. Later existing tempo changes remain. Uncheck Continue to restore the original tempo at the end. MIDI retains musical timing; audio/video and automation retain seconds. Undo restores the entire change.</p></details>`;}
export function bindTempoRamp(root,{session,execute,guard}){
 const form=root.querySelector('[data-tempo-ramp]');if(!form)return;const f=form.elements,button=form.querySelector('button'),preview=form.querySelector('output');
 const values=()=>Object.fromEntries(['startBeat','endBeat','fromBpm','toBpm','step'].map(k=>[k,f[k].value.trim()?Number(f[k].value)-(['startBeat','endBeat'].includes(k)?1:0):NaN]).concat([['curve',f.curve.value],['continueAfter',f.continueAfter.checked]]));
 const update=()=>{try{const plan=tempoRampPlan(session,values()),points=plan.points,lo=Math.min(...points.map(p=>p.bpm)),hi=Math.max(...points.map(p=>p.bpm)),x=p=>10+580*(p.beat-points[0].beat)/(points.at(-1).beat-points[0].beat),y=p=>hi===lo?50:90-80*(p.bpm-lo)/(hi-lo);let path=`M${x(points[0])} ${y(points[0])}`;for(const point of points.slice(1))path+=` H${x(point)} V${y(point)}`;form.querySelector('path').setAttribute('d',path);preview.textContent=`${plan.generated} curve points · ${plan.duration.toFixed(2)} seconds · ${plan.tempoChanges.length} tempo changes in project.`;button.disabled=false;}catch(error){form.querySelector('path').removeAttribute('d');preview.textContent=error.message;button.disabled=true;}};
 form.oninput=update;form.onchange=update;form.onsubmit=guard(event=>{event.preventDefault();update();if(!button.disabled)execute([{op:'tempo.ramp',values:values()}],'Created tempo curve');});update();
}
