import {z} from 'zod';
import {selectedMidiNotes} from './note-selection.js';
const options=z.object({from:z.number().finite().min(0).max(1),to:z.number().finite().min(0).max(1),bounds:z.enum(['phrase','region']).default('phrase'),curve:z.enum(['linear','easeIn','easeOut']).default('linear'),noteId:z.string().optional(),noteIds:z.string().max(2020000).optional()}).strict();
export function velocityRampEdits(region,values){
 const v=options.parse(values),notes=selectedMidiNotes(region,v);if(!notes.length)throw Error('Add or select notes for a velocity ramp.');
 const start=v.bounds==='region'?0:Math.min(...notes.map(n=>n.start)),end=v.bounds==='region'?region.duration:Math.max(...notes.map(n=>n.start));
 return notes.map(n=>{let t=end>start?Math.max(0,Math.min(1,(n.start-start)/(end-start))):0;t=v.curve==='easeIn'?t*t:v.curve==='easeOut'?1-(1-t)**2:t;return {id:n.id,velocity:v.from+(v.to-v.from)*t};});
}
const state=settings=>settings.velocityRamp??={from:40,to:110,bounds:'phrase',curve:'linear',scope:'region'};
export function velocityRampView(settings){const s=state(settings);return `<details class="daw-velocity-ramp"><summary>Velocity ramp · crescendo / decrescendo</summary><form data-velocity-ramp class="button-row"><label>Apply to<select name="scope"><option value="region" ${s.scope==='region'?'selected':''}>All notes in region</option><option value="selected" ${s.scope==='selected'?'selected':''}>Selected notes</option></select></label><label>Start velocity<input name="from" type="number" min="0" max="127" step="1" value="${Number.isFinite(s.from)?s.from:''}" required></label><label>End velocity<input name="to" type="number" min="0" max="127" step="1" value="${Number.isFinite(s.to)?s.to:''}" required></label><label>Ramp spans<select name="bounds"><option value="phrase" ${s.bounds==='phrase'?'selected':''}>First to last chosen note</option><option value="region" ${s.bounds==='region'?'selected':''}>Entire region</option></select></label><label>Curve<select name="curve">${['linear','easeIn','easeOut'].map((v,i)=>`<option value="${v}" ${s.curve===v?'selected':''}>${['Linear','Ease in','Ease out'][i]}</option>`).join('')}</select></label><button type="button" data-ramp-swap>Reverse ramp</button><button>Apply velocity ramp</button></form><div data-ramp-chart></div><output data-ramp-preview></output><p class="muted">Sets note-on velocities by start time. Simultaneous notes receive the same value; a single onset uses the start velocity. Zero silences a note. For a swell during a held note, use expression or volume automation.</p></details>`;}
export function bindVelocityRamp(root,{region,settings,execute,guard}){
 const form=root.querySelector('[data-velocity-ramp]');if(!form)return;const s=state(settings),button=form.querySelector('button:not([type])'),chart=root.querySelector('[data-ramp-chart]'),preview=root.querySelector('[data-ramp-preview]');
 const values=()=>({from:s.from/127,to:s.to/127,bounds:s.bounds,curve:s.curve,...(s.scope==='selected'?{noteIds:(settings.selectedIds||[]).join(',')}:{})});
 const update=()=>{for(const key of ['from','to'])s[key]=form.elements[key].value===''?NaN:Number(form.elements[key].value);for(const key of ['bounds','curve','scope'])s[key]=form.elements[key].value;try{if([s.from,s.to].some(v=>!Number.isInteger(v)||v<0||v>127))throw Error('Enter whole-number velocities from 0 to 127.');if(s.scope==='selected'&&!settings.selectedIds?.length)throw Error('Select notes in the piano roll first.');const edits=velocityRampEdits(region,values()),byId=new Map(region.notes.map(n=>[n.id,n])),changed=edits.filter(e=>Math.abs(e.velocity-byId.get(e.id).velocity)>1e-9).length;chart.innerHTML=`<svg viewBox="0 0 400 80" role="img" aria-label="Preview of note velocities after applying the ramp" style="width:100%;max-width:600px;height:100px;color:var(--accent)">${edits.map(e=>`<line x1="${4+byId.get(e.id).start/region.duration*392}" x2="${4+byId.get(e.id).start/region.duration*392}" y1="76" y2="${76-e.velocity*72}" stroke="currentColor" stroke-width="3"/>`).join('')}</svg>`;preview.textContent=`${changed} of ${edits.length} notes will change.`;button.disabled=!changed;}catch(e){preview.textContent=e.message;chart.innerHTML='';button.disabled=true;}};
 form.oninput=update;form.onchange=update;form.querySelector('[data-ramp-swap]').onclick=()=>{const from=form.elements.from.value;form.elements.from.value=form.elements.to.value;form.elements.to.value=from;update();};form.onsubmit=guard(e=>{e.preventDefault();update();if(!button.disabled)execute([{op:'notes.velocityRamp',target:region.id,values:values()}],'Applied MIDI velocity ramp');});update();
}
